### ISSUE TITLE
Upcoming incompatibility in HA Core 2025.1.

### ISSUE THREAD

**Issue by jaal2001** [kongo09/philips-airpurifier-coap#102]
The 2024.1 release of HA produces a lot of warning for the 2025.1 release:

WARNING (MainThread) [homeassistant.components.fan] SUPPORT_PRESET_MODE was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.components.fan] SUPPORT_SET_SPEED was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.components.fan] SUPPORT_PRESET_MODE was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.components.fan] SUPPORT_SET_SPEED was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.components.sensor] STATE_CLASS_MEASUREMENT was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.components.sensor] STATE_CLASS_MEASUREMENT was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_HUMIDITY was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.HUMIDITY instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_TEMPERATURE was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.const] TIME_HOURS was used from philips_airpurifier_coap, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.HOURS instead, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.philips_airpurifier_coap.philips.PhilipsAC4550'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <FanEntityFeature.SET_SPEED|PRESET_MODE: 9>, please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by kongo09** [comment]
Thanks for highlighting this, I really need to find some time...

**Comment by kongo09** [comment]
fixed in v0.16.0
