### ISSUE TITLE
This is its IP, just no longer seems to connect (it does ping)

### ISSUE THREAD

**Issue by TheBartoMan** [kongo09/philips-airpurifier-coap#108]
This error originated from a custom integration.

Logger: custom_components.philips_airpurifier_coap.philips
Source: custom_components/philips_airpurifier_coap/philips.py:125
Integration: Philips AirPurifier (with CoAP) (documentation, issues)
First occurred: 20:22:50 (2 occurrences)
Last logged: 20:25:54

Config not ready, first refresh failed for host 192.168.1.144

**Comment by kongo09** [comment]
Philips devices seem to have a connectivity problem that I cannot fix

**Comment by kongo09** [comment]
Might be similar to #25
