### ISSUE TITLE
Mods/Presets are not working. CX5120

### ISSUE THREAD

**Issue by ghost** [kongo09/philips-airpurifier-coap#114]
Since the last update (official realse, not the beta) the modes are not working. I Can turn on the Device and off but not on and mode 'high'. 

[home-assistant_philips_airpurifier_coap_2024-01-24T19-57-17.453Z.log](https://github.com/kongo09/philips-airpurifier-coap/files/14043059/home-assistant_philips_airpurifier_coap_2024-01-24T19-57-17.453Z.log)

_Originally posted by @Stoffiiii in https://github.com/kongo09/philips-airpurifier-coap/issues/95#issuecomment-1908825414_

**Comment by kongo09** [comment]
Which one is the last working beta?

**Comment by ghost** [comment]
Good question. Think it was Beta 17-22

**Comment by kongo09** [comment]
Can you please downgrade and try?

**Comment by ghost** [comment]
i try Beta 23 (it's the lowest one i can select). There it also doesnt work :(

**Comment by Anashost** [comment]
Im still on Beta 16, everything works here.

**Comment by kongo09** [comment]
please try v0.18.1

**Comment by ghost** [comment]
yeees. Working fine

**Comment by KeyboardZombie** [comment]
this post should be top google result, took me ages to find a working version of this.

**Comment by kongo09** [comment]
I found an inconsistency in the preset and speed settings for CX5120. Can someone please check if you can set the device to ventilation mode when it is switched off and the last setting before switching it off was auto mode?

**Comment by kongo09** [comment]
Version v0.18.11-beta.1 should fix this, please try if this works for you
