### ISSUE TITLE
Support Philips AC3858/86 model

### ISSUE THREAD

**Issue by tomliau33** [kongo09/philips-airpurifier-coap#115]
I have a Philips AC3858/86, which originally wasn't supported. I tried modifying the code to rename AC3858/51 to AC3858/86 and found that it works fine. I hope AC3858/86 can be added to the supported list, with the same settings as AC3858/51. Thank you!

**Comment by kongo09** [comment]
please try: [v0.18.2](https://github.com/kongo09/philips-airpurifier-coap/releases/tag/v0.18.2)

**Comment by tomliau33** [comment]
I had updated to v0.18.2 and it worked.
Thank you!
