### ISSUE TITLE
Missing entities for AC3829

### ISSUE THREAD

**Issue by mzaferyahsi** [kongo09/philips-airpurifier-coap#124]
Hi,

I seem to have an issue with some of the entities on my AC3829. I am running ‘v0.18.6’ of the plugin with Home Assistant ‘2022.1.4’ running on Kubernetes.

![IMG_8870](https://github.com/kongo09/philips-airpurifier-coap/assets/4150565/ade7dbe7-0630-4693-83b9-9f5fda00880e)
![IMG_8869](https://github.com/kongo09/philips-airpurifier-coap/assets/4150565/d66c3c1e-a9a1-4b0c-bcac-3f608cc2db4e)
![IMG_8871](https://github.com/kongo09/philips-airpurifier-coap/assets/4150565/c14c9147-94f1-430a-a576-3366c9325c90)

**Comment by kongo09** [comment]
`Air Quality Index` never was a sensor, but a mistake. I'm sure it was on the same level for you all the time. I've now removed it according to the dicussion here #116 

The other missing entities seem like a renaming in your HA installation. I can see the new filters above with new names. Simply delete the old entities.
