### ISSUE TITLE
Entity sensor.device_total_volatile_organic_compounds (AC2889)

### ISSUE THREAD

**Issue by jaal2001** [kongo09/philips-airpurifier-coap#125]
Hi,
with HA 2024.2.2 there is a new warning, which seems affect AC2889 (and not AC4550):

`2024-02-20 15:13:09.284 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.device_total_volatile_organic_compounds (<class 'custom_components.philips_airpurifier_coap.sensor.PhilipsSensor'>) is using native unit of measurement 'L' which is not a valid unit for the device class ('volatile_organic_compounds') it is using; expected one of ['µg/m³']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues`

**Comment by kongo09** [comment]
fixed, will be live in next release

**Comment by jaal2001** [comment]
Now HA does also displays this message for my AC4550.
