### ISSUE TITLE
Not a valid unit for the device class 

### ISSUE THREAD

**Issue by NIVO-1** [kongo09/philips-airpurifier-coap#126]
Hi,
First of all I want to say thanks for a great add-on to Home Assistant.

When I startup my Home Assistant I get an error like below.

Hopefully you see what is the issue here.

The version of the add-on is 0.18.6

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:737
integration: Sensor (documentation, issues)
First occurred: 20:41:14 (1 occurrences)
Last logged: 20:41:14

Entity sensor.sovrum_total_volatile_organic_compounds (<class 'custom_components.philips_airpurifier_coap.sensor.PhilipsSensor'>) is using native unit of measurement 'L' which is not a valid unit for the device class ('volatile_organic_compounds') it is using; expected one of ['µg/m³']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

Regards
Niklas

**Comment by kongo09** [comment]
Which device do you have?

**Comment by NIVO-1** [comment]
Hi,The model is AC3033. RegardsNiklas20 mars 2024 kl. 00:46 skrev kongo09 ***@***.***>:﻿
Which device do you have?

**Comment by kongo09** [comment]
Can you please try 0.18.7 and check if the problem still exists?

**Comment by NIVO-1** [comment]
Hi,

Now the unit measurement is set to None.



Regards
Niklas

**Comment by kongo09** [comment]
Do you have a source for the correct unit?

There was some discussion here: #116

**Comment by NIVO-1** [comment]
Hi,

Don’t know exactly what you mean.

Here is the entity properties:
state_class: measurement
device_class: volatile_organic_compounds
icon: mdi:blur
friendly_name: Sovrum Total Volatile Organic Compounds

Regards
Niklas


Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:737
integration: Sensor (documentation <https://www.home-assistant.io/integrations/sensor>, issues <https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22>)
First occurred: 08:45:53 (1 occurrences)
Last logged: 08:45:53

Entity sensor.sovrum_total_volatile_organic_compounds (<class 'custom_components.philips_airpurifier_coap.sensor.PhilipsSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('volatile_organic_compounds') it is using; expected one of ['µg/m³']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues

**Comment by kongo09** [comment]
I know the properties in HA. I mean, I programmed them. What is your Philips app showing as units? Can you please share a screen shot?

**Comment by NIVO-1** [comment]
Hope this is the info you are after.

/Niklas

**Comment by kongo09** [comment]
I don't see anything?

**Comment by NIVO-1** [comment]
Strange, it was a jpeg file.

Anyway, here is a pdf version
/Niklas

**Comment by kongo09** [comment]
There is nothing in GitHub

**Comment by NIVO-1** [comment]
Hi,

This is very strange…

If I look at that value inside the att it says ”IAI”

/Niklas

**Comment by kongo09** [comment]
Which is why it has no unit. It's an index.

**Comment by NIVO-1** [comment]
Shall I just add the unit in HA then?

**Comment by kongo09** [comment]
IAI has no unit and the device class should not require one

But your initial issue was about TVOC? So what is the unit in the app for TVOC? Can you share a screenshot of that?

**Comment by NIVO-1** [comment]
Sorry, wrong by me.

I only see PM2.5, IAI and Gas levels inside the app.

**Comment by kongo09** [comment]
So the error belongs to a sensor the service actually doesn't have?

**Comment by NIVO-1** [comment]
That might be so, wonder why I see the entity in HA with the value of one.

I have now added the entity to the recorder so I can monitor if the value is changing over the days.
/Niklas

**Comment by kongo09** [comment]
The integration picks up the sensor data if the data field is available in the data stream and automatically creates the corresponding sensor. That doesn't mean that the value actually makes any sense. So I'm curious to hear if it even changes over time for you. If you confirm not, then I can remove the sensor for this model in the code.

**Comment by NIVO-1** [comment]
Will keep you updated.
/Niklas

**Comment by NIVO-1** [comment]
I saw the sensor was increased to ”2” for 1,5 hour yesterday. So something is there :-)

**Comment by jaal2001** [comment]
I do have the same issue 4550.
This device does provide Allergene (IAI), PM2.5 and gas concentration (I assume this should be tvoc), where only PM2.5 seems to have a unit.

**Comment by jaal2001** [comment]
Issue still exists

**Comment by kongo09** [comment]
I'm not entirely sure what to do with this issue. Is there a bug or not? If so, what is the bug? Is it about the wrong unit of a sensor value or is it about a sensor showing data in HA but reality that sensor doesn't exist?

**Comment by jaal2001** [comment]
Sorry, I have uninstalled the integration, so I can't test it anymore. As far as I remember it was still bragging about a false unit type for the sensor.

**Comment by THETCR** [comment]
@kongo09 
For the AC4236 the logs of HA state that it is set to 'None' instead of the required 'µg/m³'.

**Comment by kongo09** [comment]
So let's assume this is indeed 'µg/m³' - I'll change it in the next update.
