### ISSUE TITLE
turbo preset no longer available?

### ISSUE THREAD

**Issue by user897943** [kongo09/philips-airpurifier-coap#13]
On the previous integration:
```
preset_modes: 1, 2, 3, allergen, auto, bacteria, sleep, turbo
preset_mode: auto
icon: mdi:air-purifier
friendly_name: Air Purifier - 1st floor
supported_features: 8
```

On this integration:
```
preset_modes: allergen, auto, bacteria, sleep
percentage: null
percentage_step: 25
preset_mode: auto
name: 1st level
type: AC2889
model_id: AC2889/10
product_id: be10acb2e62411e8a1e3061302926720
device_id: a59e5dbe729a11eb9be206c551001531
software_version: 1.0.7
wifi_version: AWS_Philips_AIR@69.1
error_code: 0
error: 0
preferred_index: PM2.5
runtime: 1:22:44
icon: pap:auto_mode
friendly_name: Purifier - 1st level
supported_features: 9
```

I am struggling to understand how to set the speed. I am currently using 100% as 3, 66% as 2, and 33% as 1 as a workaround. But this doesn't seem right.

The AC2889 does not have percentage speed, it's either 1, 2 or 3 and there's a turbo mode. Then there's the allergen, bacteria & virus, sleep, auto, and turbo.

I noticed on "percentage step" that you're dividing into quarters. This would allow 25=1, 50=2, 75=3, 100=turbo, is that a correct assumption?

**Comment by user897943** [comment]
PS. The icons don't seem to be changing, where are they supposed to change? Is it for the fan.* entity? I already cleared cache...

**Comment by jutonium** [comment]
Turbo is essentially 100% fan speed. The others are 25, 50, and 75. Changing between these shows the expected number in the display for a few seconds.
e.g.
```
action:
  - service: fan.set_percentage
    data:
      percentage:
          100
    target:
      entity_id: fan.ac2889
```
will display 't'.

The icon of the entity does change in my installation. But sometimes it gets stuck. That seems to be connected to the known connectivity issue.

**Comment by user897943** [comment]
> Turbo is essentially 100% fan speed. The others are 25, 50, and 75. Changing between these shows the expected number in the display of the air purifier for a few seconds. e.g.
> 
> ```
> action:
>   - service: fan.set_percentage
>     data:
>       percentage:
>           100
>     target:
>       entity_id: fan.ac2889
> ```
> 
> will display 't'.
> 
> The icon of the entity does change in my installation. But sometimes it gets stuck. That seems to be connected to the known connectivity issue.

I confirm that to be the case.

One thing I noticed is that this integration will halt home assistant startup completely until the purifier is online. So if for any reason the purifier can't be reached during startup of Home Assistant then the procedure will hang indefinitely. I tested this over and over.

What needs to happen:
1. Integration tries to establish connection with each purifier for only 10 seconds.
2. If established connection to each purifier within 10 seconds continue as normal, if however no connection was made within 10 seconds then let HA continue startup but integration should keep retrying on the background
3. If integration retries on the background and connects, it should count how many seconds and automatically adjust for subsequent restarts of HA, but up to a max of 60 seconds.
4. If integration can't reach purifier for more than 60 seconds assume purifier is offline and write message to HA log.

Why should this be the case?
For obvious reasons HA should not stop working because of one integration holding it indefinitely. All my lighting automations with sensors stopped working and that's how I found out, after a HA update earlier.

**Comment by kongo09** [comment]
> this integration will halt home assistant startup completely until the purifier is online

this issue is about the turbo preset mode. Please open a separate issue.

**Comment by kongo09** [comment]
> Turbo is essentially 100% fan speed

Yes, that's how it is handled right now, as @user897943 already confirmed. It's a bit of a design choice. The other preset modes seem to do more sophisticated things than just setting the fan speed, e.g. the sleep setting seems to do more like diming lights. That's why I singled the turbo mode out and put it together with the speed settings as maximum speed.

I have to admit that this is somewhat arbitrary and you might disagree. The Clean Home+ app also puts turbo together with the speed levels, but also includes sleep there. If the community feels that sleep should be eliminated as a preset and also go into the speed setting, I'm happy to change that.

**Comment by user897943** [comment]
Can you please not touch the presets? Speed is 1, 2, and 3. Presets are presets... It should simply emulate the Clean Home app...

I don't understand what you mean by opening a new issue for the turbo mode. My purifier was off when HA got stuck initializing because the integration couldn't reach the purifier... Indefinitely...

**Comment by kongo09** [comment]
Please read my comment. The Clean Home app treats the `turbo` setting as a speed, not a preset.

![image](https://user-images.githubusercontent.com/640121/163451741-37615414-2d1a-4540-b5a2-dc695fbdac2e.png)

**Comment by user897943** [comment]
Wait, what? Sorry if I'm confused but on home assistant I'm pretty sure that everything was actually a preset. Because after installing your integration I had to amend the automations to do call service fan speed instead of call service fan preset... On the presets I could even put the speeds 1, 2, or 3. Now I have to use a percentage. I understand you might wanna harmonize things but I think it should stay the way the manufacturer intended, so basically everything is a preset including the 1, 2, and 3. It doesn't make sense to have a percentage when the unit is coded to rotate the motor at precisely 25, 50, 75 and 100. It is confusing, most people won't know that, it actually took a while for it to sink in for me after looking at the state attributes and noticing "percentage step 25". But I think most people are used to doing it via presets. You don't have to change anything but honestly, I think it should mirror what Philips did on their app. I'm good either way, my dashboard has been amended. But unfortunately now I lose the ability to see the setting when it's one of the "fan speeds" and not the presets. Let me show:
![Screenshot_20220414-221056](https://user-images.githubusercontent.com/5891221/163475908-d69fdd76-68f2-48f7-80e4-b105a6e6dbab.png)
As you can see the first level shows the name of the preset from the attributes.
But the 2nd shows a --- because it's the speed percentage... So now I lost a way to display which mode is running. I think you should revert so that it's all presets, that way the mode/speed can be gathered from the state attributes like before.

**Comment by kongo09** [comment]
I see your challenge. At the same time, I wanted to support the proper `fan` model of HA which deals with speed settings.

But what about the following idea:

- I stick the `sleep`, `night` setting into the speed settings as well to make that consistent with the Clean Home+ app
- I also stick the speed settings into the preset modes, to have both worlds available

It's a bit redundant then, but different people prefer different approaches and there is a clear case for the speed setting as well, e.g. if you have a group of devices from different manufacturers in the same room and ask the group to go to a certain percentage of fan speed. You can't do this with speed only being available through presets.

**Comment by user897943** [comment]
> I see your challenge. At the same time, I wanted to support the proper `fan` model of HA which deals with speed settings.
> 
> But what about the following idea:
> 
> * I stick the `sleep`, `night` setting into the speed settings as well to make that consistent with the Clean Home+ app
> * I also stick the speed settings into the preset modes, to have both worlds available
> 
> It's a bit redundant then, but different people prefer different approaches and there is a clear case for the speed setting as well, e.g. if you have a group of devices from different manufacturers in the same room and ask the group to go to a certain percentage of fan speed. You can't do this with speed only being available through presets.

Yes, having both ways would be amazing! I didn't know it was possible :) I appreciate your open-mindedness here. I understand what you mean in terms of different models/brands being able to operate because you're following the fan model. So having both ways solves both use cases.

**Comment by kongo09** [comment]
I don't know if it works, but I'll take a look

**Comment by user897943** [comment]
Many thanks for implementing!

Can I ask if it's possible to report the speeds as just the numbers? You'll see why below:

![Screenshot_20220418-224113](https://user-images.githubusercontent.com/5891221/163882366-44525626-02da-4b96-b22d-9e3451fe00e9.png)

**Comment by kongo09** [comment]
I'd like to keep the naming consistent with the Philips app. If that doesn't fit in your frontend, I suggest you use templates to modify the display.
