### ISSUE TITLE
Not connected ? Maybe some new information about AC2889

### ISSUE THREAD

**Issue by DaisyF8** [kongo09/philips-airpurifier-coap#131]
I finally got in contact with a living person at Philips/Versuni helpdesk. My device is connected to wifi, but the app would say "not connected".  I just wanted to give you the contents of these mails.  Maybe there is something in there (_maybe setting **Multi To Unicast** to ON in the router, and surely providing wan-access without limit_) that could be of use.

My model 
`{"name": "Air Purifier", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "range": "Comfort", "Runtime": 653184, "rssi": -39, "otacheck": false, "wifilog": false, "free_memory": 54824, "WifiVersion": "AWS_Philips_AIR@73.1", ...`

Their mail today 

> Dear Sir/Madam,
> 
> Thank you for bringing your disconnection issue to our attention, we are sorry you are experiencing this issue. Our team is conducting an investigation and identified a potential cause related to the firmware reconnect mechanism with some routers. We will develop and release a new Wi-Fi firmware version as soon as possible to solve it. Until we have developed this new firmware for you, prevention of disconnection can be done by either keeping your router and device online consistently or by adjusting your router's WPA settings to WPA2.
> 
> In the meantime, we are busy investigating and would appreciate your assistance in providing the following information:
> 1. In the past 2 weeks, has your device been plugged in or is it currently unplugged?
> 2. Could you provide us with the model of your router and whether you have made any special configurations to the router recently?
> 3. What was the Wi-Fi icon status of your device when you found the device offline.  (On, not showing or blinking)
> 
> We apologize for any inconvenience this may cause and appreciate your patience and support.
> 
> Best regards,
> 
> Philips Consumer Care Team

My response today

> So my situation is better now (but not ideal). Some time a few months ago AC2889/10 stopped working according to schedule. This is fixed now, see below "some extra information".  I still would like some kind of firmware revision concerning lan behaviour while not connected to wan (in any case if Philips/Versuni servers ever were to close down).
> 
> After experimenting AC2889/10 is now stable connected with a WPA2 wifi-network, with unlimited access to lan and wan.  Constant on non-flashing white connect symbol; on and off schedule (my main concern) is working without flaw.
> 
> As far as your questions go :
> 1. AC2889/10 has been on and connected the same way since april 10; with constant on non-flashing connect symbol. Haven't touched it except for some adjusting of the scheduling in the app (I use both air-matters and air+ app). The week before april 10 was experimentation that resulted in broken connectivity.  AC2889/10 wouldn't turn on according to the schedule even though it had a constant on non-flashing white connect symbol.
> 2. Router is Netgear R7800 with OpenWRT firmware (firmware has not changed for two years).  My IoT-devices are in a subnet without access to wan, but they do have access to lan-devices.  AC2889/10 has been in this IoT-subnet since april 10 but with rules active that provide unfiltered wan access. As far as AC2889/10 is concerned it has full lan and wan access.
> 3. When I found my device to be offline in the app (I think that is what you are asking) the wifi-symbol would be constant on non-flashing.
> 
> Some extra information : 
> 
> The IoT-subnet is new, I didn't use to have it before april 10.  Before april 10 AC2889/10 would be in a separate 2.4Ghz network, but every device was open to lan and wan, just like my main 5Ghz network.  Some time a couple of months ago, AC2889/10 suddenly stopped working according to the scheduler (firmware update ?). I would notice the app showing the device offline. I did a lot of experimenting but couldn't solve it until...
>
> I very well may be wrong, but my feeling is that setting Multi To Unicast to ON in the router fixed the scheduler and device offline error (description : "ARP, IPv4 and IPv6 (even 802.1Q) with multicast destination MACs are unicast to the STA MAC address. Note: This is not Directed Multicast Service (DMS) in 802.11v. Note: might break receiver STA multicast expectations".)  This could've been a fluke, mere coincidence... I'm not going to test this now until maybe after a reply from you. I could then turn the setting to OFF and see if it messes up the scheduler again.
> 
> It seems currently AC2889/10 doesn't accept absence of wan, and the setup process will error out in the step following connecting AC2889/10 to lan-wifi.  If you provide wan during setup (so you don't get the error), and after setup take wan away, AC2889/10 will show not connected in the app.  So both Multi To Unicast to ON and wan-connectivity are conditions to be present for the app and AC2889/10 to work correctly
> 
> I would like AC2889/10 to work with the app on lan even if there is no wan-connectivity.  I very much want to have a working setup, and then close the door to wan for all my IoT-devices. Hope to hear from you.

**Comment by DaisyF8** [comment]
I've been following https://github.com/rgerganov/py-air-control/blob/master/README.md and for example

`aioairctrl --host 10.20.40.206 set om=2`

works.

I'm new to all this... Is this a recent fix ?

**Comment by mitompl** [comment]
I also still have an issue with AC2889/10 as reported under #83 .. and yes, also on my network config, using aioairctrl  just works...

**Comment by DaisyF8** [comment]
Thanks for the info... The other thread is a very relaxing read : 😁

**Comment by mitompl** [comment]
I would say it still requires some further investigation. I believe that there is only small little bug inside.
