### ISSUE TITLE
Timeout, host x.x.x.x looks like a Philips AirPurifier but doesn't answer, aborting

### ISSUE THREAD

**Issue by 011V32** [kongo09/philips-airpurifier-coap#135]
Sometimes I got the following error at startup:

> This error originated from a custom integration.
> 
> Logger: custom_components.philips_airpurifier_coap.config_flow
> Source: custom_components/philips_airpurifier_coap/config_flow.py:84
> integration: Philips AirPurifier (documentation, issues)
> First occurred: May 24, 2024 at 11:40:21 (1 occurrences)
> Last logged: May 24, 2024 at 11:40:21
> 
> Timeout, host x.x.x.x looks like a Philips AirPurifier but doesn't answer, aborting

The IP would be the correct one.
What could be here the problem?

**Comment by 011V32** [comment]
No changes so far...

**Comment by kongo09** [comment]
This feels like the connectivity problem that many users of Philips devices report. Often it works, then suddenly for whatever reasons it doesn't. Some users report that connecting with the Philips mobile app and interacting with the device gets it back working on HA as well. Some people power cycle and it helps. Or not.

I'm sorry, I have no idea what that is or how to solve this or if it is even solvable or an internal Philips problem.
