### ISSUE TITLE
Fan CX3550/01 Missing

### ISSUE THREAD

**Issue by BA2000** [kongo09/philips-airpurifier-coap#137]
Hi,
is it possible to add the New Philips WLAN Fan cx3550?
It can be controled by the Philips Air+ App, as well as the  Philips Purifier AC2889.

Greetings 
BA2000

**Comment by martlxmartl** [comment]
Hi Kongo,
thanks for your great work!

Here is the data obtained by aioairctrl. Hope this is all you need!

Mode fanspeed 1:
{"D01102": 2, "D01S03": "Schlafzimmer", "D01S04": "Trident", "D01S05": "CX3550/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D01S0D": "688001001145", "D0110F": 3, "D01S12": "0.1.4", "D01213": 0, "ProductId": "b3d240e5b11711ee88c206d016384e4a", "DeviceId": "e602901434a111efa50741069bbc8fb7", "otacheck": false, "Runtime": 8618136, "rssi": -35, "wifilog": false, "free_memory": 155296, "WifiVersion": "AWS_Philips_AIR_Combo@2.5", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03105": 100, "D0310A": 1, "D0310C": 1, "D0310D": 1, "D0320F": 23040, "D03110": 0, "D03130": 100, "aqit_ext": 0}
Mode fanspeed2:
{"D01102": 2, "D01S03": "Schlafzimmer", "D01S04": "Trident", "D01S05": "CX3550/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D01S0D": "688001001145", "D0110F": 3, "D01S12": "0.1.4", "D01213": 0, "ProductId": "b3d240e5b11711ee88c206d016384e4a", "DeviceId": "e602901434a111efa50741069bbc8fb7", "otacheck": false, "Runtime": 8658234, "rssi": -37, "wifilog": false, "free_memory": 155216, "WifiVersion": "AWS_Philips_AIR_Combo@2.5", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03105": 100, "D0310A": 1, "D0310C": 2, "D0310D": 2, "D0320F": 23040, "D03110": 0, "D03130": 100, "aqit_ext": 0}
Mode fanspeed3:
{"D01102": 2, "D01S03": "Schlafzimmer", "D01S04": "Trident", "D01S05": "CX3550/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D01S0D": "688001001145", "D0110F": 3, "D01S12": "0.1.4", "D01213": 0, "ProductId": "b3d240e5b11711ee88c206d016384e4a", "DeviceId": "e602901434a111efa50741069bbc8fb7", "otacheck": false, "Runtime": 8799036, "rssi": -48, "wifilog": false, "free_memory": 155488, "WifiVersion": "AWS_Philips_AIR_Combo@2.5", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03105": 100, "D0310A": 1, "D0310C": 3, "D0310D": 3, "D0320F": 23040, "D03110": 0, "D03130": 100, "aqit_ext": 0}
Mode "sleep":
{"D01102": 2, "D01S03": "Schlafzimmer", "D01S04": "Trident", "D01S05": "CX3550/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D01S0D": "688001001145", "D0110F": 3, "D01S12": "0.1.4", "D01213": 0, "ProductId": "b3d240e5b11711ee88c206d016384e4a", "DeviceId": "e602901434a111efa50741069bbc8fb7", "otacheck": false, "Runtime": 8859378, "rssi": -37, "wifilog": false, "free_memory": 155296, "WifiVersion": "AWS_Philips_AIR_Combo@2.5", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03105": 0, "D0310A": 1, "D0310C": 17, "D0310D": 2, "D0320F": 23040, "D03110": 0, "D03130": 100, "aqit_ext": 0}
Mode "natural":
{"D01102": 2, "D01S03": "Schlafzimmer", "D01S04": "Trident", "D01S05": "CX3550/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D01S0D": "688001001145", "D0110F": 3, "D01S12": "0.1.4", "D01213": 0, "ProductId": "b3d240e5b11711ee88c206d016384e4a", "DeviceId": "e602901434a111efa50741069bbc8fb7", "otacheck": false, "Runtime": 8918566, "rssi": -44, "wifilog": false, "free_memory": 155296, "WifiVersion": "AWS_Philips_AIR_Combo@2.5", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03105": 100, "D0310A": 1, "D0310C": -126, "D0310D": 1, "D0320F": 23040, "D03110": 0, "D03130": 100, "aqit_ext": 0}
Mode "natural" but static angle:
{"D01102": 2, "D01S03": "Schlafzimmer", "D01S04": "Trident", "D01S05": "CX3550/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D01S0D": "688001001145", "D0110F": 3, "D01S12": "0.1.4", "D01213": 0, "ProductId": "b3d240e5b11711ee88c206d016384e4a", "DeviceId": "e602901434a111efa50741069bbc8fb7", "otacheck": false, "Runtime": 8999362, "rssi": -48, "wifilog": false, "free_memory": 155296, "WifiVersion": "AWS_Philips_AIR_Combo@2.5", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03105": 100, "D0310A": 1, "D0310C": -126, "D0310D": 2, "D0320F": 0, "D03110": 0, "D03130": 100, "aqit_ext": 0}
Turned  off:
{"D01102": 2, "D01S03": "Schlafzimmer", "D01S04": "Trident", "D01S05": "CX3550/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D01S0D": "688001001145", "D0110F": 3, "D01S12": "0.1.4", "D01213": 0, "ProductId": "b3d240e5b11711ee88c206d016384e4a", "DeviceId": "e602901434a111efa50741069bbc8fb7", "otacheck": false, "Runtime": 9039230, "rssi": -48, "wifilog": false, "free_memory": 154944, "WifiVersion": "AWS_Philips_AIR_Combo@2.5", "StatusType": "status", "ConnectType": "Online", "D03102": 0, "D03105": 100, "D0310A": 1, "D0310C": -126, "D0310D": 0, "D0320F": 0, "D03110": 0, "D03130": 100, "aqit_ext": 0}
Mode "natural", static, 3h timer:
{"D01102": 2, "D01S03": "Schlafzimmer", "D01S04": "Trident", "D01S05": "CX3550/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D01S0D": "688001001145", "D0110F": 3, "D01S12": "0.1.4", "D01213": 0, "ProductId": "b3d240e5b11711ee88c206d016384e4a", "DeviceId": "e602901434a111efa50741069bbc8fb7", "otacheck": false, "Runtime": 9099442, "rssi": -49, "wifilog": false, "free_memory": 154944, "WifiVersion": "AWS_Philips_AIR_Combo@2.5", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03105": 100, "D0310A": 1, "D0310C": -126, "D0310D": 1, "D0320F": 0, "D03110": 4, "D03130": 100, "aqit_ext": 0}

**Comment by kongo09** [comment]
Great stuff, thanks. I'm super short on time right now so this won't be a quick one, but the above data is exactly what's needed. I'm sure we'll get this sorted. I'll let you know once I have something to test.

**Comment by werty1st** [comment]
i tried to implement the new values but its not working. should i use another class as starting point?

```python
class PhilipsCX3550(PhilipsNew2GenericCoAPFan):
    """CX3550."""

    AVAILABLE_PRESET_MODES = {
        PresetMode.SPEED_1: {
            PhilipsApi.NEW2_POWER: 1,
            PhilipsApi.NEW2_MODE_A: 1,
            PhilipsApi.NEW2_MODE_B: 1,
            PhilipsApi.NEW2_MODE_C: 1,
        },
        PresetMode.SPEED_2: {
            PhilipsApi.POWER: 1,
            PhilipsApi.NEW2_MODE_A: 1,
            PhilipsApi.NEW2_MODE_B: 2,
            PhilipsApi.NEW2_MODE_C: 2,
        },
        PresetMode.SPEED_3: {
            PhilipsApi.POWER: 1,
            PhilipsApi.NEW2_MODE_A: 1,
            PhilipsApi.NEW2_MODE_B: 3,
            PhilipsApi.NEW2_MODE_C: 3,
        },
        PresetMode.NATURAL: {
            PhilipsApi.POWER: 1,
            PhilipsApi.NEW2_MODE_A: 1,
            PhilipsApi.NEW2_MODE_B: -126,
            PhilipsApi.NEW2_MODE_C: 1,
        },
        PresetMode.SLEEP: {
            PhilipsApi.POWER: 1,
            PhilipsApi.NEW2_MODE_A: 1,
            PhilipsApi.NEW2_MODE_B: 17,
            PhilipsApi.NEW2_MODE_C: 2,
        },
    }
    AVAILABLE_SPEEDS = {
        PresetMode.SPEED_1: {
            PhilipsApi.NEW2_POWER: 1,
            PhilipsApi.NEW2_MODE_A: 1,
            PhilipsApi.NEW2_MODE_B: 1,
            PhilipsApi.NEW2_MODE_C: 1,
        },
        PresetMode.SPEED_2: {
            PhilipsApi.POWER: 1,
            PhilipsApi.NEW2_MODE_A: 1,
            PhilipsApi.NEW2_MODE_B: 2,
            PhilipsApi.NEW2_MODE_C: 2,
        },
        PresetMode.SPEED_3: {
            PhilipsApi.POWER: 1,
            PhilipsApi.NEW2_MODE_A: 1,
            PhilipsApi.NEW2_MODE_B: 3,
            PhilipsApi.NEW2_MODE_C: 3,
        },
    }
    KEY_OSCILLATION = {
        PhilipsApi.NEW2_OSCILLATION: PhilipsApi.OSCILLATION_MAP_2,
    }

    AVAILABLE_LIGHTS = [PhilipsApi.NEW2_DISPLAY_BACKLIGHT2]
    AVAILABLE_SWITCHES = [PhilipsApi.NEW2_BEEP]
    UNAVAILABLE_SENSORS = [PhilipsApi.NEW2_GAS]
    AVAILABLE_SELECTS = [PhilipsApi.NEW2_TIMER2]
    #AVAILABLE_NUMBERS = [PhilipsApi.NEW2_TARGET_TEMP]

```

**Comment by werty1st** [comment]
I have at least the power and timer working. but the speed selection doesn't appear at all. The oscillation settings is a slider but this model can only turn it on or off. I don't know how to make it a switch.

**Comment by VSPylypenko** [comment]
When you add Philips CX3550 support in integration? When adding a device to the integration, I constantly receive a message that the model is not supported.

**Comment by EuleMitKeule** [comment]
@werty1st I tried your code, but I am getting a timeout when trying to setup the entry even though I am able to ping the fan from the home assistant instance.

**Comment by wehrmannit** [comment]
It's registering as "CX3550/01" so it should be XC3550_01, right?

**Comment by EuleMitKeule** [comment]
@werty1st 
![grafik](https://github.com/user-attachments/assets/c14d15bf-0f78-404b-bbfa-30da493f9444)
Speed selection works for me, but not oscillation.

**Comment by EuleMitKeule** [comment]
Sending `"D0320F": 23040` to the fan to enable oscillation gives a successful response, but the fan does not oscillate and the next status contains `"D0320F": 0`.

The only value that changes when enabling/disabling oscillation via the app is `D0320F`, so I am not sure what else has to be done for this to work.

**Comment by wehrmannit** [comment]
> Sending `"D0320F": 23040` to the fan to enable oscillation gives a successful response, but the fan does not oscillate and the next status contains `"D0320F": 0`.
> 
> The only value that changes when enabling/disabling oscillation via the app is `D0320F`, so I am not sure what else has to be done for this to work.
@EuleMitKeule 

Try with 17241 or 17242. Seems to be changing?

I bruteforced it

**Comment by EuleMitKeule** [comment]
@wehrmannit Neither is working for me :/

Could you share the code/commands used for bruteforcing?

**Comment by wehrmannit** [comment]
For Powershell I used:
for ($num = 17000; $num -le 50000; $num++) { Write-Output "Current num: $num"; aioairctrl.exe --host 192.168.0.33 set -I D0320F=$num }

When it started working I changed the numbers to find the right one

**Comment by EuleMitKeule** [comment]
17242 works for me, but only from the terminal, not from the integration.

**Comment by EuleMitKeule** [comment]
I found the bug, the oscillation value has to be sent as an integer, not a string. Now oscillation works! 🎉

**Comment by EuleMitKeule** [comment]
There seems to be one issue remaining: changing the oscillation from the UI does not really work yet, since the status never gets updated to reflect that the fan is currently oscillating. Therefore selecting no on the oscillation switch does not do anything.

**Comment by wehrmannit** [comment]
@EuleMitKeule can we update it twice? Once to 17242 and then to 23040?

**Comment by EuleMitKeule** [comment]
I fixed the issue by manually updating the device status after oscillation is changed.
I opened a PR #144 to merge my changes.
For this integration to really be usable I think some more work has to be done, especially fixing the issue with Home Assistant hanging on startup and the integration not being able to initialize if no command is sent via the app to the fan during startup.

**Comment by EuleMitKeule** [comment]
I started to introduce some major changes to the integration on my fork in order to optimize behaviour for the CX3550/01 fan. It's pretty stable and does not have any hanging/disconnect issues and changes to the state are reflected instantly, although there may be some minor bugs still. Maybe somebody would like to try it out.

**Comment by werty1st** [comment]
Hi @EuleMitKeule I'm using your version and just added your repo. it's working great so far.
I'm missing the Sleeptimer.

<img width="1059" alt="image" src="https://github.com/user-attachments/assets/4237e8fc-de9b-481a-b6df-8c975e5842d3">

**Comment by EuleMitKeule** [comment]
@werty1st Yup, will work on that next. Maybe you could open issues in my fork instead for things regarding that so we don't spam this repo with unrelated stuff.

**Comment by werty1st** [comment]
@EuleMitKeule i wanted to but issues seem to be disabled on your fork
<img width="713" alt="image" src="https://github.com/user-attachments/assets/e2040834-1781-4780-9738-de98dd23b46f">

**Comment by EuleMitKeule** [comment]
@werty1st Whoops, should be possible now! Thanks for letting me know.

**Comment by micky9371** [comment]
@EuleMitKeule, today I bought the CX3550/01 and was very happy to read about Your working HA integration. 
So I installed Your repo. Unfortunately I get a "Timeout, cannot connect to device" when adding the Integration and entering the IP of the fan.
Control by Air+ App works fine. Double-checked the IP address as well. Do You have any hints for me what I can check to get it working? 
Thanks a lot!
Micky

**Comment by werty1st** [comment]
@micky9371 the timeout happens for me as well. sometimes i have to try 2-3 times. Or try pressing buttons on the fan to "wake it up".

**Comment by micky9371** [comment]
@werty1st, perfect, now I was able connecting to it.
It seems I simply had to unplug the mains for some seconds. After that the configuration procedure was successfully completed.
Works like a charm for me.
Again, many thanks to @EuleMitKeule for Your great work!

**Comment by wehrmannit** [comment]
@EuleMitKeule  https://developers.home-assistant.io/blog/2024/07/19/fan-fanentityfeatures-turn-on_off - maybe something to read now

**Comment by william-niq** [comment]
Hey this is a cool thread! just got one of these and will patiently wait the support :D 

Found out that `D03130` is for the beep sound to be turned on / off incase that helps!

**Comment by EuleMitKeule** [comment]
@william-niq You can try out my fork, controlling the device already works, there only seem to be a few bugs regarding the display of the current state.

**Comment by tvarbanov** [comment]
> @william-niq You can try out my fork, controlling the device already works, there only seem to be a few bugs regarding the display of the current state.

I just got your fork and it seems that it works great. Will test it more but it seems all is working. 
In Apple Home the controls seems weird(I think it adds the modes as switches), but that's a separate thing and I guess it's not really something to do with the actual integration.

Thank you very much :)

**Comment by kongo09** [comment]
I'll take a look at this next. Thanks, @EuleMitKeule , for preparing the fork. Does it work or do you still have trouble with the states?

**Comment by EuleMitKeule** [comment]
Haven't had the time yet to take another look.

**Comment by kongo09** [comment]
> @EuleMitKeule https://developers.home-assistant.io/blog/2024/07/19/fan-fanentityfeatures-turn-on_off - maybe something to read now

This is implemented already.

**Comment by kongo09** [comment]
Can people please try v0.18.11-beta.1 which incorporates the code prepared by @EuleMitKeule

**Comment by BA2000** [comment]
Hi, i´ve testet the Version V0.18.11-beta.1, and it works for me.
The AC2889 was recognized imediatly, the CX3550/01 was found after the input of the IP and additional in the original Philips App change the speed.
:-)
Great. I will test this for the next days.

Greetings BA2000
![Screenshot 2024-10-26 195935](https://github.com/user-attachments/assets/e9de489b-7e06-42ce-91ad-aa5daa2b7b56)

**Comment by kongo09** [comment]
Great. Can you check what your MAC address is of the device, which is used for auto detection?

**Comment by BA2000** [comment]
Hi, where can i find the MAC used for auto detection?

**Comment by kongo09** [comment]
The easiest is probably to go into your Air+ app, select the device, go to Settings and then Device Information

But you can probably see this on your router as well or use a network scanner.

**Comment by BA2000** [comment]
The MAC of device#1 (AC2889) is 04:78:63:D5:A2:DF
The MAC of device#2 (CX3550) is 84:9D:C2:13:A6:D6

**Comment by kongo09** [comment]
Hm, the autorecognition is already using the MAC of your CX3550 so in theory it should work. Maybe if you wait a bit longer it detects it... not sure.

**Comment by Ka3seBr0t** [comment]
For anyone still watching this thread: the CX3550/01 turned out to be a genuinely different animal from the AC-series purifiers this project targets — it's cloud-only (AWS IoT device shadow behind Philips' air-matters/gaoda auth chain, not the local CoAP protocol these integrations speak natively).

Reverse-engineered the full auth chain and built a standalone HA integration for it: https://github.com/Ka3seBr0t/HA_Philips_Air_Plus — fan (speed/presets/oscillate), beep, and a 12h auto-off timer, all control-verified against a physical CX3550/01. Posting here since this issue is where everyone with this exact "why won't my fan show up" problem seems to end up. Not a replacement for this project's CoAP-based approach (different device class, different local vocabulary) — just the missing piece for this specific fan.
