### ISSUE TITLE
Detected blocking calls

### ISSUE THREAD

**Issue by tjorim** [kongo09/philips-airpurifier-coap#143]
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 01:27:19 (2 occurrences)
Last logged: 01:27:19

Detected blocking call to walk with args ('/config/custom_components/philips_airpurifier_coap/icons/pap',) inside the event loop by custom integration 'philips_airpurifier_coap' at custom_components/philips_airpurifier_coap/__init__.py, line 72: for dirpath, _dirnames, filenames in walk(iconpath): (offender: /config/custom_components/philips_airpurifier_coap/__init__.py, line 72: for dirpath, _dirnames, filenames in walk(iconpath):), please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#walk Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component result = await task File "/config/custom_components/philips_airpurifier_coap/__init__.py", line 72, in async_setup for dirpath, _dirnames, filenames in walk(iconpath):
Detected blocking call to scandir with args ('/config/custom_components/philips_airpurifier_coap/icons/pap',) inside the event loop by custom integration 'philips_airpurifier_coap' at custom_components/philips_airpurifier_coap/__init__.py, line 72: for dirpath, _dirnames, filenames in walk(iconpath): (offender: <frozen os>, line 366: ?), please create a bug report at https://github.com/kongo09/philips-airpurifier-coap/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#scandir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component result = await task File "/config/custom_components/philips_airpurifier_coap/__init__.py", line 72, in async_setup for dirpath, _dirnames, filenames in walk(iconpath):

**Comment by kongo09** [comment]
fixed in v0.18.8
