### ISSUE TITLE
Make speed a preset as well

### ISSUE THREAD

**Issue by kongo09** [kongo09/philips-airpurifier-coap#15]
- put speed settings into presets
- put `night` and `sleep` into speeds as lowest setting

**Comment by kongo09** [comment]
supports #13

**Comment by user897943** [comment]
@kongo09 did you see this? Looks like a better alternative than the control that betaboon wrote and looks like there is control via the Philips cloud as well as coap and encrypted coap. May be more reliable. 
https://github.com/rgerganov/py-air-control

**Comment by kongo09** [comment]
Yes, I know this. This is the basis betaboon started from. This guy basically reverse engineered the Philips protocol in the first place. Without him, we wouldn't have anything.

But I didn't look into this lately. Why don't you give it a try and see if it is more stable?

**Comment by kongo09** [comment]
v0.9.6
