### ISSUE TITLE
Stopped working, removed, upgraded HA, does not install

### ISSUE THREAD

**Issue by dmindfuse** [kongo09/philips-airpurifier-coap#150]
Hi everyone

This plugin served me very well for a little more than a year, providing features Philips couldn't come up with.
However, all good things come to an end? and so... it stopped working one day. I decided to uninstall it and try a reinstall, but this went south. I had to manually remove the customer_components folder, then remove it from HACS, tried to reinstall it, but this failed. Decided to remove the 11 associated entities 1 by 1, then removed 1 entry. It was gone now. I left it for weeks. 

Then I upgraded HA to 2024.6.2 today and gave the HACS download and attempt to install the integration another swing, but the error popping up remains the same as prior the upgrade:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

In the logs I find:

```
Logger: homeassistant.config_entries
Source: config_entries.py:2757
First occurred: 5:42:07 PM (2 occurrences)
Last logged: 5:46:51 PM

Error occurred loading flow for integration philips_airpurifier_coap: cannot import name 'StaticPathConfig' from 'homeassistant.components.http' (/usr/src/homeassistant/homeassistant/components/http/__init__.py)
```

So... where should I begin? Is this related to my installation or is it a plugin matter? Any advice is welcome... I miss my fan automatically kicking in when the air quality drops.

Thanks all
M

**Comment by kongo09** [comment]
Can you update your HA to the latest 2024.8.3 version and then share logs?

**Comment by dmindfuse** [comment]
Hello @kongo09 , your suggestion fixed the issue. I was on the :stable version. Changed it to be :latest and ended up with your suggested version, which brought back the installation wizard. I was able to control the fan, thank goodness :) So, thank you very much!

Off topic: I originally installed home assistant to toy around with it. Mainly using Homekit, but homekit feels terribly unreliable (could also just be Hue). I use Siri 95% of the time and automations. Do you by any chance use a voice solution around your place with home assistant? Does it work well? I have 3 homepods to allow me to do so with homekit.

**Comment by kongo09** [comment]
Glad to hear it is working. 

I'm using Google Assistant but it's quality is really bad. There is some build in solution in HA but I'm struggling with that.
