### ISSUE TITLE
Trying to add a new device

### ISSUE THREAD

**Issue by korneij** [kongo09/philips-airpurifier-coap#152]
Hey,

I just installed the integration via HACS & now trying to add my Philips 1000i (AC1715/11). But it's not accepting the IP of the device. Either I am not 100% sure what it's expecting as device name. Anyone can help me here?

**Comment by kongo09** [comment]
The AC1715 should work. Yes, you need to enter the IP address if the device is not automatically discovered. If the integration fails to connect, this could be a network problem. Can you please enable logging inside HA and share here?

**Comment by korneij** [comment]
The action causes two entries:
This error originated from a custom integration.

Logger: custom_components.philips_airpurifier_coap.config_flow
Source: custom_components/philips_airpurifier_coap/config_flow.py:235
integration: Philips AirPurifier (documentation, issues)
First occurred: 5:58:33 PM (8 occurrences)
Last logged: 8:19:00 PM

Failed to connect: [Errno 111] Connection refused (ECONNREFUSED, received through errqueue)
Failed to connect: No address information found for requests to 'philips-airpurifier'

###################
Logger: coap
Source: runner.py:189
First occurred: 5:59:10 PM (7 occurrences)
Last logged: 8:19:18 PM

Connection loss was not expected.

**Comment by KlaraJa** [comment]
Having the same issue here.
I thought, maybe the subversion is not supported and I wanted to start a request to add this one, but then the python tool also gave me this error:
`aiocoap.error.NetworkError: [Errno 61] Connection refused`

**Comment by kongo09** [comment]
You say the python command line tool gives the same error? In that case, you're out of luck as HA is using the same mechanism. 

Are these older devices? There have been devices that do not use encrypted CoAP but use unencrypted CoAP or HTTP. This integration doesn't support these alternative connection methods as all modern devices use encrypted CoAP. But you might want to try to following tool to figure out if you can talk to your device at all: https://github.com/rgerganov/py-air-control

**Comment by KlaraJa** [comment]
I've tried it with https://github.com/rgerganov/py-air-control
Tried plain_coap and coap I got those result:
```zsh
$ airctrl --ipaddr 192.168.178.155 --protocol plain_coap
Give up on message From None, To ('192.168.178.155', 5683), CON-39861, EMPTY-None, [] No payload
```
```zsh
$ airctrl --ipaddr 192.168.178.155 --protocol coap
Give up on message From None, To ('192.168.178.155', 5683), CON-61980, POST-dU, [Uri-Path: sys, Uri-Path: dev, Uri-Path: sync, ] 33CEF344...8 bytes
Traceback (most recent call last):
  File "/Users/[redacted]/env/bin/airctrl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/[redacted]/env/lib/python3.12/site-packages/pyairctrl/airctrl.py", line 205, in main
    c = CoAPCli(device["ip"], debug=args.debug)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[redacted]/env/lib/python3.12/site-packages/pyairctrl/airctrl.py", line 99, in __init__
    super().__init__(CoAPAirClient(host, port, debug))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[redacted]/env/lib/python3.12/site-packages/pyairctrl/coap_client.py", line 82, in __init__
    self._sync()
  File "/Users/[redacted]/env/lib/python3.12/site-packages/pyairctrl/coap_client.py", line 100, in _sync
    raise Exception("sync timeout")
Exception: sync timeout
```

**Comment by kongo09** [comment]
I this case, you're out of luck. Sorry. I cannot help you.

**Comment by RonnieB7** [comment]
It looks a lot like these are actually the newest devices from Philips. I've got a brand new AC1715, and get the same errors.
Are they moving away from COAP maybe?

Btw, it looks like they're using a Bluetooth connection first to connect to your phone to establish the WiFi connection which also means the device is not setting up an initial "PHILIPS Setup" WiFi SSID anymore. This means you cannot connect it to the Air Matters app anymore and can only connect it to their new Air+ app (for as far as I know).
I guess the only way with the newest devices is to connect over cloud.
Could anyone maybe help me where I should look for a cloud integration? I cannot find one in HACS.

**Comment by korneij** [comment]
yeah.. thinks so too.. but sadly this thread was closed w/o a provided solution. Haven't found any alternative solution yet

**Comment by kongo09** [comment]
There is none as far as I know. I reached out to Philips several times to ask for API access to use the cloud service. They never replied at all. Apparently, they had some agreement with IFTTT in the past, but that got cancelled and access removed. Now Alexa is the only external integration.

It feels like Philips is moving backwards. Too sad.
