### ISSUE TITLE
New Device AC0850/31

### ISSUE THREAD

**Issue by hen-hick** [kongo09/philips-airpurifier-coap#154]
See raw data for the Air Purifier AC0850/31 from the 800i series.

It is already recognized by the HA integration. The sensors and diagnostics show the correct values, but the control doesn't work and just shows "off", regardless of the actual state. Also selecting the presets does not have any effects. I suspect this is due to the fact that this is a newer model of the AC0850 so has some slightly different firmware.

The device has 4 states: sleep, turbo, auto, off

Sleep

`{"D01102": 5, "D01S03": "Office", "D01S04": "Pluto", "D01S05": "AC0850/31", "D01107": 0, "D01108": 3, "D01109": 1, "D0110A": 4, "D0110B": 1, "D0110C": 18, "D0110F": 3, "D01S12": "0.1.3", "D01213": 0, "ProductId": "89be7eb8cc3e11eca3f10217247a73aa", "DeviceId": "ffaff4f078fe11ef92886f6aaa29d532", "Runtime": 75840014, "rssi": -44, "wifilog": false, "free_memory": 185760, "WifiVersion": "AWS_Philips_AIR_Combo@1.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D0310A": 2, "D0310C": 17, "D0310D": 1, "D03120": 1, "D03221": 2, "D0312A": 1, "D0312B": 1, "D0312C": 4, "D03134": 1, "D03240": 0, "D05408": 4800, "D0540E": 4778}`

Turbo

`{"D01102": 5, "D01S03": "Office", "D01S04": "Pluto", "D01S05": "AC0850/31", "D01107": 0, "D01108": 3, "D01109": 1, "D0110A": 4, "D0110B": 1, "D0110C": 18, "D0110F": 3, "D01S12": "0.1.3", "D01213": 0, "ProductId": "89be7eb8cc3e11eca3f10217247a73aa", "DeviceId": "ffaff4f078fe11ef92886f6aaa29d532", "Runtime": 75803662, "rssi": -44, "wifilog": false, "free_memory": 185760, "WifiVersion": "AWS_Philips_AIR_Combo@1.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D0310A": 2, "D0310C": 18, "D0310D": 18, "D03120": 1, "D03221": 2, "D0312A": 1, "D0312B": 1, "D0312C": 4, "D03134": 1, "D03240": 0, "D05408": 4800, "D0540E": 4778}`

Auto

`{"D01102": 5, "D01S03": "Office", "D01S04": "Pluto", "D01S05": "AC0850/31", "D01107": 0, "D01108": 3, "D01109": 1, "D0110A": 4, "D0110B": 1, "D0110C": 18, "D0110F": 3, "D01S12": "0.1.3", "D01213": 0, "ProductId": "89be7eb8cc3e11eca3f10217247a73aa", "DeviceId": "ffaff4f078fe11ef92886f6aaa29d532", "Runtime": 75581806, "rssi": -40, "wifilog": false, "free_memory": 186224, "WifiVersion": "AWS_Philips_AIR_Combo@1.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D0310A": 2, "D0310C": 0, "D0310D": 1, "D03120": 1, "D03221": 1, "D0312A": 1, "D0312B": 1, "D0312C": 4, "D03134": 1, "D03240": 0, "D05408": 4800, "D0540E": 4778}`

Off

`{"D01102": 5, "D01S03": "Office", "D01S04": "Pluto", "D01S05": "AC0850/31", "D01107": 0, "D01108": 3, "D01109": 1, "D0110A": 4, "D0110B": 1, "D0110C": 18, "D0110F": 3, "D01S12": "0.1.3", "D01213": 0, "ProductId": "89be7eb8cc3e11eca3f10217247a73aa", "DeviceId": "ffaff4f078fe11ef92886f6aaa29d532", "Runtime": 76123850, "rssi": -40, "wifilog": false, "free_memory": 185760, "WifiVersion": "AWS_Philips_AIR_Combo@1.2", "StatusType": "status", "ConnectType": "Online", "D03102": 0, "D0310A": 2, "D0310C": 0, "D0310D": 0, "D03120": 1, "D03221": 1, "D0312A": 1, "D0312B": 1, "D0312C": 4, "D03134": 1, "D03240": 0, "D05408": 4800, "D0540E": 4778}`

**Comment by kongo09** [comment]
Have you tried the advice from #139 ? Maybe your model behaves the same?

**Comment by hen-hick** [comment]
I've tried the forked project by Deviant with no luck and the same issue so I'm not sure if it is the same issue.

**Comment by hen-hick** [comment]
Had a bit more of a look and its the same issue as #139 as the AC0850/31 uses the new2 (3rd gen) API rather than the second. deviants fork did not work as it specifically looks for AC0850/11  model ID. I added extra bits for the AC0850/31 just copying deviants code and changing the 11 to 31 and that seems to have worked.

**Comment by kongo09** [comment]
Let's keep this open, as I still need to pull this into the main code base

**Comment by hen-hick** [comment]
#155 pull request here to add the AC0850/31 as new device with 3rd gen API. Also added bonus of mode icons

**Comment by kongo09** [comment]
New pre-release should support this model. Please test: v0.18.10-beta.2

**Comment by Tortur3** [comment]
Some feedback on this: Got myself an AC0850/11

The 18.10-beta.2 is working fine!

While beta.3 drops errors and 18.09 does not work with fan settings as described before.

**Comment by kongo09** [comment]
@Tortur3  Can you please enable debug logging and post the errors here so that I can take a look?

**Comment by kongo09** [comment]
please try v0.18.10-beta.4

**Comment by Tortur3** [comment]
As you already released beta.6 now I tried this one and it seems to work fine!

**Comment by kongo09** [comment]
One question: does the device have a Gas sensor?

**Comment by kongo09** [comment]
I've just done a new release and everything should be fine. If not, please reopen.
