### ISSUE TITLE
Integration not working after update to HA 2024.10.1

### ISSUE THREAD

**Issue by timou07** [kongo09/philips-airpurifier-coap#156]
Hi,

I installed the Integration on 2024.9.3 a few days ago and so far I'm very happy with it!
Today I updated to 2024.10.1 and now the integration is not starting anymore. I got a dependeny error for aioairctrl, so I removed the integration, redownloaded it from HACS and tried to add it again, but it fails with the following error message:

_Unable to install package aioairctrl==0.2.5: error: error sending request for url (https://wheels.home-assistant.io/musllinux-index/aioairctrl/) Caused by: client error (SendRequest) Caused by: connection error Caused by: received fatal alert: BadRecordMac_

After going back to 2024.9.3 the installation works again without any issues.

Small additional thing: You mention IFTTT being a more stable integration, but the link you provide forwards to the home page of IFTTT, the sub page seems to be gone. The only thing I found was a Reddit post claiming that Philips support said the IFTTT support is discontinued: https://www.reddit.com/r/ifttt/comments/1adqnak/comment/kwjkodr/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Thanks and best regards
Timo

**Comment by kongo09** [comment]
Hm, not sure what's going on. 2024.10.1 is working on all my devices. Let's see if others report a problem as well.

Thanks for pointing out the change on IFTTT.

**Comment by timou07** [comment]
Oh that's interesting. My HA is running as OVA-Image on a ESX host, do you have something similar or could this maybe part of it?

I just tested again with removing the integration, then updating HA and reinstalling the integration, but facing the same issue. From the logs I found this:

_Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 135, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 114, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 112, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1312, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1499, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2964, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2941, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 575, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 269, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 307, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for philips_airpurifier_coap not found: ['aioairctrl==0.2.5']._

Will try some more things and report back when I find something.

**Comment by kongo09** [comment]
I run it on a Raspi 4. Nothing special, but also no problems.

**Comment by kongo09** [comment]
I've just tried a fresh install on a Windows laptop in a Docker devcontainer. Runs the integration without a problem.

**Comment by pthoelken** [comment]
For me it's not working as well. 

`2024-10-07 14:19:08.719 WARNING (MainThread) [custom_components.philips_airpurifier_coap.config_flow] Timeout, host 10.1.46.84 doesn't answer, aborting`

**Comment by kongo09** [comment]
If you get a timeout, this doesn't feel like a HA problem. Have you unplugged your device and power cycled? Did you try to access it via the Air+ app while HA boots up? This could be the normal Philips connectivity problem that plagues most of us.

**Comment by pthoelken** [comment]
> If you get a timeout, this doesn't feel like a HA problem. Have you unplugged your device and power cycled? Did you try to access it via the Air+ app while HA boots up? This could be the normal Philips connectivity problem that plagues most of us.

During adding the device to HA, I can browse to the device by the Phillips Air+ app and can get some information about the status and so on. So like this, the device is online.

**Comment by kongo09** [comment]
And if you downgrade to HA 2024.9 it starts working?

**Comment by pthoelken** [comment]
I've do a downgrade to 2024.9.3 and the timeout error still exists.

**Comment by kongo09** [comment]
Ok, that means you do not have the problem described in this issue. It sounds like you might have the general connectivity problem that plagues many of us. Not much I can do about that. I'm really sorry.

**Comment by HuisAutomatisering** [comment]
Works for me. but see increased coap-error disconnections. I know they are there, but it seems to be increased in 2024.10 Don't know why.

**Comment by kongo09** [comment]
Not sure what's going on here, but I'll close the issue as I don't think I can help and the integration seems to work.

**Comment by timou07** [comment]
Just short addition in case anyone has this issue, I managed to install a clean HA instance via OVA image on my ESX server and there I get the same issue aswell, so it seems to be connected to the OVA image.
Didn't have time to run any further testing, but if I find some time I will try other installation methods of HA, probably they will work.
