### ISSUE TITLE
Request support for AC0950

### ISSUE THREAD

**Issue by lo0k0502** [kongo09/philips-airpurifier-coap#158]
According to Air+ app, this model has following functionalities:

- Modes
   - Auto
   - Sleep
   - Medium
   - Turbo
- Controls
   - Brightness
   - Timer
   - Scheduler
   - Child Lock
   - Beep Sound
- Sensors
   - Air Quality
      - PM2.5
      - IAI
   - Filter
      - Clean
      - Replace

I'm currently providing the status data of 4 modes here, if there are other information needed please let me know.

### Auto

```json
{
  "D01102": 0,
  "D01S03": "\u81e5\u5ba4",
  "D01S04": "Unicorn",
  "D01S05": "AC0950/80",
  "D01107": 0,
  "D01108": 3,
  "D01109": 3,
  "D0110A": 0,
  "D0110B": 0,
  "D0110C": 18,
  "D01S0D": "688001001382",
  "D0110F": 3,
  "D01S12": "0.3.3",
  "D01213": 0,
  "ProductId": "16967a35facd11ee9c160217247a73aa",
  "DeviceId": "807717f0855811ef99a469a5a8527d50",
  "otacheck": false,
  "Runtime": 4303584,
  "rssi": -27,
  "wifilog": false,
  "blelog": false,
  "free_memory": 153984,
  "WifiVersion": "AWS_Philips_AIR_Combo@3.0",
  "StatusType": "status",
  "ConnectType": "Online",
  "D03102": 1,
  "D03103": 0,
  "D03104": 123,
  "D03105": 123,
  "D0310A": 2,
  "D0310C": 0,
  "D0310D": 1,
  "D03110": 0,
  "D03211": 0,
  "D03120": 2,
  "D03221": 6,
  "D0312A": 1,
  "D0312B": 1,
  "D0312C": 4,
  "D03130": 100,
  "D03134": 0,
  "D03136": 0,
  "D03240": 0,
  "aqit_ext": 0,
  "D05207": 720,
  "D05408": 9600,
  "D0520D": 716,
  "D0540E": 9596
}
```

### Sleep

```json
{
  "D01102": 0,
  "D01S03": "\u81e5\u5ba4",
  "D01S04": "Unicorn",
  "D01S05": "AC0950/80",
  "D01107": 0,
  "D01108": 3,
  "D01109": 3,
  "D0110A": 0,
  "D0110B": 0,
  "D0110C": 18,
  "D01S0D": "688001001382",
  "D0110F": 3,
  "D01S12": "0.3.3",
  "D01213": 0,
  "ProductId": "16967a35facd11ee9c160217247a73aa",
  "DeviceId": "807717f0855811ef99a469a5a8527d50",
  "otacheck": false,
  "Runtime": 4330162,
  "rssi": -28,
  "wifilog": false,
  "blelog": false,
  "free_memory": 154144,
  "WifiVersion": "AWS_Philips_AIR_Combo@3.0",
  "StatusType": "status",
  "ConnectType": "Online",
  "D03102": 1,
  "D03103": 0,
  "D03104": 0,
  "D03105": 0,
  "D0310A": 2,
  "D0310C": 17,
  "D0310D": 1,
  "D03110": 0,
  "D03211": 0,
  "D03120": 1,
  "D03221": 1,
  "D0312A": 1,
  "D0312B": 1,
  "D0312C": 4,
  "D03130": 100,
  "D03134": 0,
  "D03136": 0,
  "D03240": 0,
  "aqit_ext": 0,
  "D05207": 720,
  "D05408": 9600,
  "D0520D": 716,
  "D0540E": 9596
}
```

### Medium

```json
{
  "D01102": 0,
  "D01S03": "\u81e5\u5ba4",
  "D01S04": "Unicorn",
  "D01S05": "AC0950/80",
  "D01107": 0,
  "D01108": 3,
  "D01109": 3,
  "D0110A": 0,
  "D0110B": 0,
  "D0110C": 18,
  "D01S0D": "688001001382",
  "D0110F": 3,
  "D01S12": "0.3.3",
  "D01213": 0,
  "ProductId": "16967a35facd11ee9c160217247a73aa",
  "DeviceId": "807717f0855811ef99a469a5a8527d50",
  "otacheck": false,
  "Runtime": 4384052,
  "rssi": -26,
  "wifilog": false,
  "blelog": false,
  "free_memory": 154144,
  "WifiVersion": "AWS_Philips_AIR_Combo@3.0",
  "StatusType": "status",
  "ConnectType": "Online",
  "D03102": 1,
  "D03103": 0,
  "D03104": 123,
  "D03105": 123,
  "D0310A": 2,
  "D0310C": 19,
  "D0310D": 2,
  "D03110": 0,
  "D03211": 0,
  "D03120": 2,
  "D03221": 5,
  "D0312A": 1,
  "D0312B": 1,
  "D0312C": 4,
  "D03130": 100,
  "D03134": 0,
  "D03136": 0,
  "D03240": 0,
  "aqit_ext": 0,
  "D05207": 720,
  "D05408": 9600,
  "D0520D": 716,
  "D0540E": 9596
}
```

### Turbo

```json
{
  "D01102": 0,
  "D01S03": "\u81e5\u5ba4",
  "D01S04": "Unicorn",
  "D01S05": "AC0950/80",
  "D01107": 0,
  "D01108": 3,
  "D01109": 3,
  "D0110A": 0,
  "D0110B": 0,
  "D0110C": 18,
  "D01S0D": "688001001382",
  "D0110F": 3,
  "D01S12": "0.3.3",
  "D01213": 0,
  "ProductId": "16967a35facd11ee9c160217247a73aa",
  "DeviceId": "807717f0855811ef99a469a5a8527d50",
  "otacheck": false,
  "Runtime": 4444114,
  "rssi": -27,
  "wifilog": false,
  "blelog": false,
  "free_memory": 153952,
  "WifiVersion": "AWS_Philips_AIR_Combo@3.0",
  "StatusType": "status",
  "ConnectType": "Online",
  "D03102": 1,
  "D03103": 0,
  "D03104": 123,
  "D03105": 123,
  "D0310A": 2,
  "D0310C": 18,
  "D0310D": 18,
  "D03110": 0,
  "D03211": 0,
  "D03120": 1,
  "D03221": 3,
  "D0312A": 1,
  "D0312B": 1,
  "D0312C": 4,
  "D03130": 100,
  "D03134": 0,
  "D03136": 0,
  "D03240": 0,
  "aqit_ext": 0,
  "D05207": 720,
  "D05408": 9600,
  "D0520D": 716,
  "D0540E": 9596
}
```

**Comment by kongo09** [comment]
Thanks for the data, that should help integrating the device

**Comment by kongo09** [comment]
I've just published a beta. Can you please try if your device works? If not, please enable debug logging and post the errors here.

**Comment by lo0k0502** [comment]
Thanks for the work! I've just tried `v0.18.10-beta.5` and have identified several issues.

## Missing features

1. **Modes**: This is what I mentioned in the first comment, it would be the top priority for me so if this can be supported I would really appreciate it.
2. **Brightness control**: This would be a select option with three modes: Bright, Low, and Off. It would control the brightness of the panel on the physical device. While not crucial, it would be a nice addition if available.
3. **Scheduler**: This feature would allow setting a schedule to power on or off at specific times. I understand this might be complex to implement, so it can be considered an optional feature.

<img src="https://github.com/user-attachments/assets/22402a80-297c-4fcc-a503-4bad43f2da03" width="200" />
<img src="https://github.com/user-attachments/assets/a7d91222-09c7-4e64-b462-b6b7a85380f8" width="200" />

## Bugs

### Switch

The switches are behaving erratically. For instance, when I press power off, the UI reverts to the previous state after a few seconds, even though the machine's state correctly changes to off. Due to this UI reversion, turning it back on is challenging unless I quickly press the switch before it reverts. This seems to be a data synchronization issue.

Logs during testing:
[test-log.txt](https://github.com/user-attachments/files/17366102/test-log.txt)

Video demonstration:

https://github.com/user-attachments/assets/3d0477fb-ab96-4bc4-9f3e-a2b6c197cb59

### Select

I've tested the Timer feature, since I don't know what Preferred Index feature is.
I can set a 1-12 hours timer, and the Air+ app recognizes it's working. However, after refreshing the page, it still displays "Off," even though the timer is correctly set on Air+. Additionally, when I try to turn off a set timer, selecting "Off" doesn't work; the Timer in the Air+ app doesn't deactivate.

Logs during testing:
[test-log2.txt](https://github.com/user-attachments/files/17366227/test-log2.txt)

Video demonstration:

https://github.com/user-attachments/assets/c89e8a3c-cd8f-4c34-bf81-dfb30f36870b

## Additional Info

I've also recorded a segment of logs when the machine is on in Auto mode without any user controls. I hope this information is helpful.
[idle-log.txt](https://github.com/user-attachments/files/17366268/idle-log.txt)

**Comment by kongo09** [comment]
Thanks so much for all the data, especially the videos as they help a lot to understand what you actually see. I guess I need some serious time to look deeper into this...

**Comment by kongo09** [comment]
Can you please explain again what is missing with the modes?

**Comment by kongo09** [comment]
Hm, I looked at the logs but I don't really understand what's going on. It seems the integration is sending the command and as you say your device is also receiving it and reacting. The way the integration behaves is, that there is no "local echo" so the switch will only stay in its new state if the device also reports the new value. If the integration cannot detect the new value, it assumes the old value is still valid and flips the switch back to where it was.

So what happens if you use the Air+ app to change any of these switches? If you turn it off in the app, does the integration detect that and follow and also shows switched off?

**Comment by kongo09** [comment]
By the way, there is another user with an AC0951 which seems to have the same codes. The discussion is here: https://github.com/kongo09/philips-airpurifier-coap/issues/163

I've copied the work from the AC0950. Let's see if that device hits the same problems - we would then have another pair of eyes.

**Comment by kongo09** [comment]
I tried to fix the lights. Please try v0.18.10-beta.8

**Comment by lo0k0502** [comment]
Sorry for the delay, I've been a bit busy these days 🫠

I've tried v0.18.10-beta.8, and I can say it's definitely a lot better!

First, let me address this:

> Can you please explain again what is missing with the modes?

Sure! The entire feature seems to be missing, as I can't find any related control on the integration device page, nor any related entities. Please see video and image below:

https://github.com/user-attachments/assets/895fe1c7-c953-4e58-84b1-38d143ba6a11

![image](https://github.com/user-attachments/assets/d7827081-72b8-4216-a498-0d4fb788693c)

Aside from that...

The backlight control is working, although in my case, there's an additional 'Low' option, which makes it a Select. While it's not very crucial for me, I'll leave these status data just in case. (Currently, it seems like both Brightness and Low are treated as 'on' in HA, while 'Off' is... well, off.)
[brightness-bright.json](https://github.com/user-attachments/files/17523305/brightness-bright.json)
[brightness-low.json](https://github.com/user-attachments/files/17523307/brightness-low.json)
[brightness-off.json](https://github.com/user-attachments/files/17523308/brightness-off.json)

The switches are working well without any unexpected behavior, and the selects are also functioning smoothly. Really appreciate it!

Thanks again for your hard work on this. If there's anything else I can help, feel free to ask!

**Comment by kongo09** [comment]
You will find the selection for the modes here:

![image](https://github.com/user-attachments/assets/5cf357e2-6ec7-419c-97a3-b7aa6104416c)

**Comment by kongo09** [comment]
So the backlight medium setting is the only thing missing? But you can select it, it just doesn't work?

**Comment by lo0k0502** [comment]
> So what happens if you use the Air+ app to change any of these switches? If you turn it off in the app, does the integration detect that and follow and also shows switched off?

Currently, it seems to sync properly in both directions. Sometimes, the state can get a bit confused if I switch controls too quickly between HA and Air+, but under normal use, it works just fine. 

Since this issue doesn't bother me too much right now, I’m not too concerned about it. But if you need more information or want me to test further, I’d be happy to help!

**Comment by kongo09** [comment]
If generally it works, I'd leave it as is. There could be problems like network latency and what not interfering with the experience. That's outside our control here anyhow. Important is, that the settings trigger the right actions in principle.

**Comment by lo0k0502** [comment]
I'm a little confused for the mode selection ui, I can't find anything similar in HA, is that HA or Air+?
If it's Air+, it's a bit different in my case.

![Screenshot_20241025_224909_Air+](https://github.com/user-attachments/assets/e92e4cca-3570-4d7b-8136-f1da79979067)

**Comment by lo0k0502** [comment]
> So the backlight medium setting is the only thing missing? But you can select it, it just doesn't work?

I can use this switch to toggle on and off in HA

![image](https://github.com/user-attachments/assets/2d388d24-6a4f-4032-85a3-98dde02157ab)

And select between three options in Air+

![Screenshot_20241025_224915_Air+](https://github.com/user-attachments/assets/a07aa3ed-504b-46c0-83cd-9cd4c7eb3dec)

This feature is working and syncing properly both ways, just have two ways to control, like I said 'Brightness' and 'Low' in Air+ is 'On' in HA.

**Comment by lo0k0502** [comment]
> If generally it works, I'd leave it as is. There could be problems like network latency and what not interfering with the experience.

That just reminds me that I need to check my home network
Been noticing some occasional delays recently...

**Comment by kongo09** [comment]
For both, the light and the fan entity, you need to click on the entity to see the control view. There you can see the modes (as shown on my screenshot above) and a slider for dimming the light (which should jump to the middle as there is no proper dimming)

**Comment by lo0k0502** [comment]
> For both, the light and the fan entity, you need to click on the entity to see the control view. There you can see the modes (as shown on my screenshot above) and a slider for dimming the light (which should jump to the middle as there is no proper dimming)

I see..., my bad.
I'm actually new to HA, so I really didn't know that. It seems that this solves all my remaining issues.
Really appreciate all the hard work, patience, quick communications, and helpful instructions!

**Comment by kongo09** [comment]
my pleasure. If you like it, [you can get me a coffee](https://buymeacoffee.com/kongo09)
