### ISSUE TITLE
Request for AC0850/11

### ISSUE THREAD

**Issue by spreefloh** [kongo09/philips-airpurifier-coap#159]
Sorry. I missed the fact that there is already a request for this.

According to Air+ app, this model has following functionalities:

**Modes**
- Auto
- Sleep
- Turbo

**Controls**
- On/Off
- Scheduler

**Air** Quality
- PM2.5 (1µg/m²)
- IAI (1/12)

**Filter**
- Filter Status in % (99%)

### Raw-Data:
**Silent:**
{"D01102": 5, "D01S03": "Schlafzimmer", "D01S04": "Pluto", "D01S05": "AC0850/11", "D01107": 0, "D01108": 3, "D01109": 1, "D0110A": 0, "D0110B": 5, "D0110C": 18, "D0110F": 3, "D01S12": "0.1.3", "D01213": 0, "ProductId": "6cfff702cc3e11eca3f10217247a73aa", "DeviceId": "86a4e980871311efa6131ff07e46da6e", "Runtime": 14657300, "rssi": -54, "wifilog": false, "free_memory": 184000, "WifiVersion": "AWS_Philips_AIR_Combo@1.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D0310A": 2, "D0310C": 17, "D0310D": 1, "D03120": 1, "D03221": 1, "D0312A": 1, "D0312B": 1, "D0312C": 4, "D03134": 1, "D03240": 0, "D05408": 4800, "D0540E": 4796}

**Auto:**
{"D01102": 5, "D01S03": "Schlafzimmer", "D01S04": "Pluto", "D01S05": "AC0850/11", "D01107": 0, "D01108": 3, "D01109": 1, "D0110A": 0, "D0110B": 5, "D0110C": 18, "D0110F": 3, "D01S12": "0.1.3", "D01213": 0, "ProductId": "6cfff702cc3e11eca3f10217247a73aa", "DeviceId": "86a4e980871311efa6131ff07e46da6e", "Runtime": 14156448, "rssi": -55, "wifilog": false, "free_memory": 182736, "WifiVersion": "AWS_Philips_AIR_Combo@1.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D0310A": 2, "D0310C": 0, "D0310D": 1, "D03120": 1, "D03221": 1, "D0312A": 1, "D0312B": 1, "D0312C": 4, "D03134": 1, "D03240": 0, "D05408": 4800, "D0540E": 4797}

**Turbo:**
{"D01102": 5, "D01S03": "Schlafzimmer", "D01S04": "Pluto", "D01S05": "AC0850/11", "D01107": 0, "D01108": 3, "D01109": 1, "D0110A": 0, "D0110B": 5, "D0110C": 18, "D0110F": 3, "D01S12": "0.1.3", "D01213": 0, "ProductId": "6cfff702cc3e11eca3f10217247a73aa", "DeviceId": "86a4e980871311efa6131ff07e46da6e", "Runtime": 14557652, "rssi": -53, "wifilog": false, "free_memory": 177456, "WifiVersion": "AWS_Philips_AIR_Combo@1.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D0310A": 2, "D0310C": 18, "D0310D": 18, "D03120": 1, "D03221": 1, "D0312A": 1, "D0312B": 1, "D0312C": 4, "D03134": 1, "D03240": 0, "D05408": 4800, "D0540E": 4796}

**Off:**
{"D01102": 5, "D01S03": "Schlafzimmer", "D01S04": "Pluto", "D01S05": "AC0850/11", "D01107": 0, "D01108": 3, "D01109": 1, "D0110A": 0, "D0110B": 5, "D0110C": 18, "D0110F": 3, "D01S12": "0.1.3", "D01213": 0, "ProductId": "6cfff702cc3e11eca3f10217247a73aa", "DeviceId": "86a4e980871311efa6131ff07e46da6e", "Runtime": 14826364, "rssi": -53, "wifilog": false, "free_memory": 184752, "WifiVersion": "AWS_Philips_AIR_Combo@1.2", "StatusType": "status", "ConnectType": "Online", "D03102": 0, "D0310A": 2, "D0310C": 0, "D0310D": 0, "D03120": 2, "D03221": 5, "D0312A": 1, "D0312B": 1, "D0312C": 4, "D03134": 1, "D03240": 0, "D05408": 4800, "D0540E": 4792}

**Comment by kongo09** [comment]
Have you tried the beta, does it work for you?
