### ISSUE TITLE
Error on intergration

### ISSUE THREAD

**Issue by KeyboardZombie** [kongo09/philips-airpurifier-coap#164]
"Error
Config flow could not be loaded: {"message":"Invalid handler specified"}" 

every time I try to install this addon, I just spent £100 because a reddit post said the series 5000 worked in home assistant. this is extremely disappointing.

**Comment by KeyboardZombie** [comment]
After reading around a bit I got it working - had to install v0.17-amfcx-beta.19, no idea why,

**Comment by lordz0mbies** [comment]
now this update is gone and the other updates say "device already configured"

**Comment by lordz0mbies** [comment]
device disconnected, this version disapeared from selection and none of the newer versions work. absolute nightmare of an addon.

**Comment by kongo09** [comment]
Which device do you have?

**Comment by KeyboardZombie** [comment]
CX5120, and its working currently but I feel like i have to reconnect it every day.

**Comment by kongo09** [comment]
Great to hear that it is working. The devices often have connectivity problems. It's not entirely clear why that is. It can be the network, but I suspect it is the individual devices. Sometimes it helps to power cycle them. Sometimes it helps to connect via Air+ and then it also connects via Home Assistant. I cannot do anything about that.

**Comment by filibard** [comment]
Hi cannot use integration due to messagge Config flow could not be loaded: {"message":"Invalid handler specified"}

This is Log Message 

Logger: homeassistant.config_entries
Source: config_entries.py:2945
First occurred: 10:46:39 AM (4 occurrences)
Last logged: 10:57:27 AM

Error occurred loading flow for integration philips_airpurifier_coap: No module named 'homeassistant.helpers.service_info.dhcp'

Home Assistant

Core 2024.10.1
Frontend 20241002.2

**Comment by kongo09** [comment]
> Hi cannot use integration due to messagge Config flow could not be loaded: {"message":"Invalid handler specified"}
> 
> This is Log Message
> 
> Logger: homeassistant.config_entries Source: config_entries.py:2945 First occurred: 10:46:39 AM (4 occurrences) Last logged: 10:57:27 AM
> 
> Error occurred loading flow for integration philips_airpurifier_coap: No module named 'homeassistant.helpers.service_info.dhcp'
> 
> Home Assistant
> 
> Core 2024.10.1 Frontend 20241002.2

You need to open a new issue with full logs and the version number of the integration if you would like me to investigate this. This issue here is closed.

**Comment by KeyboardZombie** [comment]
> After reading around a bit I got it working - had to install v0.17-amfcx-beta.19, no idea why,

wish i could go back to 0.17. none of the new versions work with this heater. 

*edit* i'm an idiot, my new router was forcing it onto a 5.0 network and i had to force it onto a 2.4

**Comment by kongo09** [comment]
So can you confirm that the latest version is working for you?
