### ISSUE TITLE
Preferred index setting for AC2729 not working

### ISSUE THREAD

**Issue by kongo09** [kongo09/philips-airpurifier-coap#166]
Setting the preferred index has no effect and HA doesn't follow the changes of Air+

This used to work in the past.

**Comment by THETCR** [comment]
This also applies to the AC4236.
Preferred index is always empty. Setting it doesn't change anything on the actual device and it will referred back to an empty value in the front-end.

**Comment by kongo09** [comment]
It seems that either Python or the device got more picky about integers vs. numbers as strings. It's fixed in the next update.
