### ISSUE TITLE
AC4236: Incorrect value 'None' used for Volatile Organic Compounds.

### ISSUE THREAD

**Issue by THETCR** [kongo09/philips-airpurifier-coap#170]
As reported in Home Assistant:

`Entity sensor.ac4236_total_volatile_organic_compounds (<class 'custom_components.philips_airpurifier_coap.sensor.PhilipsSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('volatile_organic_compounds') it is using; expected one of ['µg/m³'];`

**Comment by kongo09** [comment]
Thanks, I'll stick it into the next update

**Comment by kongo09** [comment]
duplicate of #126

**Comment by THETCR** [comment]
@kongo09 can you make a new prerelease version? Then I can install it and hopefully both issues will be resolved.

**Comment by kongo09** [comment]
I'll do a proper one this week
