### ISSUE TITLE
Unable to connect - AC1715/70

### ISSUE THREAD

**Issue by ajclark122** [kongo09/philips-airpurifier-coap#173]
Integration is unable to connect to my new air purifier. I have integration to AC3033 working perfectly, but model AC1715/70 errors. 

2024-10-30 09:30:50.695 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.config_flow] trying to configure host: 192.168.0.119
2024-10-30 09:30:50.706 WARNING (MainThread) [custom_components.philips_airpurifier_coap.config_flow] Failed to connect: [Errno 111] Connection refused (ECONNREFUSED, received through errqueue)

**Comment by MuadDib007** [comment]
AC1715/10 has the same issue.
AC4236/14 working fine.

Addon version 0.18.10 in use.

Philips wifi firmware 1.6.4
Philips device firmware 0.0.9

**Comment by kongo09** [comment]
Can you connect from the command line with `aioairctrl` as described in the README?

**Comment by ajclark122** [comment]
Thank you
Sorry - I’m running Home Assistant Green so unable to run command line.

**Comment by Invisi** [comment]
```
❯ aioairctrl -H 10.0.0.228 -D -P 5683 status --json
DEBUG:aioairctrl.coap.client:syncing
DEBUG:coap:Sending request - Token: c8f3, Remote: <UDP6EndpointAddress 10.0.0.228>
DEBUG:coap:Sending message <aiocoap.Message at 0x7f8c980fd4d0: NON POST (MID 45367, token c8f3) remote <UDP6EndpointAddress 10.0.0.228>, 1 option(s), 8 byte(s) payload>
DEBUG:coap:Socket error recevied, details: SockExtendedErr(ee_errno=111, ee_origin=2, ee_type=3, ee_code=3, ee_pad=0, ee_info=0, ee_data=0)
DEBUG:coap:Incoming error [Errno 111] Connection refused (ECONNREFUSED, received through errqueue) from <UDP6EndpointAddress 10.0.0.228 (locally 172.20.203.168%eth0)>
ConnectionRefusedError: [Errno 111] Connection refused (ECONNREFUSED, received through errqueue)
```

From what I can tell (via nmap), nothing is listening on 5683/udp. Both my AC1715 are on the firmwares mentioned above.
They do still report (via mDNS) that they're supposedly running a web service on `:80`, but that seems to be incorrect.

```
PTR _http._tcp.local., PTR PHILIPS_AC1715_1_XXXX._http._tcp.local., (Cache flush) SRV PHILIPS_AC1715_1_XXXX.local.:80 0 0, (Cache flush) TXT "Device Type=Domestic Appliance", (Cache flush) A 10.0.0.228 (262)
```

**Comment by kongo09** [comment]
In that case we're stuck and aI cannot do anything, sorry

**Comment by ajclark122** [comment]
Thank you for looking at this. Pity there’s no easy fix. :-(

Should the 1715 then be removed from the supported models list? Or at least a comment added to it that is problematic for some users? No one’s fault, just bad luck, but I unfortunately bought this model because it was on the supported models list. 

Many many thanks.

**Comment by kongo09** [comment]
There is a clear word of caution at the top of the readme. It just differs from device to device and I wouldn't be surprised if you return your model and get another one, it might start working.

**Comment by Paul1865** [comment]
> ```
> ❯ aioairctrl -H 10.0.0.228 -D -P 5683 status --json
> DEBUG:aioairctrl.coap.client:syncing
> DEBUG:coap:Sending request - Token: c8f3, Remote: <UDP6EndpointAddress 10.0.0.228>
> DEBUG:coap:Sending message <aiocoap.Message at 0x7f8c980fd4d0: NON POST (MID 45367, token c8f3) remote <UDP6EndpointAddress 10.0.0.228>, 1 option(s), 8 byte(s) payload>
> DEBUG:coap:Socket error recevied, details: SockExtendedErr(ee_errno=111, ee_origin=2, ee_type=3, ee_code=3, ee_pad=0, ee_info=0, ee_data=0)
> DEBUG:coap:Incoming error [Errno 111] Connection refused (ECONNREFUSED, received through errqueue) from <UDP6EndpointAddress 10.0.0.228 (locally 172.20.203.168%eth0)>
> ConnectionRefusedError: [Errno 111] Connection refused (ECONNREFUSED, received through errqueue)
> ```
> 
> From what I can tell (via nmap), nothing is listening on 5683/udp. Both my AC1715 are on the firmwares mentioned above. They do still report (via mDNS) that they're supposedly running a web service on `:80`, but that seems to be incorrect.
> 
> ```
> PTR _http._tcp.local., PTR PHILIPS_AC1715_1_XXXX._http._tcp.local., (Cache flush) SRV PHILIPS_AC1715_1_XXXX.local.:80 0 0, (Cache flush) TXT "Device Type=Domestic Appliance", (Cache flush) A 10.0.0.228 (262)
> ```

I have an open UDP port 5353 on my ac1715. But it hangs after this:

`(env) ➜  ~ aioairctrl -H 192.168.2.81 -D -P 5353 status --json
DEBUG:aioairctrl.coap.client:syncing
DEBUG:coap:Sending request - Token: d207, Remote: <UDP6EndpointAddress 192.168.2.81:5353>
DEBUG:coap:Sending message <aiocoap.Message at 0x7f7861a2af00: NON POST (MID 20623, token d207) remote <UDP6EndpointAddress 192.168.2.81:5353>, 1 option(s), 8 byte(s) payload>`

Maybe you can get any further with this port?

**Comment by kongo09** [comment]
I'm sorry, I have no idea. Trying a different port is interesting but we need a response from aioairctrl or the integration cannot work

**Comment by Paul1865** [comment]
Ah, it's a fixed port in aioairctrl ... :/ 

I stumbled upon this user and code on GitHub: https://github.com/kandelvijaya/homebridge-philipsair-platform
He claims to have the AC1715 working in HomeBridge. I contacted him by mail to ask if it still working :D . Let's wait and see :) .

**Comment by kongo09** [comment]
Thanks for investigating. I had some users with a working AC1715 so there seem to be different models on the market.

**Comment by Paul1865** [comment]
I thought: what if the new purifiers only read its settings from the cloud via a get-command every second or so?
And we can only send those settings to the cloud with my AIR+ app.
So its a oneway POST from AIR+ to cloud and a oneway GET from device to cloud.

Thus I went searching and got the APK (on apkmirror) of the AIR+ app: here https://www.apkmirror.com/apk/versuni-netherlands-b-v/philips-air/philips-air-3-12-0-release/philips-air-3-12-0-android-apk-download/download/?key=74058427d2229d4fdc178e0207b58a3926bb12e5

Maybe there is a user who can deconstruct the .dex-files in the apk? I unzipped the APK, but there is still some unreadable code.

Instead of 'hacking' the device, maybe we should spend some time getting the required settings to the cloud using HA .

**Comment by Invisi** [comment]
@Paul1865 [jadx](https://github.com/skylot/jadx) and [apk.sh](https://github.com/ax/apk.sh) are some nice tools if you want to poke the app a bit.

That said, I've poked it a bit and it mostly communicates via MQTT with one singular REST call to retrieve historic sensor data and a lot of obfuscated HTTP requests to `https://data.air-matters.com/{string_of_letters_here}`. The latter ones containing lots of device metrics and location data of your phone, if it has access to your location, and fun AES encryption magic to build authentication(?) headers.

I was unfortunately unable to find any firmware blobs but going by how the device behaves and considering the Android app uses [esp-idf-provisioning-android](https://github.com/espressif/esp-idf-provisioning-android/tree/master/provisioning/src/main/java/com/espressif/provisioning) as library to transmit wifi credentials, there's a fair chance it's a well-known ESP model.
Unfortunately no internal images of the device either, as the only FCC ID listed in the manual is the wifi module: https://fccid.io/P53-EMW3080
Also wasn't able to properly open up my AC1715/11 to have a look myself

**Comment by nd3442** [comment]
@Paul1865 @Invisi did you guys ever reverse engineer the cloud API and get it working? Or have you guys returned the purifiers and swapped it for another machine?

I'm struggling to find a good purifier with Homekit/Homebridge/Home assistant support

**Comment by Paul1865** [comment]
No sorry, I didn't have time for it :/ . I gave up also :D .

**Comment by Paul1865** [comment]
Grok just gave me this option: **mitmproxy**

With that I could intercept all internet traffic between my phone (with the philips app) and the cloud.
I don't have much time, so it might take a while to get it set up.

Grok hints that when I intercepted all, I could send rest commands via HA.
Example:

```
rest_command:
  philips_airpurifier_on:
    url: "https://api.philips.com/airpurifier/control"
    method: POST
    headers:
      Authorization: "Bearer <jouw_token>"
    payload: '{"power": "on"}'

```

**Comment by Invisi** [comment]
Unrelated update and I've kinda given up as well for now ~~but as of a few days ago my AC1715s stopped working completely because the certificate of Versuni's [MQTT server](https://ats.prod.eu-da.iot.versuni.com/mqtt) is invalid. A locally-controlled device would still be very nice but apparently that's asking too much for IoT.~~

It was DNS, it's always DNS. Anyways, if I do have more time I'll see if there's any possiblity to get it running locally via other means.

![Image](https://github.com/user-attachments/assets/0d97f32b-0bc6-4ff8-b35b-d3644919290e)

**Comment by liammoz** [comment]
Did you guys ever find a fix for this? I have two of these air purifiers and I can’t troubleshoot it on my own. 

<img width="1320" height="1255" alt="Image" src="https://github.com/user-attachments/assets/e247f087-402e-42bf-afdf-43ea8b17611a" />

**Comment by nd3442** [comment]
Try this one:
https://github.com/MaddogWarner/homebridge-philips-air-purifier-complete
