### ISSUE TITLE
Missing turn on/off switch and fan speed in AMF870/15

### ISSUE THREAD

**Issue by JakubSukenik91** [kongo09/philips-airpurifier-coap#175]
Hello, I have a Philips fan - AMF870/15, but I don't see a switch to turn it on and off in Home Assistant, nor any entity to set the fan speed. Is there a way to set this up? Thank you.

**Comment by kongo09** [comment]
So what do you see? Can you share a screen shot of the device page? Which version are you on?

**Comment by JakubSukenik91** [comment]
Hello, I have 0.18.10 version, and I see these parameters:
![Snímek obrazovky 2024-11-01 v 22 45 55](https://github.com/user-attachments/assets/17e3fdc6-e742-40bc-ac0c-fa8cd3cb15f6)
![Snímek obrazovky 2024-11-01 v 22 46 05](https://github.com/user-attachments/assets/bcbddb58-4a0b-4e47-aa32-a15b3263680f)

**Comment by kongo09** [comment]
Oh, very strange. Obviously the device is detected and the integration can talk to it. Do you see any errors on the log?

**Comment by JakubSukenik91** [comment]
When I reload the integration, I get this error:
```python
Logger: homeassistant.components.fan
Zdroj: helpers/entity_platform.py:816
Integrace: Ventilátor (dokumentace, problémy)
První výskyt: 08:29:05 (2 výskyty)
Naposledy logováno: 09:30:52

Error adding entity None for domain fan with platform philips_airpurifier_coap
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 816, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 391, in capability_attributes
    supported_features = self.supported_features_compat
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 436, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 399, in supported_features
    | FanEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_OFF'
```

**Comment by kongo09** [comment]
Hm, not sure where this is coming from. If I check the class `FanEntityFeature` from HomeAssistant, it does indeed have an attribute `TURN_OFF`:

```python
class FanEntityFeature(IntFlag):
    """Supported features of the fan entity."""

    SET_SPEED = 1
    OSCILLATE = 2
    DIRECTION = 4
    PRESET_MODE = 8
    TURN_OFF = 16
    TURN_ON = 32
```

I've restructered the features part of the code a bit, which was on my todo list anyhow. Can you try v0.20.1-beta.1 and tell me if this works? Also, which version of HA are you running?

**Comment by JakubSukenik91** [comment]
Ok, I tried the newest version - v0.20.1-beta. Turn ON/OFF button is now visible, but fan speed is still missing. Version of HA:
![Snímek obrazovky 2024-11-02 v 13 08 39](https://github.com/user-attachments/assets/74f5af98-8244-4d65-9849-18e83851fd26)

Thanks!

**Comment by kongo09** [comment]
Can you paste a screen off your fan entity control please?

**Comment by JakubSukenik91** [comment]
Do you mean this?
![Snímek obrazovky 2024-11-02 v 18 40 29](https://github.com/user-attachments/assets/cb0b3d8c-38d9-4c88-ad02-227ebd5ad95c)
![Snímek obrazovky 2024-11-02 v 18 40 38](https://github.com/user-attachments/assets/6d13a79b-cf4b-4c0a-9b95-8cb25a13f300)

**Comment by kongo09** [comment]
If you click on the entity of the on/off button, what do you see?

**Comment by JakubSukenik91** [comment]
I don’t even feel like answering… I'm a bit embarrassed; I missed that, sorry :)
![Snímek obrazovky 2024-11-02 v 18 46 34](https://github.com/user-attachments/assets/c9f21e37-19ee-4f48-95ae-be4e14f4268e)
Everything is OK, thank you :)

**Comment by kongo09** [comment]
And you find the preset modes as well there, just below. It is honestly a bit confusing and feels strange - minor settings get their own switch directly usable from the device page, but the most important settings are hidden one click away. From a product perspective, this is debatable.

Anyhow, I'll close this issue now. If you like my work, feel free to [buy me a coffee](https://buymeacoffee.com/kongo09)
