### ISSUE TITLE
Philips AC0850/31 no longer controllable after update to v0.19.0

### ISSUE THREAD

**Issue by aextranet** [kongo09/philips-airpurifier-coap#179]
I've had two Philips AC0850/31 connected using this integration since early this year.

Since upgrade to v0.19.0 the integration displays the info from the device (air quality/RSSI etc) but none of the controls work to change mode.

I have deleted and re-added the devices as advised but that didn't change things.

I'm running HA v2024.10.4

Both devices are running wi-fi firmware AWS_Philips_AIR@73.1 and device firmware 1.1.1

The device/entities all display OK but the section under 'Controls', although displayed, does not control the device.

If more info is required I can provide but I'm not sure if this issue is 'known' yet.

**Comment by kongo09** [comment]
Can you try the latest beta?

**Comment by aextranet** [comment]
Not sure how to get yet but I'll give it a try. Thnx.

**Comment by aextranet** [comment]
I tried v0.20.1-beta.1 but that didn't work. Same effect - air quality &etc values display but no control.

Downgraded back to version 0.18.9 and, after removing and re-adding the devices it's back working again.

I'd like to spend a bit more time going through the released updates from 0.18.9 --> v0.20.0 again. I don't have the time to update, remove and re-add and do restarts properly at the minute. I will work through this and report back here in the next couple of days.

Thanks for the help!

**Comment by kongo09** [comment]
Thanks for your help. Can you please check if there are any errors in the log?

**Comment by jubie25** [comment]
v0.21.0 seems to solve the problem. My AC2889 is controllable again.
But although I downloaded the new version in HACS and restarted HA and the behaviour has definitely changed the running integration is still shown as v0.18.10...
Yes, I updated the browser cache and also had a look into the companion app - the same.
Maybe missed to update the version string?

**Comment by kongo09** [comment]
>  the running integration is still shown as v0.18.10.

I forgot to update the version string, good catch!

But what about the AC0850/31 that stopped working? There are various models out there with the same model number but different command codes. Is it working or not and if not, what is the error log?

**Comment by jubie25** [comment]
> But what about the AC0850/31 that stopped working? There are various models out there with the same model number but different command codes. Is it working or not and if not, what is the error log?

Because my AC2889 showed the same behaviour as the reported AC0850/31 my guess is that it's working again, too... :-)

**Comment by aextranet** [comment]
I've just found out about the new version update. I can't do it right now but I will run the update and report back in the next couple hours.

Then I'll know if my two AC0850/31's are working ok or not and report back ASAP.

**Comment by aextranet** [comment]
I've just updated to v0.21.0 and I get the same problem I had before with v0.19.0 (info but no control) with the AC0850/31's.

I don't have time to look into the logs at the moment but I'll be able to tomorrow morning.

**Comment by kongo09** [comment]
Thank you. The device is surely a complicated one so the log would help plus ideally you use `aioairctrl` to post a status from the device

**Comment by aextranet** [comment]
I installed v0.21.0 and enabled debug logs. deleted then re-added the AC0850/31

In the HA logs I found:-
"Config not ready, first refresh failed for host 192.168.xx.xx" but I think this is maybe normal at startup?

Then, just after that I get:-
"Unsupported model: AC0850"

I did try the steps with aioairctrl but they wouldn't work on my setup. I can maybe try again this weekend though.

They both work with v0.18.9 ok.

**Comment by kongo09** [comment]
Well, `aioairctrl` didn't change so that should work independently of your integration version. However, if it doesn't work, the integration doesn't work either. So maybe something in your network changed?

**Comment by aextranet** [comment]
> So maybe something in your network changed?

Nothing material has changed on the network. The air purifiers stopped working as soon as I upgraded to v0.19.0

Everything works as before when I downgrade to v0.18.9

**Comment by kongo09** [comment]
This is not logical. `aioairctrl` is the same, regardless which version of the integration you are using. It doesn't make sense if it works in one version but not in the other. Can you please verify this again?

**Comment by aextranet** [comment]
Upgrading to v0.21.0 causes the same problems and error messages when I tried upgrading/remove devices/re-add devices again.

How is the integration working out what models it supports?

It produces the error message "Unsupported model: AC0850" therefore it's detected the model correctly and flagged it as unsupported because the model number is either in a known list of unsupported models or hasn't been recognised in a list of supported models.

In version 0.18.9 I do not get that error message showing in the logs.

It can't be aioairctrl throwing that error message as you say that hasn't changed. Therefore it seems something in the integration is deciding that the model is unsupported. I suspect this error processing is also resulting in the controls part not being executed?

**Comment by kongo09** [comment]
Hm, so you say downgrading to 0.18.9 gets the system reliably back working?

**Comment by kongo09** [comment]
I do need some debug logs, can you please generate them and share?

**Comment by kongo09** [comment]
Oh, and please share the output from your `aioairctrl` as well

**Comment by kongo09** [comment]
If you cannot get `aioairctrl` running, I have another idea how to find out what firmware you are using. In the Air+ app, please go to the device settings and check device information. You should see the WLAN-firmware. What does it say for your device?

**Comment by aextranet** [comment]
Both devices are running wi-fi firmware AWS_Philips_AIR@73.1 and device firmware 1.1.1

**Comment by kongo09** [comment]
Please check v0.28.0-beta.1

**Comment by aextranet** [comment]
I installed v0.28.0-beta.1 -> Restarted HA -> Removed the device -> restarted HA -> added device.

I got the same problem as before. Everything except the control works.

The two entities that don't work on the device are 'fan.philips_ac0850' and 'select.philips_ac0850_preferred_index'.

The other 5 entities appear to be working.

In the log I got:-

Logger: custom_components.philips_airpurifier_coap.light
Source: custom_components/philips_airpurifier_coap/light.py:66 
...
Unsupported model: AC0850

**Comment by aextranet** [comment]
Rolled back to v0.18.9 -> restarted HA -> Removed device -> Added device

and it's working as expected again with all entities available.

**Comment by kongo09** [comment]
I have a feeling where the problem is and I've added more debug information. Please try v0.28.0-beta.2

Make sure, debugging is enabled for the integration. If you cannot enable it because the setup doesn't complete, put the debug lines into your configuration.yaml as described in the README. When you add the device, there should be some output in the log telling us why the model is considered unsupported.

It might be that it reports with a different model string. I've seen that before with another device.

**Comment by aextranet** [comment]
I installed v0.28.0-beta.2 -> Restarted HA -> Remove device -> Add device -> Restart HA

and it works! Interestingly I think it's now naming the device 'AC0850/31' which is correct. I think it was naming it just 'AC0850' before.

I can't see any errors in the logs from the integration. All entities show as available.

The controls for the mode and preferred index work correctly. The values reported match what the Philips app says.

I'd say you've nixed it. Thank you!

**Comment by kongo09** [comment]
I'm happy that we found the problem. The AC0850 family of devices is a bit complicated. It seems even with the same model number some devices are just different, so I need to treat them individually. Anyhow, glad it's fixed. I've just released this in v0.28.0

If you like my work you can [buy me a coffee](https://buymeacoffee.com/kongo09)
