### ISSUE TITLE
Expose CX5120 as a Climate device

### ISSUE THREAD

**Issue by kitkat270** [kongo09/philips-airpurifier-coap#185]
Hi, would it be possible to use a climate entity instead of a fan entity for the CX5120? It shares many characteristics as climate device including set temp, current temp, heating mode and align better with other heating devices.

Thank you.

**Comment by kongo09** [comment]
Interesting question, I wasn't even aware that this exists. At the moment, the whole integration is built around the assumption that the base entity is a fan.

If someone submits a pull request with a suggestion, I'm happy to check that, but otherwise I'd focus on other stuff right now.

**Comment by kitkat270** [comment]
No worries, I'm not a dev, so I don't think I'm capable of doing it myself. If anyone else could have a go, im happy to test / debug.

But thanks for all your efforts with the integration as it is, works fine for me.

**Comment by kongo09** [comment]
I'd like to reopen and reconsider this. I've just implemented the `humidifier` entity for the 2-in-1 devices and for some devices then removed the main `fan` as it was redundant. Maybe I can do something similar for the heaters. It was less effort than I first though. See #198 

Would you still be up for testing if I start this?

**Comment by kitkat270** [comment]
Yeah, sure!

**Comment by kongo09** [comment]
Can you please check for me what the minimum temperature and the maximum temperature settings are on the device or in the Air+ app? The manual says 1 to 37 °C. Is that correct?

The manual also talks about two heating settings. Right now, we have implemented High and Low but I thought these were fan speeds. Is the fan speed always the same and this is a heating setting?

**Comment by kitkat270** [comment]
hi,  yeah, so it does go from 1 to 37 in the app.

With modes there are:
Auto - keep to the set temperature 
High - which just blows out hot air (no temperature control)
Low - blows out  slightly less hot air (no temperature control)
Ventilation - fan only, no heat
Then there's oscilation on/off

**Comment by kongo09** [comment]
I've done a first beta but it's a bit of a shot in the dark as I don't have access to a heater and cannot test anything.

Please try v0.33.0-beta.1 and let me know if the `climate` entity even shows up in addition to the `fan` entity. If that works and once everything is functional, I'll remove the fan.

I've left the modes now as fan modes, but there is also an option to make them so called preset modes. Not sure what is better. We can try both.

I'd also appreciate a screenshot of how the controls look like, as I have no idea, really.

**Comment by kitkat270** [comment]
![Screenshot_20241207_103028_Air+](https://github.com/user-attachments/assets/dfbb6e4c-dba1-4d07-97bc-ddf30eab30d9)
![Screenshot_20241207_103049_Air+](https://github.com/user-attachments/assets/a2f31d85-1584-4e50-8d4f-f0c654b7b293)
![Screenshot_20241207_103057_Air+](https://github.com/user-attachments/assets/a29a3462-c993-4a54-b1c8-f3e73c9738a6)
![Screenshot_20241207_103114_Air+](https://github.com/user-attachments/assets/714381cf-66e6-447a-bfd4-8f9a307018d1)

**Comment by kitkat270** [comment]
Thanks will try later. 

I've got some kid taxiing to do today,  back later

**Comment by kongo09** [comment]
Thanks for the help. Curious to hear if the climate thing shows or you just get a log full of errors...

**Comment by kongo09** [comment]
I realize, I need to take the icons over with the thermometer...

**Comment by kongo09** [comment]
I've now included the icons and started translation. Please try v0.33.0-beta.2

**Comment by kitkat270** [comment]
Hi, not seeing the climate entity
[home-assistant_philips_airpurifier_coap_2024-12-07T17-57-59.948Z.log](https://github.com/user-attachments/files/18049378/home-assistant_philips_airpurifier_coap_2024-12-07T17-57-59.948Z.log)

**Comment by kongo09** [comment]
Stupid bug on my end, please try: v0.33.0-beta.3

**Comment by kitkat270** [comment]
Hmmm, still not getting it with beta 3.

**Comment by kongo09** [comment]
Next try: v0.33.0-beta.4

I've added some debug logging. If it still doesn't work, please enable logging and share the logs.

**Comment by kitkat270** [comment]
[home-assistant_philips_airpurifier_coap_2024-12-07T21-58-35.291Z.log](https://github.com/user-attachments/files/18049994/home-assistant_philips_airpurifier_coap_2024-12-07T21-58-35.291Z.log)

**Comment by kitkat270** [comment]
Climate entity not showing up. Looks like there could be something useful at the end of the logs there.

**Comment by kongo09** [comment]
Very helpful, thanks, will fix tomorrow

**Comment by kongo09** [comment]
Next try: v0.33.0-beta.5

I found quite a few bugs and tested more. I still struggle to use the right icons in the HVAC mode, but maybe that's ok. Let me know if it works.

**Comment by kitkat270** [comment]
Hi, climate device does appear now.
Modes work fine, except selecting off mode doesn't turn off the device. 

Swing button doesn't seem to work either. I'm not in at the moment, but will get logs later on. 

Good start!

**Comment by kongo09** [comment]
I think I found the bug with the switching off.

For the swing mode, I've added quite some debugging. How does the swing mode look like in the HA interface?

Please try: v0.33.0-beta.6

**Comment by kitkat270** [comment]
Switching off seems good now - thanks!

[home-assistant_philips_airpurifier_coap_2024-12-08T17-49-59.541Z.log](https://github.com/user-attachments/files/18053410/home-assistant_philips_airpurifier_coap_2024-12-08T17-49-59.541Z.log)
![Screenshot 2024-12-08 174613](https://github.com/user-attachments/assets/b29647c1-9188-4b24-b934-d3d2b3ce9743)

**Comment by kongo09** [comment]
Oh, the preset mode has no icons?

**Comment by kitkat270** [comment]
It does have icons. Maybe I forgot to refresh the browser after reboot.
![Screenshot 2024-12-08 180048](https://github.com/user-attachments/assets/e9b95eaa-bbe6-4fd4-9139-7825e364b085)

**Comment by kongo09** [comment]
Ah, good. Now what exactly happens with the swing mode? I don't see any errors in the log

**Comment by kongo09** [comment]
And does setting the target temperature work?

**Comment by kitkat270** [comment]
Setting temp is all good.

The swing mode...
If state (as shown in app) OFF -  HA shows as off. Switching on in HA has no effect, it stays off.
If state (as shown in app) ON -  HA shows as off. Switching on in HA turns it off.

**Comment by kongo09** [comment]
The separate switch still works?

**Comment by kitkat270** [comment]
Sorry, I meant the swing state, not the power state.
If swing state is off, HA shows off, switching it on in HA has no effect
If switch state is on, HA shows it as off, switching it on in HA then turns swing off.

**Comment by kongo09** [comment]
Yes, but I had a separate switch outside the climate entity before. Does that still work?

**Comment by kongo09** [comment]
I've added even more debugging output. In the last log I didn't see how the oscillation values are setup. Can you remove the integration and setup fresh?

New beta is: v0.33.0-beta.7

**Comment by kitkat270** [comment]
Hi, OK, so the swing control operates almost the same as it does on the fan entity.
Fan:
Swing off command from HA turns off swing mode.
Swing on command from HA doesn't appear to do anything

Climate:
Swing off command doesn't do anything
Swing on command doesn't do anything unless its currently on and in which case, it turns it off.
[home-assistant_philips_airpurifier_coap_2024-12-08T19-46-44.540Z.log](https://github.com/user-attachments/files/18053757/home-assistant_philips_airpurifier_coap_2024-12-08T19-46-44.540Z.log)

**Comment by kongo09** [comment]
Ok, that sounds like a general problem as I thought the swing with the fan worked before, but apparently not?

**Comment by kongo09** [comment]
Can you please share the output of aioairctrl again with swing on and with swing off

**Comment by kongo09** [comment]
The log still doesn't show the setup of oscillation. Strange.

**Comment by kitkat270** [comment]
[home-assistant_philips_airpurifier_coap_2024-12-08T20-27-53.636Z.log](https://github.com/user-attachments/files/18053885/home-assistant_philips_airpurifier_coap_2024-12-08T20-27-53.636Z.log)

Does this contain what you need? Do I need to get output of aioairctl from somewhere else?   Thanks

**Comment by kongo09** [comment]
The log shows that the oscillation values arrive properly inside the `climate` entity, so that's cool. Thanks.

I now went back to the original issue #95 where I added the CX5120 in the first place. It turns out, that we never got the oscillation to work properly. Turning on doesn't work.

I've changed now one more thing but if that doesn't do the trick either, we might have a problem. But please try v0.33.0-beta.8 first before I propose something else.

**Comment by kitkat270** [comment]
Hi, just tried beta8, same issue with the swing.   Everything else looks good though - fab! :-)

**Comment by kongo09** [comment]
Is turning off command now turning off?

**Comment by kongo09** [comment]
Anyhow, I've seen another swing device that had a similar problem. It shows a certain control value when the swing is on, but setting that value via the commands doesn't turn it on. The solution was, that a different value needs to be set to activate the swing. Question is just: which one?

0 is for off, so that should definitely work.

To find out the value for on, the owner of that other fan used a trick. They sent a range of control values manually to the device until one of them started the fan. You can read about it here: https://github.com/kongo09/philips-airpurifier-coap/issues/137#issuecomment-2227309879

Maybe the number they found for the CX3550 works here as well? I'll do a beta with it: v0.33.0-beta.9

But if not, you might want to familiarize yourself with `aioairctrl`. It is described in the README and it allows you to send control values to the device manually from the command line.

**Comment by kitkat270** [comment]
Hi, yes, on beta 9, swing off turns it off, but the on isn't working.

Just noticed one other thing, the temperature setpoint needs to be a whole number, the climate entity has 0.5 degree granularity.

I'll take a look at aioairctrl and see if I can get the correct value, but that will be another day. 

Huge thanks with the climate entity, brilliant!!!

**Comment by kongo09** [comment]
In v0.33.0-beta.10 I've now added a temperature step of 1 degree. So the only thing that's missing is the oscillation switch on, correct?

**Comment by kitkat270** [comment]
Hi, yes. All looks good with beta 10, except the oscillation.

**Comment by kongo09** [comment]
I've now released the work. Thanks so much for all your help and testing. For now, I've left the `fan` entity in to help other users transition over to `climate` but I'll remove this in v0.35.0

For the challenge of finding the correct value for oscillation, I'll open a separate issue #227 . Maybe others can help.

If you like my work, [you can get me a coffee](https://buymeacoffee.com/kongo09).
