### ISSUE TITLE
v0.22.0 not working for Philips AC2889

### ISSUE THREAD

**Issue by jubie25** [kongo09/philips-airpurifier-coap#188]
Again bad news... after updating to 0.22.0 no connection could be established to AC2889. With 0.21.0 things were working again (after troubles with versions newer than 0.18.10, I reported). Coming back to 0.21.0 the purifier could connect again.
Problem with 0.,22.0: initializing for hours, no success. Usually setting a command with the Philips App during restart of HA make the device connecting. All that didin't help with 0.22.0.
Staying with 0,21.0 by the moment. Guess you'll need logs...?

**Comment by kongo09** [comment]
Again, very strange. If anything, version 22 should find it easier to connect than the previous versions. To be precise, the previous versions tried to establish a connection on start of HA and that sometimes brought the whole HA start down as the devices are not well behaving with the connection. Version 22 now stores the latest state inside HA so when you start, it fetches the latest stored data instead of asking for new data. That should speed up the HA start process. It could lead to old data being displayed, but that trade-off feels ok as the devices later will report fresh data anyhow.

Only the first time version 22 starts it needs to fetch the missing data for one very last time. This is probably where it hangs for you.

What doesn't make much sense is that version 21 wouldn't hang - because it makes the same connection attempt. My feeling is, you've just not been lucky with version 22 and you should try again. Maybe do a power cycle of your device before.

**Comment by hogend** [comment]
Similar observation: AC2889 is not working with 0.22.
I get:
```
Logger: custom_components.philips_airpurifier_coap
Source: custom_components/philips_airpurifier_coap/__init__.py:140
integration: Philips AirPurifier (with CoAP) ([documentation](https://github.com/kongo09/philips-airpurifier-coap), [issues](https://github.com/kongo09/philips-airpurifier-coap/issues))
First occurred: 13 November 2024 at 21:03:11 (1988 occurrences)
Last logged: 17:07:30
Failed to connect to host 192.168.7.80: No address information found for requests to '192.168.7.80'
```
Note that ping to that address succeeds.

**Comment by kongo09** [comment]
The ping doesn't say much beyond that the device is reachable. The question is, does it answer on the API calls.

The way to try that is to run the `aioairctrl` command as described in the README. If your device was working with an earlier version of this integration, there is no reason why it wouldn't work with version 0.22 Can you please downgrade and verify?

**Comment by kongo09** [comment]
I've tried version v0.22.0 on an AC2889 and it definitely works as expected. I assume that you have connectivity problems with your devices. A downgrade should not give better results but lead to the same problems. When I have these troubles, a power cycle often (but not always) helps.

**Comment by jubie25** [comment]
I know this sounds really weird. But with v0.23.0 controlling the purifier is possible again. I switched from pre-0.22 to 0.22 and further to 0.23 and back again, always the same: v0.22 doesn't connect to the device (AC2889).
I can imagine this is frustrating to a developer that didn't change a bit in the source that may explain this. But it is (that's the reason why I alway rebuild a project in total  before testing/shipping to avoid strange things happen because of a mixture of older compiled modules and newer - but this is a short sidestory that doesn't need to tell anything :-) ).

I try now to hold v0.23 until there may be a solution to the last thing that's always needed, in all versions:
during start of HA / the integration one has to open the Philips App and perform a connection to the device. Loading the integration then continues.

**Comment by kongo09** [comment]
There was a change in the latest version on auto-detection. Do you use auto-detection or do you enter the IP manually?

Does the hanging during start of HA continue now that you've got v0.23 working - it is somewhat expected the first time but not afterwards.

**Comment by kongo09** [comment]
Hang-on, the fix for auto detection is in  v0.23.1

**Comment by hogend** [comment]
Problem is not fixed in 0.23.2 with HA version 2024.11.1

The error message states

```No address information found for requests to '192.168.7.80'```

which is strange, given that it is the valid IPv4, correct and reachable address assigned to the device
I get the exceptions listed below and it seems related to IPv6. Note that the change may actually be in HA, not in the coap code per se.

```
2024-11-18 22:05:36.779 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aiocoap/transports/udp6.py", line 483, in determine_remote
    ip, port, flowinfo, scopeid = await getaddrinfo(
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aiocoap/util/asyncio/getaddrinfo_addrconfig.py", line 96, in getaddrinfo_routechecked
    raise socket.gaierror
socket.gaierror

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hass/.homeassistant/custom_components/philips_airpurifier_coap/config_flow.py", line 69, in async_step_dhcp
    client = await CoAPClient.create(self._host)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aioairctrl/coap/client.py", line 41, in create
    await obj._init()
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aioairctrl/coap/client.py", line 36, in _init
    await self._sync()
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aioairctrl/coap/client.py", line 57, in _sync
    response = await self._client_context.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aiocoap/protocol.py", line 758, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aiocoap/protocol.py", line 787, in _run
    await protocol.find_remote_and_interface(app_request)
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aiocoap/protocol.py", line 456, in find_remote_and_interface
    if await ri.fill_or_recognize_remote(message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aiocoap/tokenmanager.py", line 218, in fill_or_recognize_remote
    return await self.token_interface.fill_or_recognize_remote(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aiocoap/messagemanager.py", line 408, in fill_or_recognize_remote
    remote = await self.message_interface.determine_remote(message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aiocoap/transports/udp6.py", line 490, in determine_remote
    raise error.ResolutionError(
aiocoap.error.ResolutionError: No address information found for requests to '192.168.7.80'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/homeassistant/helpers/discovery_flow.py", line 137, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/homeassistant/util/async_.py", line 114, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/homeassistant/util/async_.py", line 112, in sem_task
    return await task
           ^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1301, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1336, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/.homeassistant/custom_components/philips_airpurifier_coap/config_flow.py", line 93, in async_step_dhcp
    raise exceptions.ConfigEntryNotReady from ex
homeassistant.exceptions.ConfigEntryNotReady: No address information found for requests to '192.168.7.80'
2024-11-18 22:05:36.877 WARNING (MainThread) [custom_components.philips_airpurifier_coap] Failed to connect to host 192.168.7.80: No address information found for requests to '192.168.7.80'
```

**Comment by jubie25** [comment]
for me v23.2 does work!
Again: I downloaded v23.2 but the integration says 23.0...
Thanks!

**Comment by kongo09** [comment]
> Again: I downloaded v23.2 but the integration says 23.0...

That's just a number in a file that I like to forget. I'll try to automate this.

**Comment by kongo09** [comment]
>  it seems related to IPv6

Note that others have reported something similar in the past. It might be related to the CoAP library. The solution was to make sure that IPv6 is enabled in the network / on your machine (even though the integration itself and the Philips devices don't need it). Can you investigate that?

**Comment by hogend** [comment]
> > it seems related to IPv6
> 
> Note that others have reported something similar in the past. It might be related to the CoAP library. The solution was to make sure that IPv6 is enabled in the network / on your machine (even though the integration itself and the Philips devices don't need it). Can you investigate that?

The network is actually dual stack IPv4/IPv6

The question is, why is it  failing here
```
  File "/home/hass/virtualenv3.12/lib/python3.12/site-packages/aiocoap/transports/udp6.py", line 483, in determine_remote
    ip, port, flowinfo, scopeid = await getaddrinfo(
```
since the specified address is NOT an IPv6 address. It should never try to "await getaddrinfo" in udp6.py

**Comment by kongo09** [comment]
Do you have a traceback to see what is calling this?

**Comment by kongo09** [comment]
try v0.27.2-beta.1

**Comment by hogend** [comment]
Thanks. Will try tomorrow On 24 Nov 2024 16:43, kongo09 ***@***.***> wrote:
try v0.27.2-beta.1

**Comment by kongo09** [comment]
Any new insight? Does beta v0.27.2-beta.1 work for you?

**Comment by kongo09** [comment]
@hogend : can you please check if beta v0.27.2-beta.1 resolves the problem. The integration has now advanced quite a bit and I'd like to understand if I merge this in or not.

**Comment by hogend** [comment]
> @hogend : can you please check if beta v0.27.2-beta.1 resolves the problem. The integration has now advanced quite a bit and I'd like to understand if I merge this in or not.

I did not check that particular version, but I tried to analyze the problem a bit further.
The problematic bit seems to be in this section of "aiocoap/util/asyncio/getaddrinfo_addrconfig.py":
```
    for ip, port, flowinfo, scope_id in itertools.chain(v6_addresses, v4_addresses):
        # Side-step connectivity test when explicitly giving an address. This
        # should be purely a cosmetic change, but given we try not to give IP
        # addresses special treatment over host names, it needs to be done
        # somewhere if we don't want connection attempts to explicit V6
        # addresses to err with "No address information found" on V4-only
        # hosts.
        if ip != host:
            with socket.socket(
                family=socket.AF_INET6, type=socket.SOCK_DGRAM, proto=socket.IPPROTO_UDP
            ) as tempsock:
                try:
                    tempsock.connect((ip, port))
                except OSError as e:
                    if e.errno == errno.ENETUNREACH:
                        continue
```

It fails as follows
```
> aiocoap/util/asyncio/getaddrinfo_addrconfig.py(83)getaddrinfo_routechecked()
-> tempsock.connect((ip, port))
(Pdb) p host
'air-purifier-living.rmer.nl'
(Pdb) p ip
'::ffff:192.168.7.80'
(Pdb) p port
5683
(Pdb) n
OSError: [Errno 101] Network is unreachable
```
So ip!= host and it tries to connect with IPv6. That does not work!
Whereas IPv4 connects properly:
```
(Pdb) tempsock = socket.socket(
...                             family=socket.AF_INET, type=socket.SOCK_DGRAM, proto=socket.IPPROTO_UDP)
(Pdb) tempsock.connect(('192.168.7.80',port))
```
i.e. no OSError.

To me, it seems logical that connecting to '::ffff:192.168.7.80' fails since the server is on IPv6 network 2001:470:7d7d::0 with routing to a 6-over-4 tunnel in place. Why does the original IPv4 address needs to be converted into IPv6 in the first place?
I hope this helps to find a solution.

Note: commenting out the tempsock.connect call makes HA connect with the AC2889 again

**Comment by kongo09** [comment]
Thanks for the detail. Please try above mentioned beta (and only that beta) if it works

**Comment by hogend** [comment]
> Thanks for the detail. Please try above mentioned beta (and only that beta) if it works

Still fails in aiocoap/util/asyncio/getaddrinfo_addrconfig.py . Same traceback as above with
```
aiocoap.error.ResolutionError: Name resolution error: No address information found for requests to '192.168.7.80'
```

**Comment by kongo09** [comment]
Maybe you want to open an issue with aiocoap? I'm not sure what I can do on my end?

**Comment by jubie25** [comment]
After a relatively stable run time of a few days with 0.32. I dared to update to 0.33. The end: nothing's running anymore, neither 0.32 nor 0.33. There's "no connection" to the purifier (but pings and connect via Philips app does work). The log doesn't say very much:
```
2024-12-12 07:13:54.743 ERROR (MainThread) [coap] Connection loss was not expected.
2024-12-12 07:15:07.559 WARNING (MainThread) [custom_components.philips_airpurifier_coap.config_flow] Timeout, host 10.9.5.119 doesn't answer, aborting
```
I deleted the device, believing this would erase some misformed data. But now I cannot rejoin it to HA because of "no connection".
Maybe I can patch aiocoap/util/asyncio/getaddrinfo_addrconfig.py as mentioned by hogend above but I cannot find that file/folder....

**Comment by kongo09** [comment]
@jubie25 this sounds very much like the Philips connectivity problem and has nothing to do with the integration. Maybe try power cycle your device! 

@hogend your ipv6 problem might be related to aiocoap leaning heavily on ipv6. Maybe related to https://github.com/chrysn/aiocoap/issues/222

Please also check https://github.com/kongo09/philips-airpurifier-coap/issues/162#issuecomment-2433273171

There is nothing I can do so I will close this issue here.
