### ISSUE TITLE
Sound control ?

### ISSUE THREAD

**Issue by tebra-jl** [kongo09/philips-airpurifier-coap#19]
Hi,
Is it possible to enable or disable the sound of the airpurifier with this integration ?

AC2729/10
Firmware: AWS_Philips_AIR@69.1

**Comment by kongo09** [comment]
I'm not aware that this is possible on any device. I don't think it's an option on the Clean Home+ app either.

If you have any information pointing to an API to make this happen, please reopen the issue with more details.
