### ISSUE TITLE
AC1715/11 ConnectionRefusedError

### ISSUE THREAD

**Issue by n0way0ut** [kongo09/philips-airpurifier-coap#190]
hello,

I just get a philips air purifier 1000i (AC1715/11), but I am not able to setup (I get timeout error), so I checked in the issues and it seems that it was sorted out last year, so I tried with` aioairctrl --host 10.0.30.8 status-observe` and I get `ConnectionRefusedError: [Errno 111] Connection refused (ECONNREFUSED, received through errqueue)`
the device is correctly connected to the WIFI and it is working with the philips AIR+ app.
is this device has still COAP available?

**Comment by n0way0ut** [comment]
duplicate of https://github.com/kongo09/philips-airpurifier-coap/issues/152 closing.

**Comment by kongo09** [comment]
Connectivity is a problem generally and it might very well be that your device doesn't even offer encrypted CoAP. The AIR+ app is using a different mechanism via AWS.

**Comment by baulaergrungim** [comment]
I  have the same issue with my AC1715/11 that I got this week. I brought the topic of opening API on their app in google store, but I don't think they will do much about it. Maybe if they hear more voices? They allow to link it in Google Home, they could do exactly the same for HA, c'mon.
