### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by aceindy** [kongo09/philips-airpurifier-coap#199]
Since this requires quite some time to startup
![image](https://github.com/user-attachments/assets/a88a42d0-ee3d-4570-90a4-1556ff55c048)
Wouldn't it be possible to start it with a non-blocking condition?

I guess changing  manifest.json 
`  "dependencies": ["frontend", "http"],`
into 
` "after_dependencies": ["frontend", "http"],`
would already help to at least have a delayed startup ;)

**Comment by kongo09** [comment]
We can try that. Are you also using the latest version?

**Comment by aceindy** [comment]
Ofc Kongo...

My biggest issue is that the loading of this integration is blocking the rest ofc the integrations to load.
So f.e. that means, I have to wait 92.2s before I can contoll any my lights :/ 

It would already be a solution if this could be loaded last, but so far I haven't found out if it possible to have any influence on the load sequence within HA; it doesn't look like it has any :?

After I changed _dependencies_ into _after_dependencies_ that behavior seems to have improved.
It hasn't sped up, but at starts later, after the frontend has loaded (and by that time, the lights also work)

I've been doing a little research, and it seems to queue up at the end of the startup this works best (in my case)
_"after_dependencies": ["mqtt", "frontend", "http", "mobile_app"]_

Since I have 3 devices, this peace of code doesn't help:
       client = await asyncio.wait_for(CoAPClient.create(host), timeout=25)
 So still the best would be to have some non-blocking solution..

**Comment by kongo09** [comment]
Thanks, let's experiment with that and debug further. I did some recent changes where I store the last device readings in the HA database and instead of querying the devices on startup, I just use the stored data, which already should have improved the startup. Not sure where it now gets stuck and what to do, any help appreciated.

**Comment by kongo09** [comment]
I think I found a problem in the code, please try the latest beta

**Comment by kongo09** [comment]
Should be solved by #204 in release v0.25.0

**Comment by aceindy** [comment]
@kongo09  Checking 2.5...looks better,but weird startup time :?
It started 12.37 sec before restart hmpf?
![image](https://github.com/user-attachments/assets/bf561a20-1554-4cee-b964-a364fad42fac)
