### ISSUE TITLE
Add support: HU1510

### ISSUE THREAD

**Issue by stijnb1234** [kongo09/philips-airpurifier-coap#200]
Could you add support for the new HU1510?

**Comment by kongo09** [comment]
Can you share the data as described in the README?

**Comment by stijnb1234** [comment]
> Can you share the data as described in the README?

Ofcourse, I'm sorry. Here you go.

```json
{
  "D01102": 1,
  "D01S03": "Woonkamer",
  "D01S04": "Stargazer",
  "D01S05": "HU1509/00",
  "D01107": 0,
  "D01108": 3,
  "D01109": 3,
  "D0110A": 0,
  "D0110C": 1,
  "D01S0D": "688001002538",
  "D0110F": 3,
  "D01S12": "0.3.9",
  "D01213": 0,
  "ProductId": "e7b912f42a1411ef9e0106d016384e4a",
  "DeviceId": "e56c13de676811ef87e0fbaa6c32493c",
  "otacheck": false,
  "Runtime": 89865302,
  "rssi": -55,
  "wifilog": false,
  "blelog": -1,
  "free_memory": 150336,
  "WifiVersion": "AWS_Philips_AIR_Combo@5.2",
  "StatusType": "status",
  "ConnectType": "Online",
  "D03102": 1,
  "D03104": 115,
  "D03105": 115,
  "D0310A": 4,
  "D0310C": 0,
  "D0310D": 0,
  "D03110": 0,
  "D03211": 0,
  "D03224": 190,
  "D03125": 49,
  "D03128": 50,
  "D0312A": 6,
  "D0312B": 6,
  "D03130": 1,
  "D03134": 1,
  "D03135": 1,
  "D03137": 0,
  "D0313B": 20,
  "D03240": 0,
  "D05207": 180,
  "D0520D": 156
}

```

**Comment by kongo09** [comment]
Ok, I will see how far I get with that. I might need some more data with changed settings but with a bit of luck the above is already enough to identify a similar device and take it from there. Once I have something, I'll do a beta for you to test.

**Comment by stijnb1234** [comment]
Thanks! Let me know if you need more information or help.

21 nov 2024 18:06:34 kongo09 ***@***.***>:

**Comment by kongo09** [comment]
I created a first beta version v0.26.0-beta.1 but I'm not entirely sure which functions exist with your device. So might find some things in the integration that actually don't work with your device - but there might also be stuff missing that you see in the Air+ app. Please give it a try and let me know what is missing or not working.

**Comment by stijnb1234** [comment]
It says Model not supported. I think the HU1510 identifies as HU1509 as the only difference is the color I believe.

**Comment by kongo09** [comment]
Ah, sorry, I see it in the data above. I've now added the HU1509 as well. Please try the latest beta.

**Comment by stijnb1234** [comment]
It connects now. I didn't test all the settings yet, but the values itself seem to be configured correctly.

**Comment by kongo09** [comment]
Please try v0.26.0-beta.5 and maybe you can share a screenshot of the humidifier card. Does it show modes? It shouldn't on your device as you can only use on and off. I've changed the on/off function so that you can use the humidifier entity to power the device. For the fan speed you still have to use the fan settings.

**Comment by stijnb1234** [comment]
> Please try v0.26.0-beta.5 and maybe you can share a screenshot of the humidifier card. Does it show modes? It shouldn't on your device as you can only use on and off. I've changed the on/off function so that you can use the humidifier entity to power the device. For the fan speed you still have to use the fan settings.

The HU1510 does support modes: Auto, Sleep, Medium and High. Or are these other modes?

**Comment by kongo09** [comment]
You can find these modes in the `fan` entity

**Comment by kongo09** [comment]
I've just done a new beta v0.29.0-beta.1 which tries to hide the `fan` entity for you and put the modes into the `humidifier` entity. Please try and reopen if this doesn't work.
