### ISSUE TITLE
Clarify project's license

### ISSUE THREAD

**Issue by justinas** [kongo09/philips-airpurifier-coap#209]
Hi,

First of all, cool project! I recently ordered a supported Philips air purifier and I am hoping to utilize this integration! In my work to package this for Nix, I need to specify the license. However, I could not find a LICENSE file in the repository, or any indication of how it is licensed.

I noticed that the [original project](https://github.com/Denaun/philips-airpurifier-coap) this was forked from did not include a license either. Technically, that could mean "all rights reserved".

I would be thankful for any input you could give me on this.

**Comment by kongo09** [comment]
Valid question. You're right, the original project didn't have a license, which is one reason I didn't give one either. It's debatable how much of the original intellectual property is left as I changed it drastically, but nevertheless this is an open question.
