### ISSUE TITLE
Add support for CX3120/01

### ISSUE THREAD

**Issue by arashjalalat** [kongo09/philips-airpurifier-coap#214]
Hello! I noticed that the model CX5120 is supported. Is there a way to also support the model CX3120/01? I was able to output the json.

```json
{
    "D01102": 3,
    "D01S03": "My Device",
    "D01S04": "Prometheus",
    "D01S05": "CX3120/01",
    "D01107": 0,
    "D01108": 3,
    "D01109": 3,
    "D0110A": 0,
    "D0110B": 1,
    "D0110C": 1,
    "D01S0D": "688001001670",
    "D0110F": 3,
    "D01S12": "0.3.7",
    "D01213": 0,
    "ProductId": "2f21b227facd11ee974e06d016384e4a",
    "DeviceId": "914ca6c6920711ef8aa3cb42fa086425",
    "otacheck": false,
    "Runtime": 2064866514,
    "rssi": -59,
    "wifilog": false,
    "blelog": -1,
    "free_memory": 154272,
    "WifiVersion": "AWS_Philips_AIR_Combo@6.2",
    "StatusType": "status",
    "ConnectType": "Online",
    "D03102": 1,
    "D03103": 1,
    "D0310A": 3,
    "D0310C": 0,
    "D0310D": 3,
    "D0310E": 19,
    "D0320F": 45,
    "D03110": 0,
    "D03211": 0,
    "D03224": 193,
    "D0312A": 5,
    "D0312B": 5,
    "D03130": 100,
    "D0313F": 65,
    "D03240": 0,
    "D03450": 11,
    "D03451": 2,
    "D03180": 1,
    "D03182": 2,
    "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n",
    "aqit_ext": 0
}
```

**Comment by kongo09** [comment]
Sure, I can take a look. Can you please describe your device a bit? What settings does it have? How is it different from the CX5120?

**Comment by arashjalalat** [comment]
Great. I'm not aware of the features of CX5120, but in the Philips Air+ app I can see the following features for the CX3120/01:

- Actual temperature of the room
- Target temperature
- Auto(+), High, Medium, Low and Ventilation modes
- Timer function 
- Scheduler
- Oscillation
- Child lock, On or off

**Comment by kongo09** [comment]
If done a first beta now: v0.31.0-beta.1

Please let me know what works and what doesn't. Two things I already know won't work:
- Medium mode: can you please send me the `aioairctrl` readings with High, Medium and Low mode enabled, so that I can see which ones of the parameters change. Everything else unchanged please.
- Child lock: can you please send me two readings with child lock on an doff. Everything else unchanged please.

I have the feeling that Oscillation doesn't work either. Let's see. If so - well, you know the drill: readings with osciallation on and off please.

**Comment by arashjalalat** [comment]
Hello @kongo09. Amazing! I was able to add the new device with the integration. Power (on/off), Actual and target temperatures, Timer works.

Here are your requested modes:

high

```json
{"D01102": 3, "D01S03": "My Device", "D01S04": "Prometheus", "D01S05": "CX3120/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D0110C": 1, "D01S0D": "688001001670", "D0110F": 3, "D01S12": "0.3.7", "D01213": 0, "ProductId": "2f21b227facd11ee974e06d016384e4a", "DeviceId": "914ca6c6920711ef8aa3cb42fa086425", "otacheck": false, "Runtime": 2206052102, "rssi": -58, "wifilog": false, "blelog": -1, "free_memory": 155248, "WifiVersion": "AWS_Philips_AIR_Combo@6.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03103": 1, "D0310A": 3, "D0310C": 65, "D0310D": 3, "D0310E": 19, "D0320F": 45, "D03110": 0, "D03211": 0, "D03224": 206, "D0312A": 5, "D0312B": 5, "D03130": 100, "D0313F": 65, "D03240": 0, "D03450": 11, "D03451": 0, "D03180": 1, "D03182": 2, "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n", "aqit_ext": 0}
```

medium

```json
{"D01102": 3, "D01S03": "My Device", "D01S04": "Prometheus", "D01S05": "CX3120/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D0110C": 1, "D01S0D": "688001001670", "D0110F": 3, "D01S12": "0.3.7", "D01213": 0, "ProductId": "2f21b227facd11ee974e06d016384e4a", "DeviceId": "914ca6c6920711ef8aa3cb42fa086425", "otacheck": false, "Runtime": 2206079814, "rssi": -54, "wifilog": false, "blelog": -1, "free_memory": 155248, "WifiVersion": "AWS_Philips_AIR_Combo@6.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03103": 1, "D0310A": 3, "D0310C": 67, "D0310D": 2, "D0310E": 19, "D0320F": 45, "D03110": 0, "D03211": 0, "D03224": 216, "D0312A": 5, "D0312B": 5, "D03130": 100, "D0313F": 67, "D03240": 0, "D03450": 11, "D03451": 0, "D03180": 1, "D03182": 2, "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n", "aqit_ext": 0}
```

low

```json
{"D01102": 3, "D01S03": "My Device", "D01S04": "Prometheus", "D01S05": "CX3120/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D0110C": 1, "D01S0D": "688001001670", "D0110F": 3, "D01S12": "0.3.7", "D01213": 0, "ProductId": "2f21b227facd11ee974e06d016384e4a", "DeviceId": "914ca6c6920711ef8aa3cb42fa086425", "otacheck": false, "Runtime": 2206111800, "rssi": -58, "wifilog": false, "blelog": -1, "free_memory": 155440, "WifiVersion": "AWS_Philips_AIR_Combo@6.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03103": 1, "D0310A": 3, "D0310C": 66, "D0310D": 1, "D0310E": 19, "D0320F": 45, "D03110": 0, "D03211": 0, "D03224": 222, "D0312A": 5, "D0312B": 5, "D03130": 100, "D0313F": 66, "D03240": 0, "D03450": 11, "D03451": 0, "D03180": 1, "D03182": 2, "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n", "aqit_ext": 0}
```

auto+

```json
{"D01102": 3, "D01S03": "My Device", "D01S04": "Prometheus", "D01S05": "CX3120/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D0110C": 1, "D01S0D": "688001001670", "D0110F": 3, "D01S12": "0.3.7", "D01213": 0, "ProductId": "2f21b227facd11ee974e06d016384e4a", "DeviceId": "914ca6c6920711ef8aa3cb42fa086425", "otacheck": false, "Runtime": 2206179544, "rssi": -55, "wifilog": false, "blelog": -1, "free_memory": 155248, "WifiVersion": "AWS_Philips_AIR_Combo@6.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03103": 1, "D0310A": 3, "D0310C": 0, "D0310D": 3, "D0310E": 19, "D0320F": 45, "D03110": 0, "D03211": 0, "D03224": 224, "D0312A": 5, "D0312B": 5, "D03130": 100, "D0313F": 65, "D03240": 0, "D03450": 11, "D03451": 2, "D03180": 1, "D03182": 2, "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n", "aqit_ext": 0}
```

child lock off

```json
{"D01102": 3, "D01S03": "My Device", "D01S04": "Prometheus", "D01S05": "CX3120/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D0110C": 1, "D01S0D": "688001001670", "D0110F": 3, "D01S12": "0.3.7", "D01213": 0, "ProductId": "2f21b227facd11ee974e06d016384e4a", "DeviceId": "914ca6c6920711ef8aa3cb42fa086425", "otacheck": false, "Runtime": 2206211508, "rssi": -59, "wifilog": false, "blelog": -1, "free_memory": 155248, "WifiVersion": "AWS_Philips_AIR_Combo@6.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03103": 0, "D0310A": 3, "D0310C": 0, "D0310D": 3, "D0310E": 19, "D0320F": 45, "D03110": 0, "D03211": 0, "D03224": 230, "D0312A": 5, "D0312B": 5, "D03130": 100, "D0313F": 65, "D03240": 0, "D03450": 11, "D03451": 2, "D03180": 1, "D03182": 2, "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n", "aqit_ext": 0}
```

child lock on

```json
{"D01102": 3, "D01S03": "My Device", "D01S04": "Prometheus", "D01S05": "CX3120/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D0110C": 1, "D01S0D": "688001001670", "D0110F": 3, "D01S12": "0.3.7", "D01213": 0, "ProductId": "2f21b227facd11ee974e06d016384e4a", "DeviceId": "914ca6c6920711ef8aa3cb42fa086425", "otacheck": false, "Runtime": 2206241218, "rssi": -60, "wifilog": false, "blelog": -1, "free_memory": 155248, "WifiVersion": "AWS_Philips_AIR_Combo@6.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03103": 1, "D0310A": 3, "D0310C": 0, "D0310D": 3, "D0310E": 19, "D0320F": 45, "D03110": 0, "D03211": 0, "D03224": 232, "D0312A": 5, "D0312B": 5, "D03130": 100, "D0313F": 65, "D03240": 0, "D03450": 11, "D03451": 2, "D03180": 1, "D03182": 2, "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n", "aqit_ext": 0}
```

osc on

```json
{"D01102": 3, "D01S03": "My Device", "D01S04": "Prometheus", "D01S05": "CX3120/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D0110C": 1, "D01S0D": "688001001670", "D0110F": 3, "D01S12": "0.3.7", "D01213": 0, "ProductId": "2f21b227facd11ee974e06d016384e4a", "DeviceId": "914ca6c6920711ef8aa3cb42fa086425", "otacheck": false, "Runtime": 2206998274, "rssi": -56, "wifilog": false, "blelog": -1, "free_memory": 153680, "WifiVersion": "AWS_Philips_AIR_Combo@6.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03103": 1, "D0310A": 3, "D0310C": 0, "D0310D": 3, "D0310E": 19, "D0320F": 45, "D03110": 0, "D03211": 0, "D03224": 214, "D0312A": 5, "D0312B": 5, "D03130": 100, "D0313F": 65, "D03240": 0, "D03450": 11, "D03451": 2, "D03180": 1, "D03182": 2, "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n", "aqit_ext": 0}
```

osc off

```json
{"D01102": 3, "D01S03": "My Device", "D01S04": "Prometheus", "D01S05": "CX3120/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D0110C": 1, "D01S0D": "688001001670", "D0110F": 3, "D01S12": "0.3.7", "D01213": 0, "ProductId": "2f21b227facd11ee974e06d016384e4a", "DeviceId": "914ca6c6920711ef8aa3cb42fa086425", "otacheck": false, "Runtime": 2207020890, "rssi": -59, "wifilog": false, "blelog": -1, "free_memory": 153872, "WifiVersion": "AWS_Philips_AIR_Combo@6.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03103": 1, "D0310A": 3, "D0310C": 0, "D0310D": 3, "D0310E": 19, "D0320F": 0, "D03110": 0, "D03211": 0, "D03224": 209, "D0312A": 5, "D0312B": 5, "D03130": 100, "D0313F": 65, "D03240": 0, "D03450": 11, "D03451": 2, "D03180": 1, "D03182": 2, "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n", "aqit_ext": 0}
```

**Comment by kongo09** [comment]
Thanks for the parameters, very helpful! Please try the new beta v0.31.0-beta.2

I didn't ask you for the ventilation mode - does that work? If not, I would need some readings for that as well, please.

Oscillation seems to be different for this device from all others. I'm curious if that works.

Anything else that's missing?

**Comment by arashjalalat** [comment]
Your welcome! I did test the new version. However, I noticed some issues.

When the preset mode is Low as you can see in the screenshot, the visual is set to High. The actual behaviour of the device in this case is Low. This applies also to the High preset mode, where the visual shows Low and the actual behaviour of the device is High. Furthermore I think I'm missing the Auto(+) mode right?

Unfortunately the Oscillation mode isn't working for me. When setting it to on or off it doesn't do anything.

<img width="619" alt="image" src="https://github.com/user-attachments/assets/8c314762-5145-4479-b214-f4d5ce7bdb2c">

Ventilation mode

```json
{"D01102": 3, "D01S03": "My Device", "D01S04": "Prometheus", "D01S05": "CX3120/01", "D01107": 0, "D01108": 3, "D01109": 3, "D0110A": 0, "D0110B": 1, "D0110C": 1, "D01S0D": "688001001670", "D0110F": 3, "D01S12": "0.3.7", "D01213": 0, "ProductId": "2f21b227facd11ee974e06d016384e4a", "DeviceId": "914ca6c6920711ef8aa3cb42fa086425", "otacheck": false, "Runtime": 2242974442, "rssi": -64, "wifilog": false, "blelog": -1, "free_memory": 154752, "WifiVersion": "AWS_Philips_AIR_Combo@6.2", "StatusType": "status", "ConnectType": "Online", "D03102": 1, "D03103": 1, "D0310A": 1, "D0310C": -127, "D0310D": 4, "D0310E": 19, "D0320F": 0, "D03110": 0, "D03211": 0, "D03224": 195, "D0312A": 5, "D0312B": 5, "D03130": 100, "D0313F": 0, "D03240": 0, "D03450": 11, "D03451": 0, "D03180": 1, "D03182": 2, "D03R81": "FQAAAAAAAAAABv/EQv/YQv/sQv/2QQAKQQBu8A==\n", "aqit_ext": 0}
```

**Comment by kongo09** [comment]
That's very strange. The settings are the same inside the code. I struggle to see what happens?

If you use the visual speed settings and click from off to low to medium to high, does the fan do the right thing?

Can you also show me the expanded preset mode box? It should have Auto+ mode there?

Does Ventilation mode show in the presets and does it work?

Maybe, what is confusing, is that the preset modes have more settings than the visual. The reason for that is, that the visuals are reserved for true speeds, while the preset mode has more options (like Auto+ and Ventilation). Unfortunately, that's how Home Assistant built the entity model.

Does the child lock work?

On Oscillation, is it at least possible to switch it off from the integration when you switched it on from your Air+ app before?

The weird thing with oscillation is, that at least other models require a special control value to be sent to the device, but that's not the value that the device actually reports when it is oscillating. The field seems to be `D0320F` which is similar to other devices. Your data above shows 45 for the switched-on oscillation. But sending 45 doesn't seem to enable it. In other situations like this, I got stuck. But for the CX5120 some users brute-force tried numbers until they found the correct one. You can read about it here: https://github.com/kongo09/philips-airpurifier-coap/issues/137#issuecomment-2227309879

Maybe you can also try to use powershell to find the right value to enable the swing?

Next beta: v0.31.0-beta.3

**Comment by arashjalalat** [comment]
If I use the visual settings and click from off, to low to medium and high then I noticed that low will result in High fan on the device.

Yes, the preset mode is working perfectly fine! I tried each setting (including Ventilation) and it's working correctly.

<img width="317" alt="image" src="https://github.com/user-attachments/assets/15e6c92f-996e-4c13-adfa-4e2cf210fed7">

I tried to test the Child lock on your latest beta, but I don't see a Child lock option. Is that correct?

Oscillation works! If I switch the Oscillation on and off the device is behaving correctly! Only if I change the Oscillation from the Air+ app the Oscillation mode is not reflecting directly in the integration in HA, but for me that's fine!

**Comment by kongo09** [comment]
I still don't understand why you would click high on preset and the fan goes to high, but then the visual shows low. Something must be wrong but I don't understand it.

Child lock should be an extra switch? 

When you switch the oscillation on from Air+, can you then run the aioairctrl and check the reading? Is it 45?

**Comment by kongo09** [comment]
try v0.31.0-beta.4

It should fix the child lock and I changed the oscillation logic so that it should work better, no matter what the Air+ app does.

I'm still lost with the modes.

**Comment by arashjalalat** [comment]
Hi, child lock is visible and works great, thanks. Oscillation works now both from integration and Air+ app. The reading for Osc. is indeed 45.

**Comment by kongo09** [comment]
So that leaves the modes?

So you say selecting the speeds in the preset leads to the correct behaviour of the device. But the blue UI is the wrong way around? 

Consequently, selecting the speeds in the blue UI leads to the wrong device behaviour.

So I need to flip low and high for the blue UI, but not for the presets?

**Comment by kongo09** [comment]
Oh, I think I have an idea what's going on. Will do a new release tomorrow.

**Comment by kongo09** [comment]
please try: v0.31.0-beta.5

**Comment by kongo09** [comment]
I'm pretty sure with the latest changes everything works. I'll stick this now into the next release. Let me know if there is still something non-functional or missing.

If you like my work, you can support me by [buying a coffee]([buymeacoffee.com/kongo09](https://buymeacoffee.com/kongo09)).

**Comment by arashjalalat** [comment]
Sure, just did! ☕️
