### ISSUE TITLE
Support for Philips 800i (AC0850/70)

### ISSUE THREAD

**Issue by poebae** [kongo09/philips-airpurifier-coap#224]
Error is "Device not supported'.

I see [here](https://github.com/kongo09/philips-airpurifier-coap/issues/85) that the AC0850/70 is supposed to be supported, so I'm not sure if something else is different.

Running v0.32.0 of the integration and Home Assistant 2024.12.1

This is the product: https://www.amazon.com.au/dp/B0BCHY5P76?ref_=pe_19115062_429603572_302_E_DDE_dt_1

`Logger: custom_components.philips_airpurifier_coap.config_flow
Source: custom_components/philips_airpurifier_coap/config_flow.py:271
integration: Philips AirPurifier ([documentation](https://github.com/kongo09/philips-airpurifier-coap), [issues](https://github.com/kongo09/philips-airpurifier-coap/issues))
First occurred: 23:29:47 (2 occurrences)
Last logged: 23:34:02
Model AC0850/70 of family AC0850 not supported in user discovery`

**Comment by kongo09** [comment]
This device is a tricky one. Can you send me the output of aioairctrl as described in the readme

**Comment by kongo09** [comment]
Please try v0.34.0-beta.1 and let me know if it works.

**Comment by poebae** [comment]
It works! Thanks a lot 👍

Super impressed by the quick turnaround. I didn't even get a chance to try out the aioairctrl thing!

![image](https://github.com/user-attachments/assets/a61e4ccc-4dda-42ab-a8c6-00151afd6787)
![image](https://github.com/user-attachments/assets/bf90679f-e82b-42cc-a95e-df5d0b82aca2)

**Comment by kongo09** [comment]
Super cool, great, I had a feeling what the setup might be, so it was worth a try. Glad it works.

I'll stick this into the next proper release. Feel free to use the beta until then. If you like my work, you can [buy me a coffee](https://buymeacoffee.com/kongo09).
