### ISSUE TITLE
CX3120 - Some entities are not detected

### ISSUE THREAD

**Issue by chasp152** [kongo09/philips-airpurifier-coap#228]
I recently bought a CX3120 and realized this evening that it was actually supported by your integration but some controls/entities are missing. Among them: 

- Oscillation ON/OFF 
![Screenshot_20241210-000513](https://github.com/user-attachments/assets/e07476d1-7fb0-4a04-ad3d-1ca4926829d4)

- Mode: Auto / High / Mid / Low / Airflow only (also in auto mode, it has a thermostat setting)
![Screenshot_20241210-000507](https://github.com/user-attachments/assets/bc70d0af-4662-4a94-ae0f-fac0d58319fc) 

I followed your instructions to get a - hopefully - complete json file: 
[Philips CX3120(1).json](https://github.com/user-attachments/files/18069069/Philips.CX3120.1.json)

Let me know if I can do anything else to help :)

**Comment by kongo09** [comment]
Hm, interesting. I thought I had it fully working!

I've just started to experiment to represent heaters as `climate` entity. But I also currently show a `fan` entity that pretty much does the same thing. Can you please let me know what you see in HA?

**Comment by chasp152** [comment]
I just updated to 0.33 and now I can see all entities 🥳🥳 
What is odd (but not a big issue in itself) is that some features are there in multiple different places though: 
- mode: ![Screenshot_20241210-080432.png](https://github.com/user-attachments/assets/be7b895a-d6d8-4f04-8ce3-7e3a446163d3)

![Screenshot_20241210-080437.png](https://github.com/user-attachments/assets/60cd5940-f6f4-4d04-b037-b571b66e36b6)

- temperature shows as both a thermostat and a configuration: ![Screenshot_20241210-080459.png](https://github.com/user-attachments/assets/0d033414-f9df-438b-b3b9-4eef6f76e151)

- on/off shows as both a boolean switch and a thermostat

**Comment by kongo09** [comment]
Thank you, this is very helpful to see and understand. You see some things double as we're in transition to the new `climate` entity. That will change.

I notice that you lack icons for the preset mode. Can you please reload the frontend and see if they appear? If not, that's a bug.

Is everything working? Is anything missing?

**Comment by chasp152** [comment]
I tried it this weekend and it seemed to be working fine. I'll let you know if I spot anything 😊

**Comment by kongo09** [comment]
Great. I'll close this issue then.
