### ISSUE TITLE
Unclean shutdown of timer

### ISSUE THREAD

**Issue by kongo09** [kongo09/philips-airpurifier-coap#26]
Shutting down HA can lead to loads of error messages about the timer:

```
2022-05-03 13:06:08 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.timer] Starting Timer 180s.
2022-05-03 13:06:08 ERROR (MainThread) [custom_components.philips_airpurifier_coap.timer] Timer callback failure
Traceback (most recent call last):
  File "/workspaces/core/config/custom_components/philips_airpurifier_coap/timer.py", line 25, in _job
    await asyncio.sleep(self._timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 645, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
```

**Comment by kongo09** [comment]
@mhetzi have you seen that before?

**Comment by mhetzi** [comment]
sometimes but my homeassistant hangs so much on shutdown, that systemd is killing it.
(these hangs are not from this integration)

possibly connected with [issue on async_unload_entry](https://github.com/home-assistant/core/issues/61479)?

**Comment by kongo09** [comment]
https://github.com/kongo09/philips-airpurifier-coap/issues/27#issuecomment-1117886563

**Comment by kongo09** [comment]
I'll put some logging into the unloading. Is there a way to stop the timer process before it can run into this exception?

**Comment by user897943** [comment]
![Screenshot_20220513-064921](https://user-images.githubusercontent.com/5891221/168391361-301a2ea3-f967-433f-95dd-29de00410a01.png)

Had to restart HA after updating an addon on HACS, after like 10 minutes I noticed my automations weren't running (sensors lights weren't triggering). Checked docker logs, saw this... Please make this a priority, it should not make a restart hang ever, thank you, and by the way I love that you took ownership of this integration, you've done a great job!
