### ISSUE TITLE
Support for AC3036/10

### ISSUE THREAD

**Issue by jaqb** [kongo09/philips-airpurifier-coap#3]
Can you add support for AC3036 ? It's the same as AC3033 and AC3039. Same purifiers just different color/style.

**Comment by kongo09** [comment]
Great, should be easy. I'll look into this.

**Comment by Denaun** [comment]
Hi!
First of all, thank you @kongo09  for all your work 😄

This is the same model I have been using (and still use) to test on my fork. As @jaqb said, it really is the same as AC3033 aside from what it returns for `model` and `modelid`, which means it could be enough to add a const for `MODEL_AC3036 = "AC3036"` and map it to `PhilipsAC3033` in `model_to_class`.
I didn't realize the AC3039 is also the same, so I guess it would make sense to refactor them, either by sharing the same definition or by keeping all 3 of them as separate classes in case some difference pops up in the future, your choice.

I would do that but I have only limited access to my workspace at the moment. Still, please let me know if you need help.

Cheers!

**Comment by kongo09** [comment]
Hi @Denaun , the thanks goes to you. I've just extended your work! And actually, I'm learning as I do this, so I'm very grateful for advice and support!

I thought about doing a AC303x base class in case more models of that series pop up.

**Comment by kongo09** [comment]
@jaqb please try new beta v0.9.2-beta.1

**Comment by jaqb** [comment]
tbh I have already modified the files locally and it worked. but now I have also installed this beta and it still works. So thank you very much !

**Comment by kongo09** [comment]
thanks for testing!
