### ISSUE TITLE
Please add AC3055

### ISSUE THREAD

**Issue by eugenedani** [kongo09/philips-airpurifier-coap#30]
Hello,
Please add AC3055. It is the same as AC3059 but just smaller size.
I could setup AC3059 in yaml file for my AC3055 when I use  betaboon repository, but because here it is not in list of models I cannot add this integration. I receive "Model unsupported" error message despite the fact that it is the same as AC3059

**Comment by kongo09** [comment]
released new version `v0.10.1`
