### ISSUE TITLE
The status of the device does not change

### ISSUE THREAD

**Issue by pxuxmxa** [kongo09/philips-airpurifier-coap#38]
After updating v0.10.7, the problem returned, the status of the device a HA does not change.
For example: I turn off the light. Everything turns off on the device, but in HA the status is ON. In version 0.10.6, there was such a problem after rebooting ON. But after 180 seconds there was a reconnection and after that everything worked correctly

**Comment by kongo09** [comment]
Can you please downgrade and see if the problem disappears?

I worry that this is the connectivity problem and that it's just bad luck when it happens, not matter which version you are using.

**Comment by pxuxmxa** [comment]
@kongo09 
0.10.6 works but incorrectly. After restarting HA, I try to turn on the light. The light turns on but the status is off. After 180s, reconnection occurs and the status becomes correct (video 3:40) After that there are no problems. The connection is no longer lost. The problem is only after restarting HA
[home-assistant_0.10.7.log](https://github.com/kongo09/philips-airpurifier-coap/files/8698949/home-assistant_0.10.7.log)
[home-assistant_0.10.6.log](https://github.com/kongo09/philips-airpurifier-coap/files/8698950/home-assistant_0.10.6.log)
https://user-images.githubusercontent.com/86417742/168566404-ee635f26-a8af-426f-ba97-dc62dab7d321.mp4

**Comment by kongo09** [comment]
I'm not really convinced that the two versions make a difference here. The changes from v0.10.6 to v0.10.7 are minor and shouldn't affect turning on the light at all. My hypothesis is that this is coincidence and you might as well get it running with v0.10.7 and not running with v0.10.6. Maybe you try a few times with both versions and let me know if I'm right or not.

In the end, this might lead to the well-known connectivity problem, for which we don't really have a solution so far.

**Comment by pxuxmxa** [comment]
0.10.7 has been installed for several hours. And it didn't work.
0.10.6 does not work only the first 180s after restarting HA. There is a message in the log. After it, everything works correctly
_2022-05-18 13:06:36 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.timer] Starting Timer 180s.
2022-05-18 13:06:36 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.philips] Reconnecting_
Next following "Starting Time 180s." does not result in Reconnecting.
Log for several days. Reconnecting only after restarting HA.
[home-assistant.zip](https://github.com/kongo09/philips-airpurifier-coap/files/8748240/home-assistant.6.zip)
It turns out that a mandatory reconnection is required after the restart HA
You have added a new condition "RuntimeError", perhaps because of it, reconnection does not occur
I will set 0.10.7 for a longer period and analyze the logs.

**Comment by kongo09** [comment]
If you can propose a pull request to fix it, I would be more than grateful

**Comment by pxuxmxa** [comment]
@kongo09
I can't run the project in IntelliJ IDEA :( At startup, I installed the aioairctrl and homeassistant packages. Is there anything else required to run? Can you tell me what the problem is?

`C:\Users\pxuxmxa\AppData\Local\Programs\Python\Python38\python.exe C:\Users\pxuxmxa\AppData\Roaming\JetBrains\IdeaIC2022.1\plugins\python-ce\helpers\pydev\pydevd.py --cmd-line --multiprocess --qt-support=auto --client 127.0.0.1 --port 52832 --file D:/Distrib/Instal/git/philips-airpurifier-coap/philips-airpurifier-coap/custom_components/philips_airpurifier_coap/__init__.py
Traceback (most recent call last):
  File "C:\Users\pxuxmxa\AppData\Roaming\JetBrains\IdeaIC2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 16, in <module>
    from _pydevd_bundle.pydevd_collect_try_except_info import collect_return_info
  File "C:\Users\pxuxmxa\AppData\Roaming\JetBrains\IdeaIC2022.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_collect_try_except_info.py", line 12, in <module>
    from _pydevd_bundle.pydevd_constants import IS_PY38_OR_GREATER
  File "C:\Users\pxuxmxa\AppData\Roaming\JetBrains\IdeaIC2022.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_constants.py", line 222, in <module>
    from _pydev_imps._pydev_saved_modules import thread
  File "C:\Users\pxuxmxa\AppData\Roaming\JetBrains\IdeaIC2022.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_saved_modules.py", line 8, in <module>
    import socket
  File "C:\Users\pxuxmxa\AppData\Local\Programs\Python\Python38\lib\socket.py", line 52, in <module>
    import os, sys, io, selectors
  File "C:\Users\pxuxmxa\AppData\Local\Programs\Python\Python38\lib\selectors.py", line 12, in <module>
    import select
  File "D:\Distrib\Instal\git\philips-airpurifier-coap\philips-airpurifier-coap\custom_components\philips_airpurifier_coap\select.py", line 9, in <module>
    from homeassistant.components.select import SelectEntity
  File "C:\Users\pxuxmxa\AppData\Local\Programs\Python\Python38\lib\site-packages\homeassistant\components\__init__.py", line 14, in <module>
    from homeassistant.core import HomeAssistant, split_entity_id
  File "C:\Users\pxuxmxa\AppData\Local\Programs\Python\Python38\lib\site-packages\homeassistant\core.py", line 28, in <module>
    from homeassistant import async_timeout_backcompat, block_async_io, loader, util
  File "C:\Users\pxuxmxa\AppData\Local\Programs\Python\Python38\lib\site-packages\homeassistant\block_async_io.py", line 2, in <module>
    from http.client import HTTPConnection
  File "C:\Users\pxuxmxa\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 768, in <module>
    class HTTPConnection:
  File "C:\Users\pxuxmxa\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 816, in HTTPConnection
    def __init__(self, host, port=None, timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
AttributeError: partially initialized module 'socket' has no attribute '_GLOBAL_DEFAULT_TIMEOUT' (most likely due to a circular import)

Process finished with exit code 1`

**Comment by pxuxmxa** [comment]
@mhetzi
Due to the addition of the condition, the device status stopped being displayed correctly for me. Previously, 180c after the HA reboot, the status was displayed correctly. Now even after 180 the status is incorrect. Need help :) If the condition is removed, everything will work again

```
            except RuntimeError:
                try:
                    #Ensure that the runtime error, is because hass is going down!
                    asyncio.get_running_loop()
                except RuntimeError:
                    #Yes seems like hass is going down, stepping out
                    _LOGGER.warning("RuntimeError! Stopping Timer...")
                    self._auto_restart = False
                    self._task = None
                    return
```

**Comment by mhetzi** [comment]
@pxuxmxa could you test this. Sorry didnt notice this error. Device is mostly in standby when its warm outside.

**Comment by pxuxmxa** [comment]
@mhetzi 
The problem that the first 180c statuses do not change, remains. But after that everything works correctly. It suits me as it is. Thank you:)

**Comment by kongo09** [comment]
Thanks, I'll merge it later then

**Comment by kongo09** [comment]
`v0.10.8` released. I'll close this then, ok?
