### ISSUE TITLE
error code list?

### ISSUE THREAD

**Issue by tebra-jl** [kongo09/philips-airpurifier-coap#4]
Thanks for this new version of integration for Philips air purifier.
I wonder if there is somewhere a list of Philips error code with meaning.
It will be useful for automations

**Comment by kongo09** [comment]
betaboon "in the old days" collected a few error codes and they're in the code together with their meaning. But I've never seen a comprehensive list.

**Comment by kongo09** [comment]
https://github.com/kongo09/philips-airpurifier-coap/blob/58c25a2e0737723b853e918cd8a038832ed0da86/custom_components/philips_airpurifier_coap/const.py#L216

**Comment by tebra-jl** [comment]
If I find another one I will post it here.

**Comment by kongo09** [comment]
That's great, thanks. Just reopen this and I'll put it in.
