### ISSUE TITLE
older AC2889/10 not found

### ISSUE THREAD

**Issue by JoernBerkefeld** [kongo09/philips-airpurifier-coap#44]
i actually have 2 of these things. one bought years ago and one bought just a few months ago.

the "newer" model came with firmware `1.0.7` (wifi firmware AWS_Philips_AIR@69.1) and while it takes longer for that one to show up in their "CleanHome" app, it is found correctly by your integration.
the "older" model came with firmware `1.0.4` (wifi firmware 14) and cannot be found.

Via Alexa skill both are found and usable 

any suggestions?

**Comment by kongo09** [comment]
Maybe it does not work with encrypted CoAP then? Have you tried the command line tools from rgerganov?
https://github.com/rgerganov/py-air-control

**Comment by JoernBerkefeld** [comment]
uhm, tried running that but im not familiar with python code.
ended up with this always popping up:

![image](https://user-images.githubusercontent.com/1917227/176169952-3a150da9-2edf-4c99-a148-1c04cdc1bcdc.png)

--> im no good at debugging this

**Comment by JoernBerkefeld** [comment]
for **the older one** that does NOT work with your solution i got the following (`airctrl --ipaddr x.y.z.q` **no coap**):

![image](https://user-images.githubusercontent.com/1917227/176170188-406a694d-12c2-4b25-8be6-ea93bbfaf108.png)

when I tried adding `--protocol coap` or  `--protocol plain_coap` i got a nasty stack trace with either time-outs or connection denied errors.

----------------

UPDATE: had to install CoAPthon3 first... then **the new one** started working via `airctrl --ipaddr x.y.z.q --protocol coap`:
![image](https://user-images.githubusercontent.com/1917227/176172332-278c1bf9-b6e6-496b-b6be-f71727221299.png)


----

now while that's all weird to me, hopefully it gives you what you need to figure this out? or else, tell me how to continue testing

**Comment by kongo09** [comment]
That means the old one is definitely not supported

The new one however should work

**Comment by JoernBerkefeld** [comment]
ok, thank you. would you happen to know if there are other integrations that work with my old friend here? Doing that with Alexa is cool I suppose but would rather keep things in one system

**Comment by kongo09** [comment]
There are a number of integrations around but I don't really know what state they are in. None offers all the functionality of this one. So I feel, options are limited. I lack the time and motivation to integrate the older devices, but if someone does a pull request, I'd be more than happy to consider that.
