### ISSUE TITLE
Model support for AC4558/31

### ISSUE THREAD

**Issue by ronald-chun** [kongo09/philips-airpurifier-coap#45]
Hello, thank you for developing this awesome integration for HA
I hope you can support my device model AC4558/31 in the future.
Thanks a lot!!

```
{
  "name": "My Device",
  "type": "AC4558",
  "modelid": "AC4558/31",
  "swversion": "1.0.3",
  "range": "O2",
  "Runtime": 49633219,
  "rssi": -19,
  "wifilog": false,
  "free_memory": 51216,
  "WifiVersion": "AWS_Philips_AIR@69.1",
  "ProductId": "xxx",
  "DeviceId": "xxx",
  "StatusType": "status",
  "ConnectType": "Online",
  "om": "a",
  "pwr": "1",
  "cl": false,
  "aqil": "1",
  "uil": "1",
  "mode": "AG",
  "pm25": 2,
  "iaql": 1,
  "aqit": 7,
  "aqit_ext": 9,
  "tvoc": 4,
  "ddp": "1",
  "rddp": "1",
  "err": 0,
  "fltt1": "A3",
  "fltt2": "none",
  "fltsts0": 215,
  "fltsts1": 4290,
  "fltsts2": 0
}

**Comment by kongo09** [comment]
I'm happy to take a look at this, but probably not over the holidays.

**Comment by kongo09** [comment]
I've started to look into supporting this model. The device seems to have two special modes that other devices don't have, the auto gas mode and the auto pollution mode. Can you please help by posting the values of `mode` and `om` for the following settings:
- general auto mode
- auto gas mode
- auto pollution mode
- auto allergen mode

plus
- sleep mode
- speed 1
- speed 2
- turbo

As far as I understand, these should be all the settings, correct? I would only expect `mode` and `om` to change from one setting to another.

**Comment by ronald-chun** [comment]
Sorry for the late reply. 
The following are the values of `mode` and `om` in all the different settings:
```
// general auto mode + sleep
{
    "mode": "AG",
    "om": "s",
}
// general auto mode + speed 1
{
    "mode": "AG",
    "om": "1",
}
// general auto mode + speed 2
{
    "mode": "AG",
    "om": "2",
}
// general auto mode + turbo
{
    "mode": "AG",
    "om": "t",
}


// auto gas mode + sleep
{
    "mode": "F",
    "om": "s",
}
// auto gas mode + speed 1
{
    "mode": "F",
    "om": "1",
}
// auto gas mode + speed 2
{
    "mode": "F",
    "om": "2",
}
// auto gas mode + turbo
{
    "mode": "F",
    "om": "t",
}


// auto pollution mode + sleep
{
    "mode": "P",
    "om": "s",
}
// auto pollution mode + speed 1
{
    "mode": "P",
    "om": "1",
}
// auto pollution mode + speed 2
{
    "mode": "P",
    "om": "2",
}
// auto pollution mode + turbo
{
    "mode": "P",
    "om": "t",
}


// auto allergen mode + sleep
{
    "mode": "A",
    "om": "s",
}
// auto allergen mode + speed 1
{
    "mode": "A",
    "om": "1",
}
// auto allergen mode + speed 2
{
    "mode": "A",
    "om": "2",
}
// auto allergen mode + turbo
{
    "mode": "A",
    "om": "t",
}
```

**Comment by kongo09** [comment]
Please try the new beta `v0.11.0-beta4558.1` and let me know if it works

**Comment by ronald-chun** [comment]
Tested on `v0.11.0-beta4558.1`, the on/off, speed and the Preset mode auto & gas are working perfectly.
But for the Preset Mode pollution and allergen, I cannot change to these 2 modes in the dropdown

**Comment by kongo09** [comment]
What do you mean?

- The modes are not displayed so you cannot select them
- or they are displayed but greyed out
- or they are displayed normally but when you select them, nothing happens

**Comment by ronald-chun** [comment]
This one
- or they are displayed normally but when you select them, nothing happens

The other modes and speed slider will have a beep sound and reflect in the Philips app (Clean Home+) immediately after I do the changes

But the pollution and allergen mode does not have any beep sound and nothing happened in the Philips app

**Comment by kongo09** [comment]
That's interesting. So it seems that setting `mode` alone is not enough. When you observe the parameters as above, does anything else change?

Alternatively, I could try set `om` as well, even if it is the same value that is set already. Maybe that makes it work...

**Comment by ronald-chun** [comment]
I think all the modes should be together with the `om: "a"`

I tried the following steps:
1. change to "pollution" mode in the app
2. get the status by using aioairctrl, 
```
{
...
"mode": "P", 
"om": "a",
...
}
```
3. change to speed 1 in the app
4. get the status by using aioairctrl, 
```
{
...
"mode": "P", 
"om": "1",
...
}
```
5. change to "pollution" mode again in the app
6. get the status by using aioairctrl, 
```
{
...
"mode": "P", 
"om": "a",
...
}
```

I double-checked the status in all four modes, and all of them have the same behaviour

**Comment by kongo09** [comment]
try `v0.11.0-beta4558.2`

What happens to your speed setting when you now select a preset?

**Comment by kongo09** [comment]
@ronald-chun does the beta work for you?

**Comment by ronald-chun** [comment]
Sorry for the late reply
The pollution mode is still not working
And for the allergen mode, it works sometimes and it doesn't work sometimes. I am still trying any of the working patterns/combinations with speed.

**Comment by kongo09** [comment]
any update on this? Maybe it helps if things are switched in a certain order. Or the device is simply as unreliable as many other Philips devices.

**Comment by kongo09** [comment]
Here comes another attempt. Please try [v0.11.0-beta4558.3](https://github.com/kongo09/philips-airpurifier-coap/releases/tag/v0.11.0-beta4558.3)

**Comment by kongo09** [comment]
any luck with the latest beta?

**Comment by ronald-chun** [comment]
I tried the version v0.11.0-beta4558.3 
but still cannot change the mode the Pollution
Except for this, all modes and speed look good

**Comment by kongo09** [comment]
I've just done a new release that should fix the pollution mode. Please try.
