### ISSUE TITLE
Stopped working since 2022.8.2

### ISSUE THREAD

**Issue by Xitro01** [kongo09/philips-airpurifier-coap#46]
Hi,

Your integration was working flawlessly, but since the last update of HA (2022.8.2) the integration stopped working.
I'm getting the following error message from the integration page: [Errno 113] received through errqueue

**Comment by kongo09** [comment]
Will check once back from holidays. Any idea what that means?

**Comment by Xitro01** [comment]
Not really, my logs say the following:

```
Logger: homeassistant.config_entries
Source: config_entries.py:1067
First occurred: 08:56:53 (1 occurrences)
Last logged: 08:56:53

Config entry 'AC3829 Woonkamer' for philips_airpurifier_coap integration not ready yet: [Errno 113] received through errqueue; Retrying in background
```

Looking at the changes that they made, I can't really find anything that could be the issue.

**Comment by Xitro01** [comment]
Nevermind, resetting the device completely solved it for me. Something messed up my device somehow.

Thanks anyway!
