### ISSUE TITLE
Support for AC2959 and AC4550.

### ISSUE THREAD

**Issue by puffer-duck** [kongo09/philips-airpurifier-coap#54]
They seem to be exactly the same as already supported models:

AC4550 is same as AC4558.
AC2959 is same as AC2958.

**Comment by kongo09** [comment]
The AC4558 still seems to have problems, see #45 

I've done a beta for both models. Can you please let me know in detail what works and what doesn't. If something doesn't work, I would need the debug log to figure out what is going on.

Try beta `v0.11.0-beta2959-beta4550.1`

**Comment by puffer-duck** [comment]
AC4550 is connected, there is a minor glitch - turning off light works, turning on doesn't, it just lights up for a few seconds. ` turned off triggered by service light.turn_off` - when turning off. And no message when attempting turning on. Other than that - seems working fine.

AC2959 times out when attempting to add it. Actually when I was trying it on stable, I had same situation - AC4550 failed with wrong model, AC2959 timed out.

**Comment by kongo09** [comment]
Thanks for the feedback. I'd like to understand the light problem better. Can you please enable debug logging and share the log when you turn the light off and on?

The AC2959 might suffer from the same connectivity problem like so many devices. I'll leave it in the code nevertheless. Maybe other people will have more luck and report back if it works or not. One way to address the connectivity problem is a power cycle of the device. Did you try that?

**Comment by kongo09** [comment]
Can you also for the AC4550 see if the pollution mode works, please?

**Comment by puffer-duck** [comment]
> One way to address the connectivity problem is a power cycle of the device. Did you try that?

Unfortunately this is not helping.

**Comment by puffer-duck** [comment]
> Thanks for the feedback. I'd like to understand the light problem better. Can you please enable debug logging and share the log when you turn the light off and on?

Is it the one in Logbook or is it somewhere else?




> Can you also for the AC4550 see if the pollution mode works, please?

Unfortunately no - Auto mode and Pollution mode do nothing. Gas and Allergen works, setting speed manually works too.

**Comment by kongo09** [comment]
> Is it the one in Logbook or is it somewhere else?

It is the logging as described in the readme

**Comment by puffer-duck** [comment]
[home-assistant.log](https://github.com/kongo09/philips-airpurifier-coap/files/10202646/home-assistant.log)

I rebooted to make it smaller - right after LED was off. I turned it on, then off, then on. Copied file right after.

**Comment by kongo09** [comment]
pollution mode should be fixed in `v0.11.4-beta2959-beta4550.2` - please try

**Comment by kongo09** [comment]
It might be that the models are actually not identical. The AC4558 seems to be working fine now, so if the AC4550 is not, then there must be a difference.

Are you familiar with typing a few commands on the command line interface? If so, could you try to follow the description https://github.com/kongo09/philips-airpurifier-coap#is-your-model-not-supported-yet and acquire some raw data of your device, especially while switching the modes and turning on and off the lights?

**Comment by puffer-duck** [comment]
@kongo09 Sure, I can get raw data, just had a few missiles destroy my energy grid, so had no power to test it. Will do after new year. Happy holidays!

**Comment by kongo09** [comment]
Oh, are you telling me, you're in Ukraine?

**Comment by alineary** [comment]
Hi! Stumbled across this issue as I was trying to add my AC4550 to Homeassistant. I can provide the raw data.
```json
{
   "name":"Bedroom",
   "type":"AC4550",
   "modelid":"AC4550/10",
   "swversion":"1.0.1",
   "range":"O2",
   "Runtime":1521634,
   "rssi":-50,
   "otacheck":false,
   "wifilog":false,
   "free_memory":49072,
   "WifiVersion":"AWS_Philips_AIR@73.1",
   "ProductId":"90bbfb7ae62611e8a1e3061302926720",
   "DeviceId":"1dd61c283fb611e9a1e3061302926720",
   "StatusType":"status",
   "ConnectType":"Online",
   "om":"1",
   "pwr":"1",
   "cl":false,
   "aqil":"1",
   "uil":"1",
   "mode":"A",
   "pm25":2,
   "iaql":1,
   "aqit":4,
   "aqit_ext":0,
   "tvoc":1,
   "ddp":"0",
   "rddp":"0",
   "err":0,
   "fltt1":"A5",
   "fltt2":"C7",
   "fltsts0":169,
   "fltsts1":9648,
   "fltsts2":4248
}
```

I was able to integrate the device into my Homeassistant just a while ago (end of last year). Worked okay, but a bit laggy, as is to be expected since the device was/is not yet supported. However, there seemed to be some issue and I had to set it up again. Now there is just a Popup during integration telling me that device is not supported. I hope my data helps as I am looking forward to automating my air purifier again! :) If there is any other way I can help just let me know. Greetings from Germany!

**Comment by kongo09** [comment]
Thanks for chiming in, I'll take a look at your data. It would be great if you can work with me to get this going.

**Comment by alineary** [comment]
@kongo09 I'm happy to help and test. :) 
Also: Here is the data when the light is turned off (it was turned on when I requested the other JSON from the air purifier). Might be useful to tackle that problem?
```json
{
   "name":"Bedroom",
   "type":"AC4550",
   "modelid":"AC4550/10",
   "swversion":"1.0.1",
   "range":"O2",
   "Runtime":10854261,
   "rssi":-60,
   "otacheck":false,
   "wifilog":false,
   "free_memory":48936,
   "WifiVersion":"AWS_Philips_AIR@73.1",
   "ProductId":"90bbfb7ae62611e8a1e3061302926720",
   "DeviceId":"1dd61c283fb611e9a1e3061302926720",
   "StatusType":"status",
   "ConnectType":"Online",
   "om":"a",
   "pwr":"1",
   "cl":false,
   "aqil":"0",
   "uil":"0",
   "mode":"AG",
   "pm25":1,
   "iaql":1,
   "aqit":4,
   "aqit_ext":0,
   "tvoc":1,
   "ddp":"0",
   "rddp":"0",
   "err":0,
   "fltt1":"A5",
   "fltt2":"C7",
   "fltsts0":166,
   "fltsts1":9646,
   "fltsts2":4246
}
```

**Comment by kongo09** [comment]
I took a look at your parameters. The fields for the light are `uil` and `aqil`. You can see how they go from `1` to `0` when you switched off the light. That's exactly what the integration is doing, so can you please clarify: is the light setting working for you or not?

I've done a new beta based on the latest code, so please try `v0.13.1-beta2959-beta4550.1` by enabling beta installs from HACS.

**Comment by kongo09** [comment]
I've also noted something else in the paramters you provided.

- In your first example, you have `om` = `1` and `mode` = `A`.
- In the second example, you have `om` = `a` and `mode` = `AG`.

Can you please clarify what mode your device was in? These settings differ from what I have in the code for the AC4550.

**Comment by alineary** [comment]
Hi! I have tried the Beta Version, and integrating my Air Purifier worked (as it previously did not). I have managed to turn off the light, however, it did not turn back on again. Same with the fan. Turning it off works, turning it back on does not. When triggering the light, my device makes a sound indicating that the light was toggled but it is not turning on. Trying to turn the fan back on does not trigger the fan-starting-sound.
Concerning the modes: I'm pretty sure I switched my device to automatic mode before requesting the second JSON, but I will make sure to provide the data for all modes as soon as possible. :)

**Comment by alineary** [comment]
I checked every mode. That automatic mode I was referring to the fan speed I think. :D 
Here comes the data!
## General Mode:
```json
{
   "name":"Bedroom",
   "type":"AC4550",
   "modelid":"AC4550/10",
   "swversion":"1.0.1",
   "range":"O2",
   "Runtime":82396167,
   "rssi":-50,
   "otacheck":false,
   "wifilog":false,
   "free_memory":52608,
   "WifiVersion":"AWS_Philips_AIR@73.1",
   "ProductId":"90bbfb7ae62611e8a1e3061302926720",
   "DeviceId":"1dd61c283fb611e9a1e3061302926720",
   "StatusType":"status",
   "ConnectType":"Online",
   "om":"a",
   "pwr":"1",
   "cl":false,
   "aqil":"1",
   "uil":"1",
   "mode":"AG",
   "pm25":7,
   "iaql":2,
   "aqit":4,
   "aqit_ext":0,
   "tvoc":1,
   "ddp":"0",
   "rddp":"2",
   "err":0,
   "fltt1":"A5",
   "fltt2":"C7",
   "fltsts0":149,
   "fltsts1":9628,
   "fltsts2":4228
}
```

## Allergen Mode:
```json
{
   "name":"Bedroom",
   "type":"AC4550",
   "modelid":"AC4550/10",
   "swversion":"1.0.1",
   "range":"O2",
   "Runtime":82766873,
   "rssi":-51,
   "otacheck":false,
   "wifilog":false,
   "free_memory":52608,
   "WifiVersion":"AWS_Philips_AIR@73.1",
   "ProductId":"90bbfb7ae62611e8a1e3061302926720",
   "DeviceId":"1dd61c283fb611e9a1e3061302926720",
   "StatusType":"status",
   "ConnectType":"Online",
   "om":"a",
   "pwr":"1",
   "cl":false,
   "aqil":"1",
   "uil":"1",
   "mode":"A",
   "pm25":8,
   "iaql":2,
   "aqit":4,
   "aqit_ext":0,
   "tvoc":1,
   "ddp":"0",
   "rddp":"0",
   "err":0,
   "fltt1":"A5",
   "fltt2":"C7",
   "fltsts0":148,
   "fltsts1":9628,
   "fltsts2":4228
}
```

## Gas Mode:
```json
{
   "name":"Bedroom",
   "type":"AC4550",
   "modelid":"AC4550/10",
   "swversion":"1.0.1",
   "range":"O2",
   "Runtime":82830392,
   "rssi":-54,
   "otacheck":false,
   "wifilog":false,
   "free_memory":49104,
   "WifiVersion":"AWS_Philips_AIR@73.1",
   "ProductId":"90bbfb7ae62611e8a1e3061302926720",
   "DeviceId":"1dd61c283fb611e9a1e3061302926720",
   "StatusType":"status",
   "ConnectType":"Online",
   "om":"a",
   "pwr":"1",
   "cl":false,
   "aqil":"1",
   "uil":"1",
   "mode":"F",
   "pm25":11,
   "iaql":3,
   "aqit":4,
   "aqit_ext":0,
   "tvoc":1,
   "ddp":"0",
   "rddp":"2",
   "err":0,
   "fltt1":"A5",
   "fltt2":"C7",
   "fltsts0":148,
   "fltsts1":9628,
   "fltsts2":4228
}
```

## Pollution Mode:
```json
{
   "name":"Bedroom",
   "type":"AC4550",
   "modelid":"AC4550/10",
   "swversion":"1.0.1",
   "range":"O2",
   "Runtime":82887760,
   "rssi":-56,
   "otacheck":false,
   "wifilog":false,
   "free_memory":49104,
   "WifiVersion":"AWS_Philips_AIR@73.1",
   "ProductId":"90bbfb7ae62611e8a1e3061302926720",
   "DeviceId":"1dd61c283fb611e9a1e3061302926720",
   "StatusType":"status",
   "ConnectType":"Online",
   "om":"a",
   "pwr":"1",
   "cl":false,
   "aqil":"1",
   "uil":"1",
   "mode":"P",
   "pm25":11,
   "iaql":3,
   "aqit":4,
   "aqit_ext":0,
   "tvoc":1,
   "ddp":"0",
   "rddp":"1",
   "err":0,
   "fltt1":"A5",
   "fltt2":"C7",
   "fltsts0":148,
   "fltsts1":9628,
   "fltsts2":4228
}
```

**Comment by kongo09** [comment]
Thanks. I've changed a few things now, please try `v0.13.1-beta2959-beta4550.2`

- child lock should be added
- modes should all work
- I've tried something with the light setting. Not sure if that fixes the problem, but let's see

**Comment by alineary** [comment]
Hi! I've tried the new beta. Switching between the modes works like a charm! The fan is also turning on and off as intended.
However, I've noticed the following:

- Child lock turns on but cannot be turned off again

- When turning the light back on, it lights up for 2 or 3 seconds and then turns off again. Also sometimes it doesn't react at all

- there seems to be a configuration for the lights brightness. The AC4550 does not support adjusting the brightness though. So that could be removed.

Greetings and have a nice week! :)

**Comment by kongo09** [comment]
Hm, this is a mystery. The child lock should switch from `true` to `false` to `true` just like for any other Philips device. From the data you provided, this looks identical here with `cl` turning to `false` if the child lock is switched off. I don't see a reason why that wouldn't work.

For the light, there should only be one switch and that shouldn't be dimmable. I'll change the code to try to fix it.

Please try `v0.13.1-beta2959-beta4550.3`

**Comment by alineary** [comment]
Hi! I've tried the new beta - the child lock works as intended now. However, it seems to have some influence on the light:

![child_lock](https://user-images.githubusercontent.com/85510512/234843672-6d0335f7-80bf-4016-906b-e16c2941750b.gif)

The light issue is the same as before, turns on for a little while before it decides to turn off again.

![light](https://user-images.githubusercontent.com/85510512/234843824-6b583170-179e-4538-b736-03c25eab94a9.gif)

The GIFs reflect the behavior that the actual device shows.

**Comment by kongo09** [comment]
Thanks for the animation.

I'm a bit irritated, that the light brightness is still there. Is that orphaned? I.e., if you remove the entity and then reinstall the integration, does it come back or is it gone?

For the light: I discovered with my own device that some auto modes like sleep have the light switched off. When I then change something, like the child lock, the light goes briefly on and then automatically off again. That's controlled by the device itself and also happens with the normal Philips app. So question: which mode are you in? Maybe this is a similar effect here?

**Comment by alineary** [comment]
Turns out that every time the child lock is toggled, the light turns on for a few seconds if it was deactivated beforehand - tried it out on the Philips app and on the device itself. So that works as intended, I just wasn't aware! :D
The Brightness entity is indeed orphaned and I removed it from my HA.
The light itself is still confusing though... Seems to behave the same way as if I was triggering the child lock (or touch any other button while the light is turned off, as it also turns on for a short while when i.e. changing the mode).

**Comment by kongo09** [comment]
The HA interface reflects the state of the device. So if the light briefly turns on, I would expect HA to briefly move the button on and then off again.

From what you write, it sounds like overall we have a working integration for your model?

**Comment by alineary** [comment]
Yes, indeed. Except for the light - which is not a big problem for me personally as I have the lights off all the time anyways.
However, I think we should keep that in mind as a known issue until an explanation is found.
Thank you for your work! :)

**Comment by kongo09** [comment]
But you said the light behaviour is the same as in the Philips app?

**Comment by alineary** [comment]
Well, yes, concerning the light turning on for a few seconds when changing a mode or the child lock, when the light is turned off.
The light button in the philips app turns the light on/off permanently, which is not the case in the integration.
I hope that clears up the confusion. :)

**Comment by kongo09** [comment]
So when you turn it off in the app, a mode change doesn't briefly turn it back on.

But when you turn it off in HA, a mode change briefly turns it back on?

**Comment by alineary** [comment]
No, the integration works perfectly fine in that case, as mode changes in the philips app as well as the integration turn on the light briefly.

However, the philips app can also permanently turn on the light.
The integration on the other hand makes it just light up for a few seconds, when using the "display backlight" switch to turn it on. It turns off again afterwards. This behavior is displayed in the gif I posted in the other comment.

**Comment by alineary** [comment]
The issue is not with the modes or child lock but with the light itself. :)

**Comment by kongo09** [comment]
Ah, now I understand. So the behaviour I know from my sleep mode, where it always goes off by itself again. But for you it is in every mode. Hm...

Back to when we had the second brightness switch in. Can you remember if that was moving as well by itself? Did it actually do anything at all? Maybe your device requires both settings to be set at the same time to be stable?

**Comment by alineary** [comment]
I don't think it did anything, but I'm not entirely sure. Do you still have a version with the dimming-switch up for download?

**Comment by 123paultje** [comment]
Hi Kongo09, thnx for this nice integration!
Since the last beta version the air_quality_index sensor is not updating anymore on ac4550

**Comment by jaal2001** [comment]
Hi, I updated to 0.15.0, but still receive "your model is not supported" for my model:
"type": "AC4550", "modelid": "AC4550/10", "swversion": "1.0.3"

Anything I can help here?
Switch on:
`{"name": "B\u00fcro", "type": "AC4550", "modelid": "AC4550/10", "swversion": "1.0.3", "range": "O2", "Runtime": 17222757, "rssi": -29, "otacheck": false, "wifilog": false, "free_memory": 57216, "WifiVersion": "AWS_Philips_AIR@73.1", "ProductId": "90bbfb7ae62611e8a1e3061302926720", "DeviceId": "67fef338e8af11ec9d217e0724522e16", "StatusType": "control", "ConnectType": "Online", "om": "a", "pwr": "1", "cl": false, "aqil": "1", "uil": "1", "mode": "AG", "pm25": 5, "iaql": 2, "aqit": 7, "aqit_ext": 0, "tvoc": 1, "ddp": "0", "rddp": "0", "err": 0, "fltt1": "A5", "fltt2": "C7", "fltsts0": 208, "fltsts1": 9687, "fltsts2": 4287}`

Activate sleep speed:
`{"name": "B\u00fcro", "type": "AC4550", "modelid": "AC4550/10", "swversion": "1.0.3", "range": "O2", "Runtime": 17245296, "rssi": -29, "otacheck": false, "wifilog": false, "free_memory": 57216, "WifiVersion": "AWS_Philips_AIR@73.1", "ProductId": "90bbfb7ae62611e8a1e3061302926720", "DeviceId": "67fef338e8af11ec9d217e0724522e16", "StatusType": "control", "ConnectType": "Online", "om": "1", "pwr": "1", "cl": false, "aqil": "1", "uil": "1", "mode": "AG", "pm25": 5, "iaql": 2, "aqit": 7, "aqit_ext": 0, "tvoc": 1, "ddp": "0", "rddp": "0", "err": 0, "fltt1": "A5", "fltt2": "C7", "fltsts0": 208, "fltsts1": 9687, "fltsts2": 4287}`

Switch to automatic mode:
`{"name": "B\u00fcro", "type": "AC4550", "modelid": "AC4550/10", "swversion": "1.0.3", "range": "O2", "Runtime": 17260431, "rssi": -29, "otacheck": false, "wifilog": false, "free_memory": 57304, "WifiVersion": "AWS_Philips_AIR@73.1", "ProductId": "90bbfb7ae62611e8a1e3061302926720", "DeviceId": "67fef338e8af11ec9d217e0724522e16", "StatusType": "control", "ConnectType": "Online", "om": "a", "pwr": "1", "cl": false, "aqil": "1", "uil": "1", "mode": "AG", "pm25": 5, "iaql": 2, "aqit": 7, "aqit_ext": 0, "tvoc": 1, "ddp": "0", "rddp": "0", "err": 0, "fltt1": "A5", "fltt2": "C7", "fltsts0": 208, "fltsts1": 9687, "fltsts2": 4287}`

**Comment by kongo09** [comment]
> updates to 0.15.0

The main version does not support the device yet, as we still have bugs. Please try the beta v0.13.1-beta2959-beta4550.3

**Comment by jaal2001** [comment]
Okay, with that version my AC4550 shows up, but my AC2889 seems not to be working anymore. 
Is it possible to merge the most recent version with AC4550 and AC2889 to a new beta?

**Comment by kongo09** [comment]
I've now put the AC4550 into the main version - the AC2959 was already there.

I know we discussed a lot about the two light switches. For now, I've put in both. Please observe how it goes. If it doesn't make sense, please let me know and I'll rework it to remove one. Until then, I'll close this issue.
