### ISSUE TITLE
AC2729 - Filter life no longer correctly reported

### ISSUE THREAD

**Issue by MsbS-pl** [kongo09/philips-airpurifier-coap#58]
After recent update of the Integration, the filter life attributes/entities to be no longer there.
In earlier versions, it was either a separate entity (such as  sensor.ac2729_filter_pre), or an attribute of the Purifier entity (e.g. states.fan.philips_ac2729.attributes.filter_pre_remaining_raw). Now, neither of the two seem to work.

**Comment by kongo09** [comment]
The names of the filters have changed. Please check on the device panel. This is my AC2729:

![Screenshot_20221211-123118](https://user-images.githubusercontent.com/640121/206901076-21c9713a-5479-4b19-aef4-0dca1c7f3663.png)
