### ISSUE TITLE
0.11.4 only initializes one fan - 0.11.3 works OK for both

### ISSUE THREAD

**Issue by chrissearle** [kongo09/philips-airpurifier-coap#61]
Just ran an update - including 0.11.3 to 0.11.4

After restart of HA only one fan initialized - the other was left in "initializing" (first fan is fine - second fan does not complete).

Tried several HA restarts and powercycled the fans. No help.

But - I then reverted to 0.11.3 and both fans were initialized after HA restart just fine.

Both are AC3033's.

Not sure what info would help give more insight here - I can bump back to 0.11.4 and check - but not seeing anything useful in the homeassistant.log file - so not sure where to look.

**Comment by kongo09** [comment]
That sounds more like the Philips connection problem than anything else. The only difference between 0.11.3 and 0.11.4 is a fix for AC4558. Everything else is the same:

https://github.com/kongo09/philips-airpurifier-coap/compare/v0.11.3...v0.11.4

I guess this is coincidence. Please go back to 0.11.4 and see if it works. Or stay with 0.11.3 for now, as it doesn't make any difference for the AC3033
