### ISSUE TITLE
[Suggestion only] Waking up the air purifiers

### ISSUE THREAD

**Issue by joe-sydney** [kongo09/philips-airpurifier-coap#62]
Hi Kongo09 - if you remember, we discussed how I was able to use node-red to wake up the air purifiers when the fan entities became unavailable or missing, using CLI commands. I believe this didn't work for you. In fact, I tried it with the branch of aioairctrl that you used and the method did not work... it works on an earlier fork which is what I've been using.

Recently with Google Assistant SDK integration, I was able to control (turn on and off) the air purifiers using HA. Perhaps you could try to see if this is able to wake up the air purifiers and get them connected to your integration again.

**Comment by kongo09** [comment]
Ah, you mean having them present on Google Assistant as well and then, once you find out that they don't respond, use Google Assistant to get them back alive? Hm, it contradicts a bit the point of keeping all communication local.

**Comment by joe-sydney** [comment]
Yes, that would require Philips Air be integrated with Google Assistant, but this integration doesn't need any direct integration other than to get HA to call the google_assistant_sdk.send_text_command service when the fan entity is unavailable or unknown.

**Comment by kongo09** [comment]
Yes, I get it. But I would not want to make this integration dependent on some other integration. I guess this could be addressed by a HA automation? Do you want to try to put something together as an automation blueprint? I could put that into the readme then?

**Comment by joe-sydney** [comment]
Yeah, is there a way for your integration to create a binary sensor and set that to "on" when the entity is unavailable or unknown or otherwise detected that the purifier needs to be woken up? e.g. binary_sensor.living_room_purifier_dead. The would be the extent of the integration. HA or node-red can pick it up from that, eg when that binary sensor is on (on event or by polling), then just call the service.

**Comment by kongo09** [comment]
Hm, that's not obvious. At least in my cases, the device sometimes simply doesn't respond to a command or stops updating. Or it keeps updating but stops answering to a command.

If you don't send a command, you wouldn't know it is gone.

Also, we would have to distinguish between the device being unresponsive and the user having unplugged the device.

**Comment by joe-sydney** [comment]
OK, in my current case using node-red, I don't distinguish as it doesn't matter that I send commands in either cases. The commands wouldnt get through if the purifier is off or disconnected. I poll every 2 minutes so it is not too frequent. Literally, I have had zero problems with my purifiers that needed manual intervention of any kind.

**Comment by joe-sydney** [comment]
Anyway, let me try your integration again - as I'd prefer to have an integration that has someone owning it instead of abandoned :)

Last time I tried it, it didn't work with the commands that I was sending the purifiers, but this time let me try with the google assistant sdk commands...
