### ISSUE TITLE
Support request for model AC3854

### ISSUE THREAD

**Issue by raulpetruta** [kongo09/philips-airpurifier-coap#66]
Hi! Congrats for your work! Hope that you can add support for this model in the future. 

### Power ON

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 757690
rssi | -44
otacheck | false
wifilog | false
free_memory | 49760
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 1
pwr | 1
cl | false
aqil | 100
uil | 1
uaset | A
mode | AG
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 1
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Power OFF

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1276129
rssi | -45
otacheck | false
wifilog | false
free_memory | 45096
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 0
pwr | 0
cl | false
aqil | 100
uil | 1
uaset | A
mode | AG
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Child Lock ON

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1410805
rssi | -45
otacheck | false
wifilog | false
free_memory | 45096
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 1
pwr | 1
cl | true
aqil | 100
uil | 1
uaset | A
mode | AG
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Child Lock OFF

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1669966
rssi | -44
otacheck | false
wifilog | false
free_memory | 45096
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 1
pwr | 1
cl | false
aqil | 100
uil | 1
uaset | A
mode | AG
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Light OFF

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1782568
rssi | -45
otacheck | false
wifilog | false
free_memory | 45096
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 1
pwr | 1
cl | false
aqil | 0
uil | 0
uaset | A
mode | AG
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Light ON

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1917408
rssi | -45
otacheck | false
wifilog | false
free_memory | 40504
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 1
pwr | 1
cl | false
aqil | 100
uil | 1
uaset | A
mode | AG
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Auto mode

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1917408
rssi | -45
otacheck | false
wifilog | false
free_memory | 40504
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 1
pwr | 1
cl | false
aqil | 100
uil | 1
uaset | A
mode | AG
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Turbo 1 

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1917408
rssi | -45
otacheck | false
wifilog | false
free_memory | 40504
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 1
pwr | 1
cl | false
aqil | 100
uil | 1
uaset | A
mode | M
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Turbo 2

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1917408
rssi | -45
otacheck | false
wifilog | false
free_memory | 40504
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 2
pwr | 1
cl | false
aqil | 100
uil | 1
uaset | A
mode | AG
pm25 | 2
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Turbo Mode

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1917408
rssi | -45
otacheck | false
wifilog | false
free_memory | 40504
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 2
pwr | 1
cl | false
aqil | 100
uil | 1
uaset | A
mode | T
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

### Sleep Mode

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1917408
rssi | -45
otacheck | false
wifilog | false
free_memory | 40504
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | 2
pwr | 1
cl | false
aqil | 100
uil | 1
uaset | A
mode | S
pm25 | 1
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535 

### Allergy sleep

Field | Value
-- | --
name | My Device
type | AC3854
modelid | AC3854/51
swversion | Ms4418
language | EN
DeviceVersion | 4.1.8
range | MarteHE
Runtime | 1917408
rssi | -45
otacheck | false
wifilog | false
free_memory | 40504
WifiVersion | AWS_Philips_AIR@75.3
ProductId | 3bdc0f96982b11eba5ae06f40e28facc
DeviceId | bf34ceaefc4411ecbb4a964fade38866
StatusType | control
ConnectType | Online
om | s
pwr | 1
cl | false
aqil | 100
uil | 1
uaset | A
mode | AS
pm25 | 2
iaql | 1
aqit | 4
aqit_ext | 0
tvoc | 1
ddp | 1
rddp | 1
err | 49153
D0311F | 0
D03180 | 0
D03R81 | 000000000
D03182 | 1
fltt1 | A3
fltt2 | none
fltsts0 | 0
fltsts1 | 3360
fltsts2 | 65535
filna | 0
filid | 0
flttotal0 | 720
flttotal1 | 4800
flttotal2 | 65535

Hope it helps.

**Comment by kongo09** [comment]
Thanks for the request and the data. This looks very doable. I'll create a beta for you to test, probably next weekend.

**Comment by raulpetruta** [comment]
Thanks! Looking forward to it.

**Comment by kongo09** [comment]
I've started to take a look at it. Checking the manual https://www.documents.philips.com/assets/20210512/2bd99bb2320a48adaf63ad2600c55656.pdf doesn't show a `allergy sleep` mode and also no two speed modes. Is that something you can only access via the Philips app?

**Comment by kongo09** [comment]
Please check beta `v0.11.6-ac3854.1` and let me know what works, what doesn't and what is missing.

**Comment by Gh61** [comment]
I believe AC3854 is the same as AC3858 (which I have) only has different front side.
There is also difference between /50 and /51, The 51 has 2 fan modes and also 2 sleep modes (classic sleep mode and allergy sleep mode, that can change the speed of the fan, when detects worse air quality).
Both these modes are available through the display of the device.

**Comment by kongo09** [comment]
Hm, interesting. The AC3858 is supported already but from the data above I see that the control codes are different. Maybe the difference is with `/50` vs `/51` which would be the first model where the series number makes a difference. Right now, the code pretty much ignores that.

So do you say that there is also an AC3858/51 with the two sleep modes?

**Comment by Gh61** [comment]
Yes, it is, but I don't really use the allergy sleep mode and the rest of modes are working fine.
Pic as a proof. Also as I've seen, the /51 model has slightly different buttons.
![IMG_20230318_002009](https://user-images.githubusercontent.com/10837736/226068768-7c79e509-3afa-4465-a0f6-3ce995f4fe66.jpg)

**Comment by kongo09** [comment]
So you have the 3858/51 but you say that integration works fine for you, even though it assumes a 3858/50?

Can you share the parameters for the different modes as above? Ideally, I can extend and distinguish the /50 from the /51

**Comment by Gh61** [comment]
Yes, it works without any problem (only the allergy sleep mode is missing).
OK I'll try to fetch parameters for all modes and post it here (maybe to another issue, so you don't have two things in one issue).
I'll look into it in one of the next few days.

**Comment by kongo09** [comment]
Great. The interesting bits are `om` and `mode`

**Comment by raulpetruta** [comment]
Hello! Sorry for late response. It works for me. I can't see the child lock and allergy sleep, but I don't use them anyway.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/57073371/226106484-5b2571d2-2c88-4e94-a6a2-e24f33111434.png">

**Comment by raulpetruta** [comment]
https://user-images.githubusercontent.com/57073371/226106718-6ff6cb9e-414b-4add-aff0-41afd7ae4561.MOV

**Comment by raulpetruta** [comment]
That's how my display looks like

**Comment by raulpetruta** [comment]
Update: I can see the allergy sleep in Preset Mode section. The only thing missing is child lock, but I never used that function

<img width="565" alt="image" src="https://user-images.githubusercontent.com/57073371/226107115-c37fa472-13da-4edd-b613-e7f35a79724a.png">

**Comment by kongo09** [comment]
> That's how my display looks like

@petrutaraul  So Allergy Sleep has the same icon as Auto mode?

**Comment by kongo09** [comment]
> The only thing missing is child lock

Hm, that's strange. It should show up under configuration like this:

![image](https://user-images.githubusercontent.com/640121/226118982-a2d677b2-46b5-401d-9fd4-8c64fa6a6ecf.png)

I'll stick in some logging for the next beta to figure out why it is missing. The logic is the same as with other devices.

update: I found the bug, it will be fixed in the next beta

**Comment by kongo09** [comment]
> It works for me.

@petrutaraul  Did you try every single setting?

I'd like to prepare another beta using the same parameters as the AC3858 to experiment if these work as well.

**Comment by kongo09** [comment]
> it works without any problem

@Gh61  Does your device have a child lock?

**Comment by kongo09** [comment]
please try `v0.11.6-ac3854.2`

- child lock should now work
- I've changed the parameters to match those of AC3858. Let's see if that works as well. If not, I'll change it back.

**Comment by Gh61** [comment]
> > it works without any problem
> 
> @Gh61 Does your device have a child lock?

Yes, it has child lock, but it also isn't available in HA.
It has the same display and functions as in the posted video.
My country's Philips support says, that the Ac3854/51 and AC3858/51 are the same, the only difference is the front panel. Mine (3858) has some textured fabric over it, the 3854 is only plastic.

**Comment by kongo09** [comment]
Ok, so
- AC3854/51 and AC3858/51 are the same
- AC3854/50 and AC3858/50 are the same
- the /51 version has child lock and allergy sleep
- the /50 version lacks these two features

did I get this right?

**Comment by kongo09** [comment]
I refactored a bit. Hopefully, I didn't break anything.

Please try `v0.11.6-ac3854.3`

**Comment by Gh61** [comment]
> Ok, so
> 
> * AC3854/51 and AC3858/51 are the same
> * AC3854/50 and AC3858/50 are the same
> * the /51 version has child lock and allergy sleep
> * the /50 version lacks these two features
> 
> did I get this right?

I believe we can confirm this for /51 models and I think it should be the same for /50 models, as you stated.

**Comment by Gh61** [comment]
> I refactored a bit. Hopefully, I didn't break anything.
> 
> Please try `v0.11.6-ac3854.3`

I tried to install this latest beta and it is throwing some exception:

```
Tato chyba pochází z vlastní integrace.

Logger: homeassistant.loader
Source: custom_components/philips_airpurifier_coap/philips.py:876
Integration: Philips AirPurifier (with CoAP) (documentation, issues)
First occurred: 21:41:14 (1 occurrences)
Last logged: 21:41:14

Unexpected exception importing component custom_components.philips_airpurifier_coap
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/philips_airpurifier_coap/__init__.py", line 20, in <module>
    from .philips import Coordinator
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 876, in <module>
    MODEL_AC3854: PhilipsAC3854,
NameError: name 'PhilipsAC3854' is not defined

```

**Comment by raulpetruta** [comment]
> > That's how my display looks like
> 
> 
> 
> @petrutaraul  So Allergy Sleep has the same icon as Auto mode?

Yes

**Comment by Gh61** [comment]
> > > That's how my display looks like
> > 
> > 
> > @petrutaraul  So Allergy Sleep has the same icon as Auto mode?
> 
> Yes

The sleep button and auto icon on the display are lit in this mode simultaneously.

**Comment by raulpetruta** [comment]
I also have some errors:

Logger: homeassistant.loader
Source: custom_components/philips_airpurifier_coap/philips.py:876
Integration: Philips AirPurifier 
First occurred: 00:36:48 (1 occurrences) 
Last logged: 00:36:48

Unexpected exception importing component custom_components.philips_airpurifier_coap
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/philips_airpurifier_coap/__init__.py", line 20, in <module>
    from .philips import Coordinator
  File "/config/custom_components/philips_airpurifier_coap/philips.py", line 876, in <module>
    MODEL_AC3854: PhilipsAC3854,
NameError: name 'PhilipsAC3854' is not defined

**Comment by kongo09** [comment]
my mistake, please try `v0.11.6-ac3854.4`

to be on the safe side, you also might want to remove all your existing entities before trying the new beta. I've changed the naming so `MODEL_AC3854` doesn't exist anymore. Does that work?

**Comment by raulpetruta** [comment]
> my mistake, please try `v0.11.6-ac3854.4`
> 
> to be on the safe side, you also might want to remove all your existing entities before trying the new beta. I've changed the naming so `MODEL_AC3854` doesn't exist anymore. Does that work?

I have another error:

```
Logger: custom_components.philips_airpurifier_coap.fan
Source: custom_components/philips_airpurifier_coap/fan.py:45 
Integration: Philips AirPurifier ([documentation](https://github.com/kongo09/philips-airpurifier-coap), [issues](https://github.com/kongo09/philips-airpurifier-coap/issues)) 
First occurred: 12:12:03 (1 occurrences) 
Last logged: 12:12:03

Unsupported model: AC3854
```

**Comment by kongo09** [comment]
Did you remove your old entities before trying the new beta?

**Comment by raulpetruta** [comment]
> Did you remove your old entities before trying the new beta?

Apologies. I forgot to do that. I removed old entities and tried again and now it works. I can see the "Child lock" option. Thank you!

<img width="345" alt="image" src="https://user-images.githubusercontent.com/57073371/226171274-e5ffd1c2-9690-40ce-8f43-5a5716b5d9c5.png">

**Comment by kongo09** [comment]
Great,, do all the modes still work?

**Comment by raulpetruta** [comment]
> Great,, do all the modes still work?

Yes. All modes seem to work, but now I have a problem. I changed the device name from "My Device" to "Office Air Purifier" inside the app and now I can't connect it to HA anymore. 

I have the following errors: 

```
Logger: custom_components.philips_airpurifier_coap.config_flow
Source: custom_components/philips_airpurifier_coap/config_flow.py:86 
Integration: Philips AirPurifier ([documentation](https://github.com/kongo09/philips-airpurifier-coap), [issues](https://github.com/kongo09/philips-airpurifier-coap/issues)) 
First occurred: 13:49:46 (1 occurrences) 
Last logged: 13:49:46

Timeout, host 192.168.0.61 looks like a Philips AirPurifier but doesn't answer, aborting 
```

```
Logger: custom_components.philips_airpurifier_coap.config_flow
Source: custom_components/philips_airpurifier_coap/config_flow.py:197 
Integration: Philips AirPurifier ([documentation](https://github.com/kongo09/philips-airpurifier-coap), [issues](https://github.com/kongo09/philips-airpurifier-coap/issues)) 
First occurred: 13:50:07 (1 occurrences) 
Last logged: 13:50:07

Failed to connect: [Errno 113] received through errqueue
```

**Comment by raulpetruta** [comment]
> > Great,, do all the modes still work?
> 
> Yes. All modes seem to work, but now I have a problem. I changed the device name from "My Device" to "Office Air Purifier" inside the app and now I can't connect it to HA anymore.
> 
> I have the following errors:
> 
> ```
> Logger: custom_components.philips_airpurifier_coap.config_flow
> Source: custom_components/philips_airpurifier_coap/config_flow.py:86 
> Integration: Philips AirPurifier ([documentation](https://github.com/kongo09/philips-airpurifier-coap), [issues](https://github.com/kongo09/philips-airpurifier-coap/issues)) 
> First occurred: 13:49:46 (1 occurrences) 
> Last logged: 13:49:46
> 
> Timeout, host 192.168.0.61 looks like a Philips AirPurifier but doesn't answer, aborting 
> ```
> 
>  ```
> Logger: custom_components.philips_airpurifier_coap.config_flow
> Source: custom_components/philips_airpurifier_coap/config_flow.py:197 
> Integration: Philips AirPurifier ([documentation](https://github.com/kongo09/philips-airpurifier-coap), [issues](https://github.com/kongo09/philips-airpurifier-coap/issues)) 
> First occurred: 13:50:07 (1 occurrences) 
> Last logged: 13:50:07
> 
> Failed to connect: [Errno 113] received through errqueue
> ```

Update: I unplugged the Air Purifier and replugged it again and now it works. The only thing which is not working is "Speed 2". "Speed 2" sets the Air Purifier to Auto Mode

**Comment by kongo09** [comment]
> now I can't connect it to HA anymore

I guess that's the unfortunate connection error that many devices seem to have from time to time. Unplugging and restarting seems to solve it in many cases, but beyond that, there doesn't seem to be a cure.

**Comment by kongo09** [comment]
> "Speed 2" sets the Air Purifier to Auto Mode

I did revert to the data you've given above:

![image](https://user-images.githubusercontent.com/640121/226175799-9c6824b7-3fd2-49a2-a716-d5e2392d9c85.png)

This is what you said for Speed 2. Indeed, there is an anomaly here, as I would expect `mode` to be `M` and not `AG` as it is for Speed 1 and as it is for the AC3850/50 model. Let's assume you had a typo or some other glitch above and I'll change it to `M` and we test if it works.

Please try `v0.11.6-ac3854.5`

**Comment by kongo09** [comment]
@Gh61 Is the latest beta working for you as well?

**Comment by raulpetruta** [comment]
> > "Speed 2" sets the Air Purifier to Auto Mode
> 
> I did revert to the data you've given above:
> 
> ![image](https://user-images.githubusercontent.com/640121/226175799-9c6824b7-3fd2-49a2-a716-d5e2392d9c85.png)
> 
> This is what you said for Speed 2. Indeed, there is an anomaly here, as I would expect `mode` to be `M` and not `AG` as it is for Speed 1 and as it is for the AC3850/50 model. Let's assume you had a typo or some other glitch above and I'll change it to `M` and we test if it works.
> 
> Please try `v0.11.6-ac3854.5`

Now speed 2 works, but the auto mode does not work anymore.

**Comment by raulpetruta** [comment]
> > > "Speed 2" sets the Air Purifier to Auto Mode
> > 
> > 
> > I did revert to the data you've given above:
> > ![image](https://user-images.githubusercontent.com/640121/226175799-9c6824b7-3fd2-49a2-a716-d5e2392d9c85.png)
> > This is what you said for Speed 2. Indeed, there is an anomaly here, as I would expect `mode` to be `M` and not `AG` as it is for Speed 1 and as it is for the AC3850/50 model. Let's assume you had a typo or some other glitch above and I'll change it to `M` and we test if it works.
> > Please try `v0.11.6-ac3854.5`
> 
> Now speed 2 works, but the auto mode does not work anymore.

I found the problem. I had Auto+ mode enabled in the settings: 
![image](https://user-images.githubusercontent.com/57073371/226177349-de30b193-2b17-4737-8aa2-8349468262bd.png)

After disabling it, now the auto mode works too.

I can confirm that all the modes are completely functional.

**Comment by kongo09** [comment]
Oh, that's interesting. I've never heard of this Auto+ mode. Is that something that shows in the device parameters as well, so that I could add it, or is it controlled by the app?

**Comment by kongo09** [comment]
Overall, I think we're done here. Hopefully, this also still works for @Gh61 but if not, we can open a fresh issue. Original task seems solved. I'll do a proper release now.

**Comment by raulpetruta** [comment]
> Oh, that's interesting. I've never heard of this Auto+ mode. Is that something that shows in the device parameters as well, so that I could add it, or is it controlled by the app?

It is controlled by the app. Maybe the mode it's different compared to the default Auto mode. I will try to see and I will post the data here.

Thanks fro your help!

**Comment by Gh61** [comment]
@kongo09 Thank you for amazing work. Everything is working for me with the new release, the new mode and also the child lock.

**Comment by kongo09** [comment]
Happy to hear that! Thanks for all your quick (!) support. It wouldn't be possible without.

**Comment by Gh61** [comment]
I just noticed, that when I select mode "turbo", "sleep" or "allergy sleep", `preset_mode` and `percentage` attribute on fan entity is null.
For speed 1, speed 2 and auto it's OK.

@petrutaraul Is this working for you?

**Comment by kongo09** [comment]
That happens if the control pattern the integration sends to the device to set the requested mode does set the mode but does not match the internal state of the device after the setting.

To figure that out, can you share with me the parameters that the device reports after you have set one of the broken modes by getting them either from the command line or using the debugging option?

**Comment by Gh61** [comment]
Here are the parameters

## Turbo mode:
```
{"name": "Kdekoliv", "type": "AC3858", "modelid": "AC3858/51", "swversion": "Ms4418", "language": "EN", "DeviceVersion": "4.1.8", "range": "MarteHE", "Runtime": 103494212, "rssi": -41, "otacheck": false, "wifilog": false, "free_memory": 57232, "WifiVersion": "AWS_Philips_AIR@75.3", "ProductId": "20189e18982b11ebb0bb0254d6e7f842", "DeviceId": "c48970b2c11a11edb42fa393e35bd29f", "StatusType": "status", "ConnectType": "Online", "om": "t", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "uaset": "A", "mode": "T", "pm25": 1, "iaql": 1, "aqit": 4, "aqit_ext": 0, "tvoc": 4, "ddp": "1", "rddp": "2", "err": 0, "D0311F": 0, "D03180": 0, "D03R81": "000000000", "D03182": 1, "fltt1": "A3", "fltt2": "none", "fltsts0": 590, "fltsts1": 4800, "fltsts2": 65535, "filna": "0", "filid": "0", "flttotal0": 720, "flttotal1": 4800, "flttotal2": 65535}`
```

## Sleep mode:
```
{"name": "Kdekoliv", "type": "AC3858", "modelid": "AC3858/51", "swversion": "Ms4418", "language": "EN", "DeviceVersion": "4.1.8", "range": "MarteHE", "Runtime": 103587359, "rssi": -43, "otacheck": false, "wifilog": false, "free_memory": 57232, "WifiVersion": "AWS_Philips_AIR@75.3", "ProductId": "20189e18982b11ebb0bb0254d6e7f842", "DeviceId": "c48970b2c11a11edb42fa393e35bd29f", "StatusType": "status", "ConnectType": "Online", "om": "s", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "uaset": "A", "mode": "S", "pm25": 1, "iaql": 1, "aqit": 4, "aqit_ext": 0, "tvoc": 3, "ddp": "1", "rddp": "2", "err": 0, "D0311F": 0, "D03180": 0, "D03R81": "000000000", "D03182": 1, "fltt1": "A3", "fltt2": "none", "fltsts0": 590, "fltsts1": 4800, "fltsts2": 65535, "filna": "0", "filid": "0", "flttotal0": 720, "flttotal1": 4800, "flttotal2": 65535}
```

## Allergy Sleep mode:
```
{"name": "Kdekoliv", "type": "AC3858", "modelid": "AC3858/51", "swversion": "Ms4418", "language": "EN", "DeviceVersion": "4.1.8", "range": "MarteHE", "Runtime": 103680584, "rssi": -41, "otacheck": false, "wifilog": false, "free_memory": 57232, "WifiVersion": "AWS_Philips_AIR@75.3", "ProductId": "20189e18982b11ebb0bb0254d6e7f842", "DeviceId": "c48970b2c11a11edb42fa393e35bd29f", "StatusType": "status", "ConnectType": "Online", "om": "as", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "uaset": "A", "mode": "AS", "pm25": 17, "iaql": 4, "aqit": 4, "aqit_ext": 0, "tvoc": 2, "ddp": "1", "rddp": "1", "err": 0, "D0311F": 1, "D03180": 0, "D03R81": "000000000", "D03182": 1, "fltt1": "A3", "fltt2": "none", "fltsts0": 590, "fltsts1": 4800, "fltsts2": 65535, "filna": "0", "filid": "0", "flttotal0": 720, "flttotal1": 4800, "flttotal2": 65535}
```

**Comment by kongo09** [comment]
Looking at the parameters, it is clear why the mode's don't show up correctly for you.

However, the list is in conflict with @petrutaraul 's list. So maybe, the AC3854/51 and the AC3858/51 are not really the same? Let's wait for @petrutaraul 's feedback if the current settings are working for them and then I can separate the two models.

**Comment by Gh61** [comment]
@petrutaraul Can you please confirm that `preset_mode` and `percentage` attributes on your `fan.*` entity are not null for all your states?
You can look at the attributes in Developer Tools => States.

**Comment by raulpetruta** [comment]
Hi! Sorry for late response. I do not get any notifications on my phone or email. Siri suggested me to open this thread and I saw the comments.

For me, everything is working. I can set the fan to sleep or allergy slepp without any problem.

**Comment by raulpetruta** [comment]
Checked in developer tools and it seems that percentage and preset_mode are null.

![image](https://user-images.githubusercontent.com/57073371/227746245-78ca7528-4055-4f68-877d-8f1083cb17b2.png)

**Comment by kongo09** [comment]
Ok, thanks, I'll do a new release later today that hopefully fixes this. Ideally, both of you check if that works on your different models.

**Comment by kongo09** [comment]
I've changed the settings for both, the /50 and the /51 family. Can you both please try if this work now in `v0.12.1`.

Please note: if you set to `auto` or `allergy sleep` modes, there is no speed percentage, as these are not speeds but automatic modes. However, the `preset_mode` field should be set in any case.

**Comment by Gh61** [comment]
All modes are now working and showing as expected. Thank you.

**Comment by kongo09** [comment]
I assume that it now works generally. If not, let's open another issue.

**Comment by raulpetruta** [comment]
It works for me too. Thank you @kongo09 !

**Comment by kongo09** [comment]
Thanks for getting back and confirming! That's amazing.
