### ISSUE TITLE
Child lock support for AC2889/10

### ISSUE THREAD

**Issue by JoernBerkefeld** [kongo09/philips-airpurifier-coap#69]
Any chance one can activate that? The app does not offer it but the firmware seems to have a switch for it?

**Comment by kongo09** [comment]
I could stick it into the code and you can give it a try, if you like. The risk is, that we set something that cannot be undone on the device or the proper app.

**Comment by kongo09** [comment]
Please try beta `v0.12.1-2889-cl.1` and let me know if it works

**Comment by JoernBerkefeld** [comment]
afraid to ask: how do i install the beta? :D sorry

**Comment by kongo09** [comment]
select `redownload` in HACS and then the beta:

![image](https://user-images.githubusercontent.com/640121/228207399-b7df2eff-c63b-4f49-aa45-da4cdd848eef.png)

**Comment by JoernBerkefeld** [comment]
ok, thank you. did install that.

got that version but cannot find "child" or "lock" among the devices or entities. please excuse me if that's me being stupid now

**Comment by kongo09** [comment]
Did you delete your existing device and then configure it new? There should be a switch entity visible on the device page that you can access from the integration overview page?

**Comment by kongo09** [comment]
This is how it looks like:

![image](https://user-images.githubusercontent.com/640121/228394320-b820c3c5-e3ba-4cb5-b79b-fba2492018cb.png)

However, as I do have an AC2889 myself, I gave it a try and the setting doesn't work. So unfortunately, the idea is not feasible.

**Comment by JoernBerkefeld** [comment]
Thank you, will try that in the coming days when im back home :)
