### ISSUE TITLE
Support Request for Model AC0850

### ISSUE THREAD

**Issue by azuanaa** [kongo09/philips-airpurifier-coap#73]
Hi @kongo09, just bought a simple Philips Air Purifier model AC0850. It has 3 modes - Sleep, Auto and Turbo. No other button on the device. In the apps, 2 sensors available for air quality, Allergens (IAI) and PM2.5. Below is the collected raw data for this model for all 3 modes and data when it is turn off from the apps. Tell me if you need any other data for this device. Thanks in advance.

Mode Sleep
{
    "D01-02": "Purifier product",
    "D01-03": "My Room",
    "D01-04": "Pluto",
    "D01-05": "AC0850/20",
    "D01-07": "English",
    "D01-08": 2,
    "D01-09": 1,
    "D01-10": 2,
    "D01-11": 0,
    "D01-20": "0.1.2",
    "D01-21": "1.1.1",
    "MCUBoot": true,
    "Runtime": 16929305,
    "rssi": -44,
    "otacheck": false,
    "wifilog": false,
    "free_memory": 56392,
    "WifiVersion": "AWS_Philips_AIR@73.1",
    "ProductId": "763274f8cc3e11eca3f10217247a73aa",
    "DeviceId": "e52499bbe34f11ed9e77c7c102552817",
    "StatusType": "status",
    "ConnectType": "Online",
    "D03-02": "ON",
    "D03-03": false,
    "D03-04": 0,
    "D03-05": 0,
    "D03-11": "A",
    "D03-12": "Sleep",
    "D03-13": "s",
    "D03-32": 1,
    "D03-33": 6,
    "D03-42": "PM2.5",
    "D03-43": "PM2.5",
    "D03-44": 4,
    "aqit_ext": 0,
    "D03-64": 0,
    "D05-02": "A3",
    "D05-03": "none",
    "D05-07": 720,
    "D05-08": 4800,
    "D05-09": 0,
    "D05-13": 720,
    "D05-14": 4796,
    "D05-15": 0
}

Mode Auto
{
    "D01-02": "Purifier product",
    "D01-03": "My Room",
    "D01-04": "Pluto",
    "D01-05": "AC0850/20",
    "D01-07": "English",
    "D01-08": 2,
    "D01-09": 1,
    "D01-10": 2,
    "D01-11": 0,
    "D01-20": "0.1.2",
    "D01-21": "1.1.1",
    "MCUBoot": true,
    "Runtime": 17069094,
    "rssi": -46,
    "otacheck": false,
    "wifilog": false,
    "free_memory": 56392,
    "WifiVersion": "AWS_Philips_AIR@73.1",
    "ProductId": "763274f8cc3e11eca3f10217247a73aa",
    "DeviceId": "e52499bbe34f11ed9e77c7c102552817",
    "StatusType": "status",
    "ConnectType": "Online",
    "D03-02": "ON",
    "D03-03": false,
    "D03-04": 100,
    "D03-05": 100,
    "D03-11": "A",
    "D03-12": "Auto General",
    "D03-13": "1",
    "D03-32": 1,
    "D03-33": 2,
    "D03-42": "PM2.5",
    "D03-43": "PM2.5",
    "D03-44": 4,
    "aqit_ext": 0,
    "D03-64": 0,
    "D05-02": "A3",
    "D05-03": "none",
    "D05-07": 720,
    "D05-08": 4800,
    "D05-09": 0,
    "D05-13": 720,
    "D05-14": 4796,
    "D05-15": 0
}

Mode Turbo
{
    "D01-02": "Purifier product",
    "D01-03": "My Room",
    "D01-04": "Pluto",
    "D01-05": "AC0850/20",
    "D01-07": "English",
    "D01-08": 2,
    "D01-09": 1,
    "D01-10": 2,
    "D01-11": 0,
    "D01-20": "0.1.2",
    "D01-21": "1.1.1",
    "MCUBoot": true,
    "Runtime": 17276669,
    "rssi": -43,
    "otacheck": false,
    "wifilog": false,
    "free_memory": 56416,
    "WifiVersion": "AWS_Philips_AIR@73.1",
    "ProductId": "763274f8cc3e11eca3f10217247a73aa",
    "DeviceId": "e52499bbe34f11ed9e77c7c102552817",
    "StatusType": "status",
    "ConnectType": "Online",
    "D03-02": "ON",
    "D03-03": false,
    "D03-04": 100,
    "D03-05": 100,
    "D03-11": "A",
    "D03-12": "Turbo",
    "D03-13": "t",
    "D03-32": 1,
    "D03-33": 2,
    "D03-42": "PM2.5",
    "D03-43": "PM2.5",
    "D03-44": 4,
    "aqit_ext": 0,
    "D03-64": 0,
    "D05-02": "A3",
    "D05-03": "none",
    "D05-07": 720,
    "D05-08": 4800,
    "D05-09": 0,
    "D05-13": 720,
    "D05-14": 4796,
    "D05-15": 0
}

Device Off
{
    "D01-02": "Purifier product",
    "D01-03": "My Room",
    "D01-04": "Pluto",
    "D01-05": "AC0850/20",
    "D01-07": "English",
    "D01-08": 2,
    "D01-09": 1,
    "D01-10": 2,
    "D01-11": 0,
    "D01-20": "0.1.2",
    "D01-21": "1.1.1",
    "MCUBoot": true,
    "Runtime": 17376441,
    "rssi": -43,
    "otacheck": false,
    "wifilog": false,
    "free_memory": 56416,
    "WifiVersion": "AWS_Philips_AIR@73.1",
    "ProductId": "763274f8cc3e11eca3f10217247a73aa",
    "DeviceId": "e52499bbe34f11ed9e77c7c102552817",
    "StatusType": "status",
    "ConnectType": "Online",
    "D03-02": "OFF",
    "D03-03": false,
    "D03-04": 100,
    "D03-05": 100,
    "D03-11": "A",
    "D03-12": "Sleep",
    "D03-13": "0",
    "D03-32": 1,
    "D03-33": 5,
    "D03-42": "PM2.5",
    "D03-43": "PM2.5",
    "D03-44": 4,
    "aqit_ext": 0,
    "D03-64": 0,
    "D05-02": "A3",
    "D05-03": "none",
    "D05-07": 720,
    "D05-08": 4800,
    "D05-09": 0,
    "D05-13": 720,
    "D05-14": 4796,
    "D05-15": 0
}

**Comment by kongo09** [comment]
Thanks for sharing the data. This is a different type of model to most others. I'll take a look when I find some time...

**Comment by kongo09** [comment]
We still need to fix the pre-filter sensor here #81
