### ISSUE TITLE
AC0850 and AC1715 have no pre-filter

### ISSUE THREAD

**Issue by kongo09** [kongo09/philips-airpurifier-coap#81]
The status data of AC0850 and AC1715 suggest that these devices have a pre-filter, which they do not have. The corresponding sensor should not show up in Home Assistant.

**Comment by kongo09** [comment]
The problem is, that the integration does not provide a list for all available sensors of each model, but instead looks at the data that comes with the status report and interprets it. Internally, it identifies the status codes and assigns sensors, if the codes are in the data.

The two devices here have status codes for a pre-filter, even though the devices don't seem to have that and there is also no pre-filter mentioned in the manuals.

The code is `D05-13`. The total value of that sensor is `D05-07`. In the data provided here #73 both values are always 720, which might be because this sensor / filter does actually not exist. Can someone please check if this is also true for your devices? @micsimoen ? @wmkicker ?

**Comment by kongo09** [comment]
please try `v0.15.0-beta.1` and report back

**Comment by WMKicker** [comment]
> The code is `D05-13`. The total value of that sensor is `D05-07`. In the data provided here #73 both values are always 720, which might be because this sensor / filter does actually not exist. Can someone please check if this is also true for your devices? @MicSimoen ? @WMKicker ?

I can confirm that `D05-13` and `D05-07` both have the value 720.

**Comment by WMKicker** [comment]
> please try `v0.15.0-beta.1` and report back

The exclusion of unavailable filters in commit d13ce28 seems to break something. Only the fan entity is available and no sensor or filter values anymore.

**Comment by kongo09** [comment]
I might have broken something - can you share the debug log files please?

**Comment by WMKicker** [comment]
> I might have broken something - can you share the debug log files please?

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips_airpurifier_coap/sensor.py", line 68, in async_setup_entry
    model_class = model_to_class.get(model)
NameError: name 'model_to_class' is not defined`

**Comment by kongo09** [comment]
I see, I forgot an import. Please try `v0.15.0-beta.2`

**Comment by WMKicker** [comment]
Yes, now it works as expected. No entity is provided for the non existent pre-filter anymore.

**Comment by kongo09** [comment]
Great, I'll do a release then. Thanks for the help.

**Comment by eavyon** [comment]
I would like to add that my ac1715 does warns when the main filter should be cleaned on the outside which has a fine mesh. You could say that is a pre-filter. By removing this sensor I get no indication when I should do this cleaning procedure. Im not sure if there is a different sensor for this but I guess its the same.

**Comment by kongo09** [comment]
So does the sensor reflect that warning or do you believe a second sensor would be needed?

**Comment by eavyon** [comment]
Well if I remember correctly. The manual states cleaning the outside of the filter every month. The prefilter sensor represents 720 hours and it looks like its counting down correctly. My device is only on a few hours a day so this takes a lot longer than a month in my instance.

I will reset that prefilter warning tonight and let you know if it resets that sensor.

**Comment by eavyon** [comment]
The device doesnt let me reset. Probably the warning light needs to be on to reset it. That will take a while but I will post back then.

**Comment by MicSimoen** [comment]
Thanks for taking care of this, I was unable to do testing the last weeks.

**Comment by eavyon** [comment]
Well I can finally update this issue. And I will kindly ask to add in the sensor again and maybe rename it to something like filter cleanliness. At 0% the warning light comes on for filter cleaning..

Only when this alert was active I was able to reset the alarm and this sensor got back up to 100%. I  can only confirm this for the AC1715 but I guess its the same on the smaller one.

**Comment by kongo09** [comment]
I'll take a look, thanks for investigating

**Comment by PistolaPeteUK** [comment]
I just come across this as I've picked up a AC1715/30 and was looking through stuff to find out why the pre-filter clean sensor was missing. I have dumped out the data with aioairctrl and I can see that the data for the pre-filter time and time remaining (D05-07 and D05-13) are present and currently set to 720 and 702 (and falling) respectively so I'm happy to help out with anything I can do to get this working.

**Comment by eavyon** [comment]
For now I use the previous version 0.14 where the sensors are still available. At some point I guess they will be added again but better suited for this device model.

**Comment by PistolaPeteUK** [comment]
Thanks - rolled back to 0.14 and it's now appeared and working

**Comment by kongo09** [comment]
This should be fixed now for the AC1715 in the latest release. Please take a look and let me know.
