### ISSUE TITLE
Get current operation mode

### ISSUE THREAD

**Issue by Demo95** [kongo09/philips-airpurifier-coap#84]
Hey there, not sure if I missed the setting, but would it be possible to integrate a function that enables HA to read out the currently selected operation mode? 

The toggle kinda already "knows" this (https://i.imgur.com/TugxKBs.png), but I cannot check for it in my automation conditions.

My use case is e.g. to only set "auto" mode, when current mode is "sleep". Would stop my automation to set "auto" when it's already the active mode. I managed to create a workaround using the lights state, but that's a bit unstable since I have the feeling that the lights turn off after some time, no matter the mode.

Cheers

**Comment by kongo09** [comment]
This already exists:

![image](https://github.com/kongo09/philips-airpurifier-coap/assets/640121/21f7b8bb-1fc2-4147-9b64-093e447d0a84)

![image](https://github.com/kongo09/philips-airpurifier-coap/assets/640121/390bbb95-33f6-46b7-8353-96611d54f54f)

It's an attribute of the `fan` called `preset_mode`

**Comment by Demo95** [comment]
Found it, thanks for pointing me in the right direction.
