### ISSUE TITLE
AC3829 connected on rgerganov but not on this integration

### ISSUE THREAD

**Issue by kongo09** [kongo09/philips-airpurifier-coap#86]
I have a AC3829/10 model. Which has it's perks. (Wi-Fi disconnects quite often and I need to reconfigure it again... If anyone knows a fix for that, that would also be nice!)

I tried to use this plugin using HACS, unfortunately it does not connect, it says time out through the interface. I enabled debug logging, I found this there:

```
2023-06-27 22:04:14.978 DEBUG (MainThread) [custom_components.philips_airpurifier_coap.config_flow] trying to configure host: 10.0.0.129
2023-06-27 22:04:14.995 DEBUG (MainThread) [aioairctrl.coap.client] syncing
2023-06-27 22:04:14.996 DEBUG (MainThread) [coap] Sending request - Token: 5adf, Remote: <UDP6EndpointAddress 10.0.0.129>
2023-06-27 22:04:14.996 DEBUG (MainThread) [coap] Sending message <aiocoap.Message at 0x7f0cc7d2d590: NON POST (MID 6521, token 5adf) remote <UDP6EndpointAddress 10.0.0.129>, 1 option(s), 8 byte(s) payload>
2023-06-27 22:04:44.980 WARNING (MainThread) [custom_components.philips_airpurifier_coap.config_flow] Timeout, host 10.0.0.129 doesn't answer, aborting
```

However, this works: https://github.com/rgerganov/py-air-control

```
C:\Users\User>airctrl --ipaddr 10.0.0.129
Exchanging secret key with the device ...
Saving session_key <random stuff was here> to C:\Users\User/.pyairctrl
[om]                          Fan speed: 0
[pwr]                         Power: OFF
[cl]                          Child lock: False
[aqil]                        Light brightness: 50
[uil]                         Buttons light: OFF
[mode]                        Mode: manual
[func]                        Function: Purification & Humidification
[rhset]                       Target humidity: 70
[rh]                          Humidity: 41
[temp]                        Temperature: 25
[pm25]                        PM25: 5
[iaql]                        Allergen index: 2
[aqit]                        Air quality notification threshold: 7
[ddp]                         Used index: IAI
[wl]                          Water level: 100
```

And:

```
C:\Users\User>airctrl --ipaddr 10.0.0.129 --firmware
Name: AC3829_10
version: 15
upgrade:
state: idle
progress: 0
statusmsg:
mandatory: False
```

I'm using device firmware version 0.1.9, and WiFi firmware 15 according to the Philips Air+ app.

_Originally posted by @empewoow in https://github.com/kongo09/philips-airpurifier-coap/issues/83#issuecomment-1610151794_

**Comment by kongo09** [comment]
@empewoow

**Comment by empewoow** [comment]
Thanks for taking this serious! If you need any details or tests for me to try, please let me know.

**Comment by empewoow** [comment]
Any news on this? Is there something I can test?

**Comment by wldevries** [comment]
I have two AC1214/10 purifiers that only support http and not coap

What is the reason that this project is based on https://github.com/betaboon/aioairctrl which only supports coap, is it more robust or does it add more features? The original project supports more protocols which makes it superior in my eyes.

**Comment by kongo09** [comment]
It was the most stable and advanced starting point by the time. If someone goes through the trouble of adapting to other methods and submitted a pull request, that works be great.

It probably would have to changed on the library level (only).
