### ISSUE TITLE
The dirty filter warning was lost. AC1715 Device.

### ISSUE THREAD

**Issue by Jaguaza** [kongo09/philips-airpurifier-coap#87]
My filter cleaning sensor broke. I couldn't tell you in which version it happened.

AC1715 My Device.

![IMG_3753](https://github.com/kongo09/philips-airpurifier-coap/assets/46264854/f2f9570f-67e1-4b76-9219-c810662ff9b4)
![IMG_3754](https://github.com/kongo09/philips-airpurifier-coap/assets/46264854/4e5a8a32-c89a-47dc-a3e9-a34ce66d2824)

**Comment by Jaguaza** [comment]
@kongo09

**Comment by kongo09** [comment]
No worries, I have this on my radar. I'm just pretty busy in my day job right now, but I'll get to it... maybe someone can help and prepare a PR?

**Comment by Jaguaza** [comment]
Thanks

**Comment by kongo09** [comment]
Do you think you could use `aioairctrl` to get me a data reading of your device? There should be two data fields in your output: `D05-13` and `D05-14`. I would expect the first one to show the value 720 and never change. In the past, I assumed this was a true filter reading, but I don't think that's true for your model. I think that's the greyed-out filter in your screenshot with "limpieza".

The second data point should be your filter data and count down over time. The integration should actually pick that up. That should be the filter that says "cambio". But you're saying it disappeared...?

**Comment by PistolaPeteUK** [comment]
I have the same issue.

I first installed 0.15 when I got my 1715/30 last month and noticed there was only a main filter entity, not a prefilter entity.
Someone mentioned on #81 to roll back to 0.14 and when I did I got a work pre-filter entity.

If I upgrade past 0.14 the entity becomes unavailable again.

It appears D05-07 show "720" and D05-08 shows "4800" and those don't change.
D05-13 is currently "59" and D05-14 is currently showing "4139" (both of which are falling) and relate to the hours left on the pre-filter and main filter respectively.

I've attached the output json from aioairctrl for you to take a look at.
[output.json](https://github.com/kongo09/philips-airpurifier-coap/files/13860709/output.json)

**Comment by kongo09** [comment]
That's very helpful information, thanks!

**Comment by kongo09** [comment]
> It appears D05-07 show "720" and D05-08 shows "4800" and those don't change.

These are the total times the device counts down from to find out when the filter warning needs to be triggered.

**Comment by kongo09** [comment]
I've fixed this in the latest release, please let me know if it works

**Comment by Jaguaza** [comment]
For me it is working perfectly. The only thing I find that on Ha restart it has become very slow loading the integration.

Thank you for your hard work.

![image](https://github.com/kongo09/philips-airpurifier-coap/assets/46264854/c146a2d3-0e91-4e0b-a4f9-128268b39ff2)

**Comment by kongo09** [comment]
> The only thing I find that on Ha restart it has become very slow loading the integration.

Yes, that's not nice but I don't really understand if this is the integration or the CoAP protocol with the implementation of Philips.
