### ISSUE TITLE
AC3036 not applying settings

### ISSUE THREAD

**Issue by riveccia** [kongo09/philips-airpurifier-coap#9]
I just installed latest version (0.9.3) and configured an AC3036.
It seems that the integration is reading parameters in the correct way, but it is not possible to control the purifier.

If I try to change the configuration from HA, nothing happens.
If i did the same from the Philips app, the entity status is changed successfully.

**Comment by kongo09** [comment]
The Philips app is using the Philips cloud. Home Assistant is using a local connection. The two cannot be compared.

It feels like you have the annoying connectivity problem that most of us have with the latest Philips firmware. Would you mind providing some logging?

**Comment by riveccia** [comment]
Unfortunately it started working in last days without any modification. 
I will provide logs if it happens again.

Thank you very much for your support.
