### ISSUE TITLE
Problem with HA 2023.11.0

### ISSUE THREAD

**Issue by mc2343** [kongo09/philips-airpurifier-coap#91]
ERROR (MainThread) [custom_components.philips_airpurifier_coap.philips] config not ready, first refresh failed for host...

Philips-airpurifier-coap have problem to connect airpurifier on HA 2023.11.0.  When I came back to version HA 2023.10.5, I did not problem to connect to airpurifier.

Model: AC3858/50

**Comment by kongo09** [comment]
Definitely working for me on 2023.11.0

**Comment by mc2343** [comment]
Problem resolved, I reinstalled the add-on and it works.
