### ISSUE TITLE
Humidifiers 

### ISSUE THREAD

**Issue by Albastraoz** [kongo09/philips-airpurifier-coap#92]
Do you think it would be very difficult to add the humidifiers from Philips with some help? We moved to a new house so we need more. But the 2in1 is not for sale anymore so considering the others.

One of the products we are looking at: HU3916/10R1

**Comment by kongo09** [comment]
That depends on the device, if it speaks encrypted CoAP and if the command set is somewhat similar to the other devices. In theory it's not too difficult and mostly blocked on me (or someone elseI) finding time.

**Comment by kongo09** [comment]
Did you get that device?

The AC2729 is a humidifier that is supported.

I'll close the issue now. Feel free to reopen should you get your hands on the device you mentioned above and should you be able to extract some data from it with `aioairctrl`
