### ISSUE TITLE
AC3033/10 add support for Allergy Sleep mode 

### ISSUE THREAD

**Issue by Laho812** [kongo09/philips-airpurifier-coap#97]
Hi, I just bought a new AC3033/10 purifier and found this integration. I'm very happy so far but I found out this integration doesn't support the "Allergy sleep mode".

I would be very happy to see this mode added.

![Screenshot_20231130_222109_Air+.jpg](https://github.com/kongo09/philips-airpurifier-coap/assets/119891233/afcec9e7-0bc1-4858-9ca5-90c1be0e3619)

Thank you in advance!

If you need any information, feel free to contact me.

**Comment by kongo09** [comment]
You need to figure out the control code. Please see the readme on how to control the device from the command line to get all codes

**Comment by Laho812** [comment]
Hi, thank you for your quick reply. 

I followed the steps to aquire the raw status-data and got the following:

![Screenshot_20231130_225422_Home Assistant.jpg](https://github.com/kongo09/philips-airpurifier-coap/assets/119891233/9eac13c3-fd98-472c-a06d-25e3b1c42419)

I'm very sorry for pasting a screenshot but copy and paste out of the terminal using a phone isn't that easy. It seems the mode for Allergy Sleep mode is "AS". 

After changing it to sleep mode it is only "S":
![Screenshot_20231130_230633_Home Assistant.jpg](https://github.com/kongo09/philips-airpurifier-coap/assets/119891233/5aeecf15-214b-4b6c-9df0-7e866f2c2ceb)

**Comment by kongo09** [comment]
I've added support to the latest release, please try and let me know if it works.

**Comment by Laho812** [comment]
> I've added support to the latest release, please try and let me know if it works.

Thank you very much! It works very well!
