### ISSUE TITLE
AC3836/09 Raw  Data

### ISSUE THREAD

**Issue by xiaodongyichuan** [kongo09/philips-airpurifier-coap#98]
{"name": "Air Purifier", "type": "AC3836", "modelid": "AC3836/09", "MCUBoot": true, "swversion": "Ms4111", "language": "ZH_CH", "DeviceVersion": "1.1.1", "range": "MarsHE", "Runtime": 110549, "rssi": -51, "otacheck": false, "wifilog": false, "free_memory": 58328, "WifiVersion": "AWS_Philips_AIR@73.1", "ProductId": "c69d6c66c4d111ea8cf80213f13981ec", "DeviceId": "dd44902ec52611ebbb8ed29429ef71e3", "StatusType": "status", "ConnectType": "Online", "om": "s", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "uaset": "F", "mode": "S", "pm25": 0, "iaql": 1, "aqit": 4, "aqit_ext": 0, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 307, "fltsts1": 768, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012"}

**Comment by xiaodongyichuan** [comment]
{"name": "Air Purifier", "type": "AC3836", "modelid": "AC3836/09", "MCUBoot": true, "swversion": "Ms4111", "language": "ZH_CH", "DeviceVersion": "1.1.1", "range": "MarsHE", "Runtime": 395719, "rssi": -51, "otacheck": false, "wifilog": false, "free_memory": 58328, "WifiVersion": "AWS_Philips_AIR@73.1", "ProductId": "c69d6c66c4d111ea8cf80213f13981ec", "DeviceId": "dd44902ec52611ebbb8ed29429ef71e3", "StatusType": "status", "ConnectType": "Online", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "uaset": "F", "mode": "AG", "pm25": 9, "iaql": 1, "aqit": 4, "aqit_ext": 0, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 307, "fltsts1": 768, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012"}

**Comment by kongo09** [comment]
Which modes does your device have?
- Auto
- Sleep
- Turbo

What about manual speed modes, do they exist?

Do you have child lock?

Do you have a Gas sensor?

**Comment by xiaodongyichuan** [comment]
> Which modes does your device have?
> 
>     * Auto
> 
>     * Sleep
> 
>     * Turbo
> 
> 
> What about manual speed modes, do they exist?
> 
> Do you have child lock?
> 
> Do you have a Gas sensor?


Yes, It has three mode: Auto,Sleep,Trubo;
There is no manual speed mode.
And there is no child lock.
And there is Gas Sensor.
And it support turn on light. 
The Screen is look like this:
![微信图片_20240109095707](https://github.com/kongo09/philips-airpurifier-coap/assets/26026825/df21322a-e208-422b-826b-bdc3046f5e42)

**Comment by kongo09** [comment]
I've now put the AC3836 into the latest release. There are, however, a few questions where I would need your feedback:

- does it work overall?
- does the Gas sensor show up correctly?
- does the Gas sensor show the correct values and is the unit correct? (I've used the data from total organic compounds - tvoc - in the data, but I'm not sure if that is really the gas sensor)
- do you get two light switches?
- do both switches work, including the dimming of the brightness switch?
- anything else?

Thanks for your help

**Comment by xiaodongyichuan** [comment]
> I've now put the AC3836 into the latest release. There are, however, a few questions where I would need your feedback:
> 
>     * does it work overall?
> 
>     * does the Gas sensor show up correctly?
> 
>     * does the Gas sensor show the correct values and is the unit correct? (I've used the data from total organic compounds - tvoc - in the data, but I'm not sure if that is really the gas sensor)
> 
>     * do you get two light switches?
> 
>     * do both switches work, including the dimming of the brightness switch?
> 
>     * anything else?
> 
> 
> Thanks for your help



Thanks for your help
Thanks
Now, it works overall.
Gas sensor show correct,but i didn't see air_quality_index in my device,maybe my device didn't support it. Other sensors data is similar to.my app.
I have to light switch, and they also work well.But my device doesn't support dimming, the button now effect is turn on and off light circle,it show different colors for air quality.
Follow is effect snapshot
![Screenshot_20240110_225804_io homeassistant companion android](https://github.com/kongo09/philips-airpurifier-coap/assets/26026825/1339b831-6058-40da-a28a-556f309811a4)

**Comment by kongo09** [comment]
So if you click on the display backlight, can you dim anything? Or is that switch useless and I better remove it?

**Comment by xiaodongyichuan** [comment]
> So if you click on the display backlight, can you dim anything? Or is that switch useless and I better remove it?

It also work, it can dim button light on device.
Olny child clock is useless.

**Comment by xiaodongyichuan** [comment]
> So if you click on the display backlight, can you dim anything? Or is that switch useless and I better remove it?

Light brightness button now effect is turn on and off light circle,it show different colors for air quality.

So the two light switches is both useful.

**Comment by kongo09** [comment]
> Olny child clock is useless.

Why is it useless? Does it not work?

**Comment by xiaodongyichuan** [comment]
> So if you click on the display backlight, can you dim anything? Or is that switch useless and I better remove it?

Light brightness button now effect is turn on and off light circle,it show different colors for air quality.

So the two light switches is both useful.

> > Olny child clock is useless.
> 
> Why is it useless? Does it not work?

Because AC3836 don't have child lock function, so it is useless.

**Comment by kongo09** [comment]
Ah, sorry. I'll remove the child lock in the next release then. You'll have to delete the useless sensor manually in HA when it greys out after the update. I'll close this issue as everything seems to work.

Have fun!
